/*
 Highmaps JS v8.0.4 (2020-03-26)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(w){d(w);d.Highcharts=w;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function w(c,r,d,l){c.hasOwnProperty(r)||(c[r]=l.apply(null,d))}d=d?d._modules:{};w(d,"parts-map/MapAxis.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(c,r){var d=r.addEvent,l=r.pick;c=c.Axis;d(c,"getSeriesExtremes",
function(){var p=[];this.isXAxis&&(this.series.forEach(function(h,c){h.useMapGeometry&&(p[c]=h.xData,h.xData=[])}),this.seriesXData=p)});d(c,"afterGetSeriesExtremes",function(){var p=this.seriesXData,h;if(this.isXAxis){var c=l(this.dataMin,Number.MAX_VALUE);var d=l(this.dataMax,-Number.MAX_VALUE);this.series.forEach(function(r,x){r.useMapGeometry&&(c=Math.min(c,l(r.minX,c)),d=Math.max(d,l(r.maxX,d)),r.xData=p[x],h=!0)});h&&(this.dataMin=c,this.dataMax=d);delete this.seriesXData}});d(c,"afterSetAxisTranslation",
function(){var p=this.chart;var h=p.plotWidth/p.plotHeight;p=p.xAxis[0];var c;"yAxis"===this.coll&&"undefined"!==typeof p.transA&&this.series.forEach(function(h){h.preserveAspectRatio&&(c=!0)});if(c&&(this.transA=p.transA=Math.min(this.transA,p.transA),h/=(p.max-p.min)/(this.max-this.min),h=1>h?this:p,p=(h.max-h.min)*h.transA,h.pixelPadding=h.len-p,h.minPixelPadding=h.pixelPadding/2,p=h.fixTo)){p=p[1]-h.toValue(p[0],!0);p*=h.transA;if(Math.abs(p)>h.minPixelPadding||h.min===h.dataMin&&h.max===h.dataMax)p=
0;h.minPixelPadding-=p}});d(c,"render",function(){this.fixTo=null})});w(d,"parts-map/ColorSeriesMixin.js",[d["parts/Globals.js"]],function(c){c.colorPointMixin={setVisible:function(c){var d=this,l=c?"show":"hide";d.visible=d.options.visible=!!c;["graphic","dataLabel"].forEach(function(c){if(d[c])d[c][l]()})}};c.colorSeriesMixin={optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var c=this,d=this.options.nullColor,l=this.colorAxis,p=this.colorKey;(this.data.length?this.data:this.points).forEach(function(h){var r=
h.getNestedProperty(p);if(r=h.options.color||(h.isNull||null===h.value?d:l&&"undefined"!==typeof r?l.toColor(r,h):h.color||c.color))h.color=r})}}});w(d,"parts-map/ColorAxis.js",[d["parts/Globals.js"],d["parts/Color.js"],d["parts/Point.js"],d["parts/Legend.js"],d["mixins/legend-symbol.js"],d["parts/Utilities.js"]],function(c,d,t,l,p,h){"";var r=d.parse;d=h.addEvent;var z=h.erase,u=h.extend,x=h.Fx,a=h.isNumber,k=h.merge,g=h.pick,n=h.splat,y=c.Axis;h=c.Chart;var v=c.Series,q=c.colorPointMixin,f=c.noop;
u(v.prototype,c.colorSeriesMixin);u(t.prototype,q);h.prototype.collectionsWithUpdate.push("colorAxis");h.prototype.collectionsWithInit.colorAxis=[h.prototype.addColorAxis];var b=c.ColorAxis=function(){this.init.apply(this,arguments)};u(b.prototype,y.prototype);u(b.prototype,{defaultColorAxisOptions:{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},
minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0},keepProps:["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"].concat(y.prototype.keepProps),init:function(e,b){this.coll="colorAxis";var m=this.buildOptions.call(e,this.defaultColorAxisOptions,b);y.prototype.init.call(this,e,m);b.dataClasses&&this.initDataClasses(b);this.initStops();this.horiz=!m.opposite;this.zoomEnabled=!1;this.defaultLegendLength=200},initDataClasses:function(e){var b=this.chart,a,
A=0,f=b.options.chart.colorCount,g=this.options,n=e.dataClasses.length;this.dataClasses=a=[];this.legendItems=[];e.dataClasses.forEach(function(e,m){e=k(e);a.push(e);if(b.styledMode||!e.color)"category"===g.dataClassColor?(b.styledMode||(m=b.options.colors,f=m.length,e.color=m[A]),e.colorIndex=A,A++,A===f&&(A=0)):e.color=r(g.minColor).tweenTo(r(g.maxColor),2>n?.5:m/(n-1))})},hasData:function(){return!(!this.tickPositions||!this.tickPositions.length)},setTickPositions:function(){if(!this.dataClasses)return y.prototype.setTickPositions.call(this)},
initStops:function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(e){e.color=r(e[1])})},buildOptions:function(e,b){var m=this.options.legend,a=b.layout?"vertical"!==b.layout:"vertical"!==m.layout;return k(e,{side:a?2:1,reversed:!a},b,{opposite:!a,showEmpty:!1,title:null,visible:m.enabled&&(b?!1!==b.visible:!0)})},setOptions:function(e){y.prototype.setOptions.call(this,e);this.options.crosshair=this.options.marker},setAxisSize:function(){var e=
this.legendSymbol,b=this.chart,a=b.options.legend||{},f,g;e?(this.left=a=e.attr("x"),this.top=f=e.attr("y"),this.width=g=e.attr("width"),this.height=e=e.attr("height"),this.right=b.chartWidth-a-g,this.bottom=b.chartHeight-f-e,this.len=this.horiz?g:e,this.pos=this.horiz?a:f):this.len=(this.horiz?a.symbolWidth:a.symbolHeight)||this.defaultLegendLength},normalizedValue:function(e){this.isLog&&(e=this.val2lin(e));return 1-(this.max-e)/(this.max-this.min||1)},toColor:function(e,b){var m=this.stops,a=this.dataClasses,
f;if(a)for(f=a.length;f--;){var g=a[f];var k=g.from;m=g.to;if(("undefined"===typeof k||e>=k)&&("undefined"===typeof m||e<=m)){var n=g.color;b&&(b.dataClass=f,b.colorIndex=g.colorIndex);break}}else{e=this.normalizedValue(e);for(f=m.length;f--&&!(e>m[f][0]););k=m[f]||m[f+1];m=m[f+1]||k;e=1-(m[0]-e)/(m[0]-k[0]||1);n=k.color.tweenTo(m.color,e)}return n},getOffset:function(){var e=this.legendGroup,b=this.chart.axisOffset[this.side];e&&(this.axisParent=e,y.prototype.getOffset.call(this),this.added||(this.added=
!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=b)},setLegendColor:function(){var e=this.reversed;var b=e?1:0;e=e?0:1;b=this.horiz?[b,0,e,0]:[0,e,0,b];this.legendColor={linearGradient:{x1:b[0],y1:b[1],x2:b[2],y2:b[3]},stops:this.stops}},drawLegendSymbol:function(b,m){var e=b.padding,a=b.options,f=this.horiz,k=g(a.symbolWidth,f?this.defaultLegendLength:12),n=g(a.symbolHeight,f?12:this.defaultLegendLength),c=g(a.labelPadding,f?16:30);a=g(a.itemDistance,10);this.setLegendColor();
m.legendSymbol=this.chart.renderer.rect(0,b.baseline-11,k,n).attr({zIndex:1}).add(m.legendGroup);this.legendItemWidth=k+e+(f?a:c);this.legendItemHeight=n+e+(f?c:0)},setState:function(b){this.series.forEach(function(e){e.setState(b)})},visible:!0,setVisible:f,getSeriesExtremes:function(){var b=this.series,m=b.length,a;this.dataMin=Infinity;for(this.dataMax=-Infinity;m--;){var f=b[m];var k=f.colorKey=g(f.options.colorKey,f.colorKey,f.pointValKey,f.zoneAxis,"y");var n=f.pointArrayMap;var c=f[k+"Min"]&&
f[k+"Max"];if(f[k+"Data"])var h=f[k+"Data"];else if(n){h=[];n=n.indexOf(k);var q=f.yData;if(0<=n&&q)for(a=0;a<q.length;a++)h.push(g(q[a][n],q[a]))}else h=f.yData;c?(f.minColorValue=f[k+"Min"],f.maxColorValue=f[k+"Max"]):(h=v.prototype.getExtremes.call(f,h),f.minColorValue=h.dataMin,f.maxColorValue=h.dataMax);"undefined"!==typeof f.minColorValue&&(this.dataMin=Math.min(this.dataMin,f.minColorValue),this.dataMax=Math.max(this.dataMax,f.maxColorValue));c||v.prototype.applyExtremes.call(f)}},drawCrosshair:function(b,
m){var e=m&&m.plotX,a=m&&m.plotY,f=this.pos,g=this.len;if(m){var k=this.toPixels(m.getNestedProperty(m.series.colorKey));k<f?k=f-2:k>f+g&&(k=f+g+2);m.plotX=k;m.plotY=this.len-k;y.prototype.drawCrosshair.call(this,b,m);m.plotX=e;m.plotY=a;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||this.cross.attr({fill:this.crosshair.color}))}},getPlotLinePath:function(b){var e=
b.translatedValue;return a(e)?this.horiz?["M",e-4,this.top-6,"L",e+4,this.top-6,e,this.top,"Z"]:["M",this.left,e,"L",this.left-6,e+6,this.left-6,e-6,"Z"]:y.prototype.getPlotLinePath.apply(this,arguments)},update:function(b,m){var e=this.chart,a=e.legend,f=this.buildOptions.call(e,{},b);this.series.forEach(function(b){b.isDirtyData=!0});(b.dataClasses&&a.allItems||this.dataClasses)&&this.destroyItems();e.options[this.coll]=k(this.userOptions,f);y.prototype.update.call(this,f,m);this.legendItem&&(this.setLegendColor(),
a.colorizeItem(this,!0))},destroyItems:function(){var b=this.chart;this.legendItem?b.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(e){b.legend.destroyItem(e)});b.isDirtyLegend=!0},remove:function(b){this.destroyItems();y.prototype.remove.call(this,b)},getDataClassLegendSymbols:function(){var b=this,m=this.chart,a=this.legendItems,g=m.options.legend,k=g.valueDecimals,n=g.valueSuffix||"",c;a.length||this.dataClasses.forEach(function(e,g){var h=!0,q=e.from,A=e.to,B=m.numberFormatter;
c="";"undefined"===typeof q?c="< ":"undefined"===typeof A&&(c="> ");"undefined"!==typeof q&&(c+=B(q,k)+n);"undefined"!==typeof q&&"undefined"!==typeof A&&(c+=" - ");"undefined"!==typeof A&&(c+=B(A,k)+n);a.push(u({chart:m,name:c,options:{},drawLegendSymbol:p.drawRectangle,visible:!0,setState:f,isDataClass:!0,setVisible:function(){h=this.visible=!h;b.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===g&&b.setVisible(h)})});m.legend.colorizeItem(this,h)}},e))});return a},beforePadding:!1,
name:""});["fill","stroke"].forEach(function(b){x.prototype[b+"Setter"]=function(){this.elem.attr(b,r(this.start).tweenTo(r(this.end),this.pos),null,!0)}});d(h,"afterGetAxes",function(){var e=this,m=e.options;this.colorAxis=[];m.colorAxis&&(m.colorAxis=n(m.colorAxis),m.colorAxis.forEach(function(m,a){m.index=a;new b(e,m)}))});d(v,"bindAxes",function(){var b=this.axisTypes;b?-1===b.indexOf("colorAxis")&&b.push("colorAxis"):this.axisTypes=["colorAxis"]});d(l,"afterGetAllItems",function(b){var e=[],
a,f;(this.chart.colorAxis||[]).forEach(function(m){(a=m.options)&&a.showInLegend&&(a.dataClasses&&a.visible?e=e.concat(m.getDataClassLegendSymbols()):a.visible&&e.push(m),m.series.forEach(function(e){if(!e.options.showInLegend||a.dataClasses)"point"===e.options.legendType?e.points.forEach(function(e){z(b.allItems,e)}):z(b.allItems,e)}))});for(f=e.length;f--;)b.allItems.unshift(e[f])});d(l,"afterColorizeItem",function(b){b.visible&&b.item.legendColor&&b.item.legendSymbol.attr({fill:b.item.legendColor})});
d(l,"afterUpdate",function(){var b=this.chart.colorAxis;b&&b.forEach(function(b,e,a){b.update({},a)})});d(v,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()})});w(d,"parts-map/ColorMapSeriesMixin.js",[d["parts/Globals.js"],d["parts/Point.js"],d["parts/Utilities.js"]],function(c,d,t){var l=t.defined;t=c.noop;var p=c.seriesTypes;c.colorMapPointMixin={dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&
-Infinity!==this.value},setState:function(c){d.prototype.setState.call(this,c);this.graphic&&this.graphic.attr({zIndex:"hover"===c?1:0})}};c.colorMapSeriesMixin={pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:t,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:p.column.prototype.pointAttribs,colorAttribs:function(c){var h={};l(c.color)&&(h[this.colorProp||"fill"]=c.color);return h}}});w(d,"parts-map/MapNavigation.js",
[d["parts/Globals.js"],d["parts/Utilities.js"]],function(c,d){function r(a){a&&(a.preventDefault&&a.preventDefault(),a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)}function l(a){this.init(a)}var p=d.addEvent,h=d.extend,C=d.merge,z=d.objectEach,u=d.pick;d=c.Chart;var x=c.doc;l.prototype.init=function(a){this.chart=a;a.mapNavButtons=[]};l.prototype.update=function(a){var k=this.chart,g=k.options.mapNavigation,c,d,v,q,f,b=function(b){this.handler.call(k,b);r(b)},e=k.mapNavButtons;a&&(g=k.options.mapNavigation=
C(k.options.mapNavigation,a));for(;e.length;)e.pop().destroy();u(g.enableButtons,g.enabled)&&!k.renderer.forExport&&z(g.buttons,function(a,n){c=C(g.buttonOptions,a);k.styledMode||(d=c.theme,d.style=C(c.theme.style,c.style),q=(v=d.states)&&v.hover,f=v&&v.select);a=k.renderer.button(c.text,0,0,b,d,q,f,0,"zoomIn"===n?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[n]).attr({width:c.width,height:c.height,title:k.options.lang[n],padding:c.padding,
zIndex:5}).add();a.handler=c.onclick;p(a.element,"dblclick",r);e.push(a);var m=c,D=p(k,"load",function(){a.align(h(m,{width:a.width,height:2*a.height}),null,m.alignTo);D()})});this.updateEvents(g)};l.prototype.updateEvents=function(a){var k=this.chart;u(a.enableDoubleClickZoom,a.enabled)||a.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||p(k.container,"dblclick",function(a){k.pointer.onContainerDblClick(a)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());u(a.enableMouseWheelZoom,
a.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||p(k.container,"undefined"===typeof x.onmousewheel?"DOMMouseScroll":"mousewheel",function(a){k.pointer.onContainerMouseWheel(a);r(a);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};h(d.prototype,{fitToBox:function(a,k){[["x","width"],["y","height"]].forEach(function(g){var c=g[0];g=g[1];a[c]+a[g]>k[c]+k[g]&&(a[g]>k[g]?(a[g]=k[g],a[c]=k[c]):a[c]=k[c]+k[g]-a[g]);a[g]>k[g]&&(a[g]=k[g]);a[c]<k[c]&&(a[c]=k[c])});
return a},mapZoom:function(a,c,g,h,d){var k=this.xAxis[0],q=k.max-k.min,f=u(c,k.min+q/2),b=q*a;q=this.yAxis[0];var e=q.max-q.min,m=u(g,q.min+e/2);e*=a;f=this.fitToBox({x:f-b*(h?(h-k.pos)/k.len:.5),y:m-e*(d?(d-q.pos)/q.len:.5),width:b,height:e},{x:k.dataMin,y:q.dataMin,width:k.dataMax-k.dataMin,height:q.dataMax-q.dataMin});b=f.x<=k.dataMin&&f.width>=k.dataMax-k.dataMin&&f.y<=q.dataMin&&f.height>=q.dataMax-q.dataMin;h&&(k.fixTo=[h-k.pos,c]);d&&(q.fixTo=[d-q.pos,g]);"undefined"===typeof a||b?(k.setExtremes(void 0,
void 0,!1),q.setExtremes(void 0,void 0,!1)):(k.setExtremes(f.x,f.x+f.width,!1),q.setExtremes(f.y,f.y+f.height,!1));this.redraw()}});p(d,"beforeRender",function(){this.mapNavigation=new l(this);this.mapNavigation.update()});c.MapNavigation=l});w(d,"parts-map/MapPointer.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(c,d){var r=d.extend,l=d.pick;d=d.wrap;c=c.Pointer;r(c.prototype,{onContainerDblClick:function(c){var d=this.chart;c=this.normalize(c);d.options.mapNavigation.enableDoubleClickZoomTo?
d.pointer.inClass(c.target,"highcharts-tracker")&&d.hoverPoint&&d.hoverPoint.zoomTo():d.isInsidePlot(c.chartX-d.plotLeft,c.chartY-d.plotTop)&&d.mapZoom(.5,d.xAxis[0].toValue(c.chartX),d.yAxis[0].toValue(c.chartY),c.chartX,c.chartY)},onContainerMouseWheel:function(c){var d=this.chart;c=this.normalize(c);var l=c.detail||-(c.wheelDelta/120);d.isInsidePlot(c.chartX-d.plotLeft,c.chartY-d.plotTop)&&d.mapZoom(Math.pow(d.options.mapNavigation.mouseWheelSensitivity,l),d.xAxis[0].toValue(c.chartX),d.yAxis[0].toValue(c.chartY),
c.chartX,c.chartY)}});d(c.prototype,"zoomOption",function(c){var d=this.chart.options.mapNavigation;l(d.enableTouchZoom,d.enabled)&&(this.chart.options.chart.pinchType="xy");c.apply(this,[].slice.call(arguments,1))});d(c.prototype,"pinchTranslate",function(c,d,l,r,t,x,a){c.call(this,d,l,r,t,x,a);"map"===this.chart.options.chart.type&&this.hasZoom&&(c=r.scaleX>r.scaleY,this.pinchTranslateDirection(!c,d,l,r,t,x,a,c?r.scaleX:r.scaleY))})});w(d,"parts-map/MapSeries.js",[d["parts/Globals.js"],d["mixins/legend-symbol.js"],
d["parts/Point.js"],d["parts/Utilities.js"]],function(c,d,t,l){var p=l.extend,h=l.fireEvent,r=l.getNestedProperty,z=l.isArray,u=l.isNumber,x=l.merge,a=l.objectEach,k=l.pick,g=l.seriesType,n=l.splat,y=c.colorMapPointMixin,v=c.noop,q=c.Series,f=c.seriesTypes;g("map","scatter",{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},
turboThreshold:0,allAreas:!0,borderColor:"#cccccc",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:"#cccccc"},inactive:{opacity:1}}},x(c.colorMapSeriesMixin,{type:"map",getExtremesFromAll:!0,useMapGeometry:!0,forceDL:!0,searchPoint:v,directTouch:!0,preserveAspectRatio:!0,pointArrayMap:["value"],setOptions:function(b){b=q.prototype.setOptions.call(this,b);var e=b.joinBy;null===e&&(e="_i");e=this.joinBy=n(e);e[1]||(e[1]=e[0]);return b},getBox:function(b){var e=
Number.MAX_VALUE,a=-e,f=e,g=-e,d=e,q=e,n=this.xAxis,h=this.yAxis,l;(b||[]).forEach(function(b){if(b.path){"string"===typeof b.path&&(b.path=c.splitPath(b.path));var m=b.path||[],n=m.length,h=!1,A=-e,D=e,B=-e,v=e,r=b.properties;if(!b._foundBox){for(;n--;)u(m[n])&&(h?(A=Math.max(A,m[n]),D=Math.min(D,m[n])):(B=Math.max(B,m[n]),v=Math.min(v,m[n])),h=!h);b._midX=D+(A-D)*k(b.middleX,r&&r["hc-middle-x"],.5);b._midY=v+(B-v)*k(b.middleY,r&&r["hc-middle-y"],.5);b._maxX=A;b._minX=D;b._maxY=B;b._minY=v;b.labelrank=
k(b.labelrank,(A-D)*(B-v));b._foundBox=!0}a=Math.max(a,b._maxX);f=Math.min(f,b._minX);g=Math.max(g,b._maxY);d=Math.min(d,b._minY);q=Math.min(b._maxX-b._minX,b._maxY-b._minY,q);l=!0}});l&&(this.minY=Math.min(d,k(this.minY,e)),this.maxY=Math.max(g,k(this.maxY,-e)),this.minX=Math.min(f,k(this.minX,e)),this.maxX=Math.max(a,k(this.maxX,-e)),n&&"undefined"===typeof n.options.minRange&&(n.minRange=Math.min(5*q,(this.maxX-this.minX)/5,n.minRange||e)),h&&"undefined"===typeof h.options.minRange&&(h.minRange=
Math.min(5*q,(this.maxY-this.minY)/5,h.minRange||e)))},hasData:function(){return!!this.processedXData.length},getExtremes:function(){var b=q.prototype.getExtremes.call(this,this.valueData),e=b.dataMin;b=b.dataMax;this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);u(e)&&(this.valueMin=e);u(b)&&(this.valueMax=b);return{dataMin:this.minY,dataMax:this.maxY}},translatePath:function(b){var e=!1,a=this.xAxis,f=this.yAxis,c=a.min,g=a.transA;a=a.minPixelPadding;var k=f.min,d=f.transA;
f=f.minPixelPadding;var q,n=[];if(b)for(q=b.length;q--;)u(b[q])?(n[q]=e?(b[q]-c)*g+a:(b[q]-k)*d+f,e=!e):n[q]=b[q];return n},setData:function(b,e,m,f){var g=this.options,k=this.chart.options.chart,d=k&&k.map,n=g.mapData,h=this.joinBy,v=g.keys||this.pointArrayMap,l=[],B={},p=this.chart.mapTransforms;!n&&d&&(n="string"===typeof d?c.maps[d]:d);b&&b.forEach(function(e,a){var f=0;if(u(e))b[a]={value:e};else if(z(e)){b[a]={};!g.keys&&e.length>v.length&&"string"===typeof e[0]&&(b[a]["hc-key"]=e[0],++f);for(var m=
0;m<v.length;++m,++f)v[m]&&"undefined"!==typeof e[f]&&(0<v[m].indexOf(".")?t.prototype.setNestedProperty(b[a],e[f],v[m]):b[a][v[m]]=e[f])}h&&"_i"===h[0]&&(b[a]._i=a)});this.getBox(b);(this.chart.mapTransforms=p=k&&k.mapTransforms||n&&n["hc-transform"]||p)&&a(p,function(b){b.rotation&&(b.cosAngle=Math.cos(b.rotation),b.sinAngle=Math.sin(b.rotation))});if(n){"FeatureCollection"===n.type&&(this.mapTitle=n.title,n=c.geojson(n,this.type,this));this.mapData=n;this.mapMap={};for(p=0;p<n.length;p++)k=n[p],
d=k.properties,k._i=p,h[0]&&d&&d[h[0]]&&(k[h[0]]=d[h[0]]),B[k[h[0]]]=k;this.mapMap=B;if(b&&h[1]){var y=h[1];b.forEach(function(b){b=r(y,b);B[b]&&l.push(B[b])})}if(g.allAreas){this.getBox(n);b=b||[];if(h[1]){var w=h[1];b.forEach(function(b){l.push(r(w,b))})}l="|"+l.map(function(b){return b&&b[h[0]]}).join("|")+"|";n.forEach(function(e){h[0]&&-1!==l.indexOf("|"+e[h[0]]+"|")||(b.push(x(e,{value:null})),f=!1)})}else this.getBox(l)}q.prototype.setData.call(this,b,e,m,f)},drawGraph:v,drawDataLabels:v,doFullTranslate:function(){return this.isDirtyData||
this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans},translate:function(){var b=this,e=b.xAxis,a=b.yAxis,f=b.doFullTranslate();b.generatePoints();b.data.forEach(function(m){u(m._midX)&&u(m._midY)&&(m.plotX=e.toPixels(m._midX,!0),m.plotY=a.toPixels(m._midY,!0));f&&(m.shapeType="path",m.shapeArgs={d:b.translatePath(m.path)})});h(b,"afterTranslate")},pointAttribs:function(b,e){e=b.series.chart.styledMode?this.colorAttribs(b):f.column.prototype.pointAttribs.call(this,b,e);e["stroke-width"]=
k(b.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return e},drawPoints:function(){var b=this,e=b.xAxis,a=b.yAxis,c=b.group,g=b.chart,d=g.renderer,n=this.baseTrans;b.transformGroup||(b.transformGroup=d.g().attr({scaleX:1,scaleY:1}).add(c),b.transformGroup.survive=!0);if(b.doFullTranslate())g.hasRendered&&!g.styledMode&&b.points.forEach(function(e){e.shapeArgs&&(e.shapeArgs.fill=b.pointAttribs(e,e.state).fill)}),b.group=b.transformGroup,f.column.prototype.drawPoints.apply(b),
b.group=c,b.points.forEach(function(e){if(e.graphic){var a="";e.name&&(a+="highcharts-name-"+e.name.replace(/ /g,"-").toLowerCase());e.properties&&e.properties["hc-key"]&&(a+=" highcharts-key-"+e.properties["hc-key"].toLowerCase());a&&e.graphic.addClass(a);g.styledMode&&e.graphic.css(b.pointAttribs(e,e.selected&&"select"||void 0))}}),this.baseTrans={originX:e.min-e.minPixelPadding/e.transA,originY:a.min-a.minPixelPadding/a.transA+(a.reversed?0:a.len/a.transA),transAX:e.transA,transAY:a.transA},this.transformGroup.animate({translateX:0,
translateY:0,scaleX:1,scaleY:1});else{var q=e.transA/n.transAX;var h=a.transA/n.transAY;var v=e.toPixels(n.originX,!0);var l=a.toPixels(n.originY,!0);.99<q&&1.01>q&&.99<h&&1.01>h&&(h=q=1,v=Math.round(v),l=Math.round(l));var p=this.transformGroup;if(g.renderer.globalAnimation){var r=p.attr("translateX");var x=p.attr("translateY");var y=p.attr("scaleX");var t=p.attr("scaleY");p.attr({animator:0}).animate({animator:1},{step:function(b,e){p.attr({translateX:r+(v-r)*e.pos,translateY:x+(l-x)*e.pos,scaleX:y+
(q-y)*e.pos,scaleY:t+(h-t)*e.pos})}})}else p.attr({translateX:v,translateY:l,scaleX:q,scaleY:h})}g.styledMode||c.element.setAttribute("stroke-width",k(b.options[b.pointAttrToOptions&&b.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(q||1));this.drawMapDataLabels()},drawMapDataLabels:function(){q.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)},render:function(){var b=this,e=q.prototype.render;b.chart.renderer.isVML&&3E3<b.data.length?
setTimeout(function(){e.call(b)}):e.call(b)},animate:function(b){var e=this.options.animation,a=this.group,f=this.xAxis,c=this.yAxis,g=f.pos,k=c.pos;this.chart.renderer.isSVG&&(!0===e&&(e={duration:1E3}),b?a.attr({translateX:g+f.len/2,translateY:k+c.len/2,scaleX:.001,scaleY:.001}):a.animate({translateX:g,translateY:k,scaleX:1,scaleY:1},e))},animateDrilldown:function(b){var e=this.chart.plotBox,a=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],f=a.bBox,c=this.chart.options.drilldown.animation;
b||(b=Math.min(f.width/e.width,f.height/e.height),a.shapeArgs={scaleX:b,scaleY:b,translateX:f.x,translateY:f.y},this.points.forEach(function(b){b.graphic&&b.graphic.attr(a.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},c)}))},drawLegendSymbol:d.drawRectangle,animateDrillupFrom:function(b){f.column.prototype.animateDrillupFrom.call(this,b)},animateDrillupTo:function(b){f.column.prototype.animateDrillupTo.call(this,b)}}),p({applyOptions:function(b,e){var a=this.series;b=t.prototype.applyOptions.call(this,
b,e);e=a.joinBy;a.mapData&&a.mapMap&&(e=t.prototype.getNestedProperty.call(b,e[1]),(e="undefined"!==typeof e&&a.mapMap[e])?(a.xyFromShape&&(b.x=e._midX,b.y=e._midY),p(b,e)):b.value=b.value||null);return b},onMouseOver:function(b){l.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)t.prototype.onMouseOver.call(this,b);else this.series.onMouseOut(b)},zoomTo:function(){var b=this.series;b.xAxis.setExtremes(this._minX,this._maxX,!1);b.yAxis.setExtremes(this._minY,
this._maxY,!1);b.chart.redraw()}},y));""});w(d,"parts-map/MapLineSeries.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(c,d){d=d.seriesType;var r=c.seriesTypes;d("mapline","map",{lineWidth:1,fillColor:"none"},{type:"mapline",colorProp:"stroke",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(c,d){c=r.map.prototype.pointAttribs.call(this,c,d);c.fill=this.options.fillColor;return c},drawLegendSymbol:r.line.prototype.drawLegendSymbol});""});w(d,"parts-map/MapPointSeries.js",
[d["parts/Globals.js"]],function(c){var d=c.merge,t=c.Point,l=c.Series;c=c.seriesType;c("mappoint","scatter",{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:"#000000"}}},{type:"mappoint",forceDL:!0,drawDataLabels:function(){l.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)}},{applyOptions:function(c,h){c="undefined"!==typeof c.lat&&"undefined"!==typeof c.lon?d(c,this.series.chart.fromLatLonToPoint(c)):
c;return t.prototype.applyOptions.call(this,c,h)}});""});w(d,"parts-more/BubbleLegend.js",[d["parts/Globals.js"],d["parts/Color.js"],d["parts/Legend.js"],d["parts/Utilities.js"]],function(c,d,t,l){"";var p=d.parse;d=l.addEvent;var h=l.arrayMax,r=l.arrayMin,z=l.isNumber,u=l.merge,x=l.objectEach,a=l.pick,k=l.stableSort,g=l.wrap,n=c.Series,y=c.Chart,v=c.noop,q=c.setOptions;q({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,
connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});q=function(){function f(b,e){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=
this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=v;this.init(b,e)}f.prototype.init=function(b,e){this.options=b;this.visible=!0;this.chart=e.chart;this.legend=e};f.prototype.addToLegend=function(b){b.splice(this.options.legendIndex,0,this)};f.prototype.drawLegendSymbol=function(b){var e=this.chart,f=this.options,c=a(b.options.itemDistance,20),g=f.ranges;var d=f.connectorDistance;this.fontMetrics=e.renderer.fontMetrics(f.labels.style.fontSize.toString()+
"px");g&&g.length&&z(g[0].value)?(k(g,function(b,e){return e.value-b.value}),this.ranges=g,this.setOptions(),this.render(),e=this.getMaxLabelSize(),g=this.ranges[0].radius,b=2*g,d=d-g+e.width,d=0<d?d:0,this.maxLabel=e,this.movementX="left"===f.labels.align?d:0,this.legendItemWidth=b+d+c,this.legendItemHeight=b+this.fontMetrics.h/2):b.options.bubbleLegend.autoRanges=!0};f.prototype.setOptions=function(){var b=this.ranges,e=this.options,f=this.chart.series[e.seriesIndex],c=this.legend.baseline,g={"z-index":e.zIndex,
"stroke-width":e.borderWidth},d={"z-index":e.zIndex,"stroke-width":e.connectorWidth},k=this.getLabelStyles(),n=f.options.marker.fillOpacity,q=this.chart.styledMode;b.forEach(function(m,h){q||(g.stroke=a(m.borderColor,e.borderColor,f.color),g.fill=a(m.color,e.color,1!==n?p(f.color).setOpacity(n).get("rgba"):f.color),d.stroke=a(m.connectorColor,e.connectorColor,f.color));b[h].radius=this.getRangeRadius(m.value);b[h]=u(b[h],{center:b[0].radius-b[h].radius+c});q||u(!0,b[h],{bubbleStyle:u(!1,g),connectorStyle:u(!1,
d),labelStyle:k})},this)};f.prototype.getLabelStyles=function(){var b=this.options,e={},f="left"===b.labels.align,c=this.legend.options.rtl;x(b.labels.style,function(b,a){"color"!==a&&"fontSize"!==a&&"z-index"!==a&&(e[a]=b)});return u(!1,e,{"font-size":b.labels.style.fontSize,fill:a(b.labels.style.color,"#000000"),"z-index":b.zIndex,align:c||f?"right":"left"})};f.prototype.getRangeRadius=function(b){var e=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,e.ranges[e.ranges.length-
1].value,e.ranges[0].value,e.minSize,e.maxSize,b)};f.prototype.render=function(){var b=this.chart.renderer,e=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=b.g("bubble-legend");this.legendItem=b.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(b){b.value>=e&&this.renderRange(b)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};
f.prototype.renderRange=function(b){var e=this.options,a=e.labels,f=this.chart.renderer,c=this.symbols,g=c.labels,d=b.center,k=Math.abs(b.radius),n=e.connectorDistance,q=a.align,h=a.style.fontSize;n=this.legend.options.rtl||"left"===q?-n:n;a=e.connectorWidth;var v=this.ranges[0].radius,l=d-k-e.borderWidth/2+a/2;h=h/2-(this.fontMetrics.h-h)/2;var p=f.styledMode;"center"===q&&(n=0,e.connectorDistance=0,b.labelStyle.align="center");q=l+e.labels.y;var x=v+n+e.labels.x;c.bubbleItems.push(f.circle(v,d+
((l%1?1:.5)-(a%2?0:.5)),k).attr(p?{}:b.bubbleStyle).addClass((p?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(e.className||"")).add(this.legendSymbol));c.connectors.push(f.path(f.crispLine(["M",v,l,"L",v+n,l],e.connectorWidth)).attr(p?{}:b.connectorStyle).addClass((p?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(e.connectorClassName||"")).add(this.legendSymbol));b=f.text(this.formatLabel(b),x,q+h).attr(p?{}:
b.labelStyle).addClass("highcharts-bubble-legend-labels "+(e.labels.className||"")).add(this.legendSymbol);g.push(b);b.placed=!0;b.alignAttr={x:x,y:q+h}};f.prototype.getMaxLabelSize=function(){var b,e;this.symbols.labels.forEach(function(a){e=a.getBBox(!0);b=b?e.width>b.width?e:b:e});return b||{}};f.prototype.formatLabel=function(b){var e=this.options,a=e.labels.formatter;e=e.labels.format;var f=this.chart.numberFormatter;return e?l.format(e,b):a?a.call(b):f(b.value,1)};f.prototype.hideOverlappingLabels=
function(){var b=this.chart,e=this.symbols;!this.options.labels.allowOverlap&&e&&(b.hideOverlappingLabels(e.labels),e.labels.forEach(function(b,a){b.newOpacity?b.newOpacity!==b.oldOpacity&&e.connectors[a].show():e.connectors[a].hide()}))};f.prototype.getRanges=function(){var b=this.legend.bubbleLegend,e=b.options.ranges,f,c=Number.MAX_VALUE,g=-Number.MAX_VALUE;b.chart.series.forEach(function(b){b.isBubble&&!b.ignoreSeries&&(f=b.zData.filter(z),f.length&&(c=a(b.options.zMin,Math.min(c,Math.max(r(f),
!1===b.options.displayNegative?b.options.zThreshold:-Number.MAX_VALUE))),g=a(b.options.zMax,Math.max(g,h(f)))))});var d=c===g?[{value:g}]:[{value:c},{value:(c+g)/2},{value:g,autoRanges:!0}];e.length&&e[0].radius&&d.reverse();d.forEach(function(b,a){e&&e[a]&&(d[a]=u(!1,e[a],b))});return d};f.prototype.predictBubbleSizes=function(){var b=this.chart,e=this.fontMetrics,a=b.legend.options,f="horizontal"===a.layout,c=f?b.legend.lastLineHeight:0,g=b.plotSizeX,d=b.plotSizeY,k=b.series[this.options.seriesIndex];
b=Math.ceil(k.minPxSize);var n=Math.ceil(k.maxPxSize);k=k.options.maxSize;var q=Math.min(d,g);if(a.floating||!/%$/.test(k))e=n;else if(k=parseFloat(k),e=(q+c-e.h/2)*k/100/(k/100+1),f&&d-e>=g||!f&&g-e>=d)e=n;return[b,Math.ceil(e)]};f.prototype.updateRanges=function(b,e){var a=this.legend.options.bubbleLegend;a.minSize=b;a.maxSize=e;a.ranges=this.getRanges()};f.prototype.correctSizes=function(){var b=this.legend,e=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(e.maxPxSize)-this.options.maxSize)&&
(this.updateRanges(this.options.minSize,e.maxPxSize),b.render())};return f}();d(t,"afterGetAllItems",function(a){var b=this.bubbleLegend,e=this.options,f=e.bubbleLegend,g=this.chart.getVisibleBubbleSeriesIndex();b&&b.ranges&&b.ranges.length&&(f.ranges.length&&(f.autoRanges=!!f.ranges[0].autoRanges),this.destroyItem(b));0<=g&&e.enabled&&f.enabled&&(f.seriesIndex=g,this.bubbleLegend=new c.BubbleLegend(f,this),this.bubbleLegend.addToLegend(a.allItems))});y.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=
this.series,b=0;b<a.length;){if(a[b]&&a[b].isBubble&&a[b].visible&&a[b].zData.length)return b;b++}return-1};t.prototype.getLinesHeights=function(){var a=this.allItems,b=[],e=a.length,c,g=0;for(c=0;c<e;c++)if(a[c].legendItemHeight&&(a[c].itemHeight=a[c].legendItemHeight),a[c]===a[e-1]||a[c+1]&&a[c]._legendItemPos[1]!==a[c+1]._legendItemPos[1]){b.push({height:0});var d=b[b.length-1];for(g;g<=c;g++)a[g].itemHeight>d.height&&(d.height=a[g].itemHeight);d.step=c}return b};t.prototype.retranslateItems=function(a){var b,
e,f,c=this.options.rtl,g=0;this.allItems.forEach(function(d,k){b=d.legendGroup.translateX;e=d._legendItemPos[1];if((f=d.movementX)||c&&d.ranges)f=c?b-d.options.maxSize/2:b+f,d.legendGroup.attr({translateX:f});k>a[g].step&&g++;d.legendGroup.attr({translateY:Math.round(e+a[g].height/2)});d._legendItemPos[1]=e+a[g].height/2})};d(n,"legendItemClick",function(){var a=this.chart,b=this.visible,e=this.chart.legend;e&&e.bubbleLegend&&(this.visible=!b,this.ignoreSeries=b,a=0<=a.getVisibleBubbleSeriesIndex(),
e.bubbleLegend.visible!==a&&(e.update({bubbleLegend:{enabled:a}}),e.bubbleLegend.visible=a),this.visible=b)});g(y.prototype,"drawChartBox",function(a,b,e){var f=this.legend,c=0<=this.getVisibleBubbleSeriesIndex();if(f&&f.options.enabled&&f.bubbleLegend&&f.options.bubbleLegend.autoRanges&&c){var g=f.bubbleLegend.options;c=f.bubbleLegend.predictBubbleSizes();f.bubbleLegend.updateRanges(c[0],c[1]);g.placed||(f.group.placed=!1,f.allItems.forEach(function(b){b.legendGroup.translateY=null}));f.render();
this.getMargins();this.axes.forEach(function(b){b.visible&&b.render();g.placed||(b.setScale(),b.updateNames(),x(b.ticks,function(b){b.isNew=!0;b.isNewLabel=!0}))});g.placed=!0;this.getMargins();a.call(this,b,e);f.bubbleLegend.correctSizes();f.retranslateItems(f.getLinesHeights())}else a.call(this,b,e),f&&f.options.enabled&&f.bubbleLegend&&(f.render(),f.retranslateItems(f.getLinesHeights()))});c.BubbleLegend=q;return c.BubbleLegend});w(d,"parts-more/BubbleSeries.js",[d["parts/Globals.js"],d["parts/Color.js"],
d["parts/Point.js"],d["parts/Utilities.js"]],function(c,d,t,l){var p=d.parse,h=l.arrayMax,r=l.arrayMin,z=l.clamp,u=l.extend,x=l.isNumber,a=l.pick,k=l.pInt;d=l.seriesType;l=c.Axis;var g=c.noop,n=c.Series,y=c.seriesTypes;d("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},
tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(a,c){var f=this.options.marker.fillOpacity;a=n.prototype.pointAttribs.call(this,a,c);1!==f&&(a.fill=p(a.fill).setOpacity(f).get("rgba"));return a},getRadii:function(a,c,f){var b=this.zData,e=this.yData,
g=f.minPxSize,d=f.maxPxSize,k=[];var n=0;for(f=b.length;n<f;n++){var q=b[n];k.push(this.getRadius(a,c,g,d,q,e[n]))}this.radii=k},getRadius:function(a,c,f,b,e,g){var d=this.options,k="width"!==d.sizeBy,n=d.zThreshold,q=c-a,h=.5;if(null===g||null===e)return null;if(x(e)){d.sizeByAbsoluteValue&&(e=Math.abs(e-n),q=Math.max(c-n,Math.abs(a-n)),a=0);if(e<a)return f/2-1;0<q&&(h=(e-a)/q)}k&&0<=h&&(h=Math.sqrt(h));return Math.ceil(f+h*(b-f))/2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&
this.points.forEach(function(a){var f=a.graphic;if(f&&f.width){var b={x:f.x,y:f.y,width:f.width,height:f.height};f.attr({x:a.plotX,y:a.plotY,width:1,height:1});f.animate(b,this.options.animation)}},this)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,c=this.data,f=this.radii;y.scatter.prototype.translate.call(this);for(a=c.length;a--;){var b=c[a];var e=f?f[a]:0;x(e)&&e>=this.minPxSize/2?(b.marker=u(b.marker,{radius:e,width:2*e,height:2*e}),b.dlBox={x:b.plotX-e,
y:b.plotY-e,width:2*e,height:2*e}):b.shapeArgs=b.plotY=b.dlBox=void 0}},alignDataLabel:y.column.prototype.alignDataLabel,buildKDTree:g,applyZones:g},{haloPath:function(a){return t.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});l.prototype.beforePadding=function(){var c=this,g=this.len,f=this.chart,b=0,e=g,d=this.isXAxis,n=d?"xData":"yData",l=this.min,p={},y=Math.min(f.plotWidth,f.plotHeight),t=Number.MAX_VALUE,u=-Number.MAX_VALUE,w=this.max-l,C=g/w,E=[];
this.series.forEach(function(b){var e=b.options;!b.bubblePadding||!b.visible&&f.options.chart.ignoreHiddenSeries||(c.allowZoomOutside=!0,E.push(b),d&&(["minSize","maxSize"].forEach(function(b){var a=e[b],f=/%$/.test(a);a=k(a);p[b]=f?y*a/100:a}),b.minPxSize=p.minSize,b.maxPxSize=Math.max(p.maxSize,p.minSize),b=b.zData.filter(x),b.length&&(t=a(e.zMin,z(r(b),!1===e.displayNegative?e.zThreshold:-Number.MAX_VALUE,t)),u=a(e.zMax,Math.max(u,h(b))))))});E.forEach(function(a){var f=a[n],g=f.length;d&&a.getRadii(t,
u,a);if(0<w)for(;g--;)if(x(f[g])&&c.dataMin<=f[g]&&f[g]<=c.max){var k=a.radii?a.radii[g]:0;b=Math.min((f[g]-l)*C-k,b);e=Math.max((f[g]-l)*C+k,e)}});E.length&&0<w&&!this.isLog&&(e-=g,C*=(g+Math.max(0,b)-Math.min(e,g))/g,[["min","userMin",b],["max","userMax",e]].forEach(function(b){"undefined"===typeof a(c.options[b[0]],c[b[1]])&&(c[b[0]]+=b[2]/C)}))};""});w(d,"parts-map/MapBubbleSeries.js",[d["parts/Globals.js"],d["parts/Point.js"],d["parts/Utilities.js"]],function(c,d,t){var l=t.merge;t=t.seriesType;
var p=c.seriesTypes;p.bubble&&t("mapbubble","bubble",{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}},{xyFromShape:!0,type:"mapbubble",pointArrayMap:["z"],getMapData:p.map.prototype.getMapData,getBox:p.map.prototype.getBox,setData:p.map.prototype.setData,setOptions:p.map.prototype.setOptions},{applyOptions:function(c,r){return c&&"undefined"!==typeof c.lat&&"undefined"!==typeof c.lon?d.prototype.applyOptions.call(this,l(c,this.series.chart.fromLatLonToPoint(c)),r):p.map.prototype.pointClass.prototype.applyOptions.call(this,
c,r)},isValid:function(){return"number"===typeof this.z},ttBelow:!1});""});w(d,"parts-map/HeatmapSeries.js",[d["parts/Globals.js"],d["mixins/legend-symbol.js"],d["parts/Utilities.js"]],function(c,d,t){var l=t.clamp,p=t.extend,h=t.fireEvent,r=t.isNumber,w=t.merge,u=t.pick;t=t.seriesType;var x=c.colorMapPointMixin,a=c.Series,k=c.SVGRenderer.prototype.symbols;t("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",
crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}},w(c.colorMapSeriesMixin,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){a.prototype.init.apply(this,arguments);var c=this.options;c.pointRange=u(c.pointRange,c.colsize||1);this.yAxis.axisPointRange=
c.rowsize||1;p(k,{ellipse:k.circle,rect:k.square})},getSymbol:a.prototype.getSymbol,setClip:function(c){var g=this.chart;a.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||c)&&this.markerGroup.clip((c||this.clipBox)&&this.sharedClipKey?g[this.sharedClipKey]:g.clipRect)},translate:function(){var a=this.options,c=a.marker&&a.marker.symbol||"",d=k[c]?c:"rect";a=this.options;var l=-1!==["circle","square"].indexOf(d);this.generatePoints();this.points.forEach(function(a){var f=a.getCellAttributes(),
b={x:Math.min(f.x1,f.x2),y:Math.min(f.y1,f.y2),width:Math.max(Math.abs(f.x2-f.x1),0),height:Math.max(Math.abs(f.y2-f.y1),0)};var e=a.hasImage=0===(a.marker&&a.marker.symbol||c||"").indexOf("url");if(l){var g=Math.abs(b.width-b.height);b.x=Math.min(f.x1,f.x2)+(b.width<b.height?0:g/2);b.y=Math.min(f.y1,f.y2)+(b.width<b.height?g/2:0);b.width=b.height=Math.min(b.width,b.height)}g={plotX:(f.x1+f.x2)/2,plotY:(f.y1+f.y2)/2,clientX:(f.x1+f.x2)/2,shapeType:"path",shapeArgs:w(!0,b,{d:k[d](b.x,b.y,b.width,b.height)})};
e&&(a.marker={width:b.width,height:b.height});p(a,g)});h(this,"afterTranslate")},pointAttribs:function(g,d){var k=a.prototype.pointAttribs.call(this,g,d),n=this.options||{},h=this.chart.options.plotOptions||{},f=h.series||{},b=h.heatmap||{};h=n.borderColor||b.borderColor||f.borderColor;f=n.borderWidth||b.borderWidth||f.borderWidth||k["stroke-width"];k.stroke=g&&g.marker&&g.marker.lineColor||n.marker&&n.marker.lineColor||h||this.color;k["stroke-width"]=f;d&&(g=w(n.states[d],n.marker&&n.marker.states[d],
g.options.states&&g.options.states[d]||{}),d=g.brightness,k.fill=g.color||c.color(k.fill).brighten(d||0).get(),k.stroke=g.lineColor);return k},markerAttribs:function(a,c){var d=a.marker||{},g=this.options.marker||{},k=a.shapeArgs||{},f={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(c){var b=g.states[c]||{};var e=d.states&&d.states[c]||{};[["width","x"],["height","y"]].forEach(function(a){f[a[0]]=(e[a[0]]||b[a[0]]||k[a[0]])+(e[a[0]+"Plus"]||b[a[0]+"Plus"]||0);f[a[1]]=k[a[1]]+(k[a[0]]-f[a[0]])/2})}return c?
f:k},drawPoints:function(){var c=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)a.prototype.drawPoints.call(this),this.points.forEach(function(a){a.graphic&&a.graphic[c.chart.styledMode?"css":"animate"](c.colorAttribs(a))})},hasData:function(){return!!this.processedXData.length},getValidPoints:function(c,d){return a.prototype.getValidPoints.call(this,c,d,!0)},getBox:c.noop,drawLegendSymbol:d.drawRectangle,alignDataLabel:c.seriesTypes.column.prototype.alignDataLabel,getExtremes:function(){var c=
a.prototype.getExtremes.call(this,this.valueData),d=c.dataMin;c=c.dataMax;r(d)&&(this.valueMin=d);r(c)&&(this.valueMax=c);return a.prototype.getExtremes.call(this)}}),w(x,{applyOptions:function(a,d){a=c.Point.prototype.applyOptions.call(this,a,d);a.formatPrefix=a.isNull||null===a.value?"null":"point";return a},isValid:function(){return Infinity!==this.value&&-Infinity!==this.value},haloPath:function(a){if(!a)return[];var c=this.shapeArgs;return["M",c.x-a,c.y-a,"L",c.x-a,c.y+c.height+a,c.x+c.width+
a,c.y+c.height+a,c.x+c.width+a,c.y-a,"Z"]},getCellAttributes:function(){var a=this.series,c=a.options,d=(c.colsize||1)/2,k=(c.rowsize||1)/2,h=a.xAxis,f=a.yAxis,b=this.options.marker||a.options.marker;a=a.pointPlacementToXValue();var e=u(this.pointPadding,c.pointPadding,0),m={x1:l(Math.round(h.len-(h.translate(this.x-d,!1,!0,!1,!0,-a)||0)),-h.len,2*h.len),x2:l(Math.round(h.len-(h.translate(this.x+d,!1,!0,!1,!0,-a)||0)),-h.len,2*h.len),y1:l(Math.round(f.translate(this.y-k,!1,!0,!1,!0)||0),-f.len,2*
f.len),y2:l(Math.round(f.translate(this.y+k,!1,!0,!1,!0)||0),-f.len,2*f.len)};[["width","x"],["height","y"]].forEach(function(a){var c=a[0];a=a[1];var f=a+"1",d=a+"2",k=Math.abs(m[f]-m[d]),g=b&&b.lineWidth||0,h=Math.abs(m[f]+m[d])/2;b[c]&&b[c]<k&&(m[f]=h-b[c]/2-g/2,m[d]=h+b[c]/2+g/2);e&&("y"===a&&(f=d,d=a+"1"),m[f]+=e,m[d]-=e)});return m}}));""});w(d,"parts-map/GeoJSON.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(c,d){function r(c,a){var d,g=!1,h=c.x,l=c.y;c=0;for(d=a.length-1;c<a.length;d=
c++){var p=a[c][1]>l;var q=a[d][1]>l;p!==q&&h<(a[d][0]-a[c][0])*(l-a[c][1])/(a[d][1]-a[c][1])+a[c][0]&&(g=!g)}return g}var l=d.error,p=d.extend,h=d.format,w=d.merge;d=d.wrap;var z=c.Chart,u=c.win;z.prototype.transformFromLatLon=function(c,a){var d,g=(null===(d=this.userOptions.chart)||void 0===d?void 0:d.proj4)||u.proj4;if(!g)return l(21,!1,this),{x:0,y:null};c=g(a.crs,[c.lon,c.lat]);d=a.cosAngle||a.rotation&&Math.cos(a.rotation);g=a.sinAngle||a.rotation&&Math.sin(a.rotation);c=a.rotation?[c[0]*d+
c[1]*g,-c[0]*g+c[1]*d]:c;return{x:((c[0]-(a.xoffset||0))*(a.scale||1)+(a.xpan||0))*(a.jsonres||1)+(a.jsonmarginX||0),y:(((a.yoffset||0)-c[1])*(a.scale||1)+(a.ypan||0))*(a.jsonres||1)-(a.jsonmarginY||0)}};z.prototype.transformToLatLon=function(c,a){if("undefined"===typeof u.proj4)l(21,!1,this);else{c={x:((c.x-(a.jsonmarginX||0))/(a.jsonres||1)-(a.xpan||0))/(a.scale||1)+(a.xoffset||0),y:((-c.y-(a.jsonmarginY||0))/(a.jsonres||1)+(a.ypan||0))/(a.scale||1)+(a.yoffset||0)};var d=a.cosAngle||a.rotation&&
Math.cos(a.rotation),g=a.sinAngle||a.rotation&&Math.sin(a.rotation);a=u.proj4(a.crs,"WGS84",a.rotation?{x:c.x*d+c.y*-g,y:c.x*g+c.y*d}:c);return{lat:a.y,lon:a.x}}};z.prototype.fromPointToLatLon=function(c){var a=this.mapTransforms,d;if(a){for(d in a)if(Object.hasOwnProperty.call(a,d)&&a[d].hitZone&&r({x:c.x,y:-c.y},a[d].hitZone.coordinates[0]))return this.transformToLatLon(c,a[d]);return this.transformToLatLon(c,a["default"])}l(22,!1,this)};z.prototype.fromLatLonToPoint=function(c){var a=this.mapTransforms,
d;if(!a)return l(22,!1,this),{x:0,y:null};for(d in a)if(Object.hasOwnProperty.call(a,d)&&a[d].hitZone){var g=this.transformFromLatLon(c,a[d]);if(r({x:g.x,y:-g.y},a[d].hitZone.coordinates[0]))return g}return this.transformFromLatLon(c,a["default"])};c.geojson=function(c,a,d){var g=[],k=[],l=function(a){var c,d=a.length;k.push("M");for(c=0;c<d;c++)1===c&&k.push("L"),k.push(a[c][0],-a[c][1])};a=a||"map";c.features.forEach(function(c){var d=c.geometry,f=d.type;d=d.coordinates;c=c.properties;var b;k=[];
"map"===a||"mapbubble"===a?("Polygon"===f?(d.forEach(l),k.push("Z")):"MultiPolygon"===f&&(d.forEach(function(a){a.forEach(l)}),k.push("Z")),k.length&&(b={path:k})):"mapline"===a?("LineString"===f?l(d):"MultiLineString"===f&&d.forEach(l),k.length&&(b={path:k})):"mappoint"===a&&"Point"===f&&(b={x:d[0],y:-d[1]});b&&g.push(p(b,{name:c.name||c.NAME,properties:c}))});d&&c.copyrightShort&&(d.chart.mapCredits=h(d.chart.options.credits.mapText,{geojson:c}),d.chart.mapCreditsFull=h(d.chart.options.credits.mapTextFull,
{geojson:c}));return g};d(z.prototype,"addCredits",function(c,a){a=w(!0,this.options.credits,a);this.mapCredits&&(a.href=null);c.call(this,a);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});w(d,"parts-map/Map.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(c,d){function r(a,c,d,h,l,p,q,f){return["M",a+l,c,"L",a+d-p,c,"C",a+d-p/2,c,a+d,c+p/2,a+d,c+p,"L",a+d,c+h-q,"C",a+d,c+h-q/2,a+d-q/2,c+h,a+d-q,c+h,"L",a+f,c+h,"C",a+f/2,c+h,a,c+h-f/2,a,c+h-f,"L",
a,c+l,"C",a,c+l/2,a+l/2,c,a+l,c,"Z"]}var l=d.extend,p=d.merge,h=d.pick,w=c.Chart;d=c.defaultOptions;var z=c.Renderer,u=c.SVGRenderer,x=c.VMLRenderer;l(d.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});d.mapNavigation={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},
text:"-",y:28}},mouseWheelSensitivity:1.1};c.splitPath=function(a){var c;a=a.replace(/([A-Za-z])/g," $1 ");a=a.replace(/^\s*/,"").replace(/\s*$/,"");a=a.split(/[ ,]+/);for(c=0;c<a.length;c++)/[a-zA-Z]/.test(a[c])||(a[c]=parseFloat(a[c]));return a};c.maps={};u.prototype.symbols.topbutton=function(a,c,d,h,l){return r(a-1,c-1,d,h,l.r,l.r,0,0)};u.prototype.symbols.bottombutton=function(a,c,d,h,l){return r(a-1,c-1,d,h,0,0,l.r,l.r)};z===x&&["topbutton","bottombutton"].forEach(function(a){x.prototype.symbols[a]=
u.prototype.symbols[a]});c.Map=c.mapChart=function(a,d,g){var k="string"===typeof a||a.nodeName,l=arguments[k?1:0],r=l,q={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,startOnTick:!1},f=c.getOptions().credits;var b=l.series;l.series=null;l=p({chart:{panning:"xy",type:"map"},credits:{mapText:h(f.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:h(f.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:q,yAxis:p(q,{reversed:!0})},l,{chart:{inverted:!1,
alignTicks:!1}});l.series=r.series=b;return k?new w(a,l,g):new w(l,d)}});w(d,"masters/modules/map.src.js",[],function(){})});
//# sourceMappingURL=map.js.map