/*
 Highstock JS v8.0.4 (2020-03-26)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(p){"object"===typeof module&&module.exports?(p["default"]=p,module.exports=p):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(G){p(G);p.Highcharts=G;return p}):p("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(p){function G(u,m,p,e){u.hasOwnProperty(m)||(u[m]=e.apply(null,p))}p=p?p._modules:{};G(p,"parts/ScrollbarAxis.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(u,m){var p=m.addEvent,e=m.defined,A=m.pick;return function(){function m(){}
m.compose=function(m,t){p(m,"afterInit",function(){var g=this;g.options&&g.options.scrollbar&&g.options.scrollbar.enabled&&(g.options.scrollbar.vertical=!g.horiz,g.options.startOnTick=g.options.endOnTick=!1,g.scrollbar=new t(g.chart.renderer,g.options.scrollbar,g.chart),p(g.scrollbar,"changed",function(m){var t=Math.min(A(g.options.min,g.min),g.min,g.dataMin),B=Math.max(A(g.options.max,g.max),g.max,g.dataMax)-t;if(g.horiz&&!g.reversed||!g.horiz&&g.reversed){var z=t+B*this.to;t+=B*this.from}else z=
t+B*(1-this.from),t+=B*(1-this.to);A(this.options.liveRedraw,u.svg&&!u.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===m.DOMType||!e(m.DOMType)?g.setExtremes(t,z,!0,"mousemove"!==m.DOMType,m):this.setRange(this.from,this.to)}))});p(m,"afterRender",function(){var g=Math.min(A(this.options.min,this.min),this.min,A(this.dataMin,this.min)),m=Math.max(A(this.options.max,this.max),this.max,A(this.dataMax,this.max)),t=this.scrollbar,B=this.axisTitleMargin+(this.titleOffset||0),z=this.chart.scrollbarsOffsets,
C=this.options.margin||0;t&&(this.horiz?(this.opposite||(z[1]+=B),t.position(this.left,this.top+this.height+2+z[1]-(this.opposite?C:0),this.width,this.height),this.opposite||(z[1]+=C),B=1):(this.opposite&&(z[0]+=B),t.position(this.left+this.width+2+z[0]-(this.opposite?0:C),this.top,this.width,this.height),this.opposite&&(z[0]+=C),B=0),z[B]+=t.size+t.options.margin,isNaN(g)||isNaN(m)||!e(this.min)||!e(this.max)||this.min===this.max?t.setRange(0,1):(z=(this.min-g)/(m-g),g=(this.max-g)/(m-g),this.horiz&&
!this.reversed||!this.horiz&&this.reversed?t.setRange(z,g):t.setRange(1-g,1-z)))});p(m,"afterGetOffset",function(){var g=this.horiz?2:1,e=this.scrollbar;e&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[g]+=e.size+e.options.margin)})};return m}()});G(p,"parts/Scrollbar.js",[p["parts/Axis.js"],p["parts/Globals.js"],p["parts/ScrollbarAxis.js"],p["parts/Utilities.js"]],function(p,m,J,e){var A=e.addEvent,u=e.correctFloat,D=e.defined,t=e.destroyObjectProperties,g=e.fireEvent,E=e.merge,F=e.pick,
B=e.removeEvent;e=m.defaultOptions;var z=m.hasTouch,C=m.isTouchDevice,w=m.swapXY=function(d,b){var q=d.length;if(b)for(b=0;b<q;b+=3){var a=d[b+1];d[b+1]=d[b+2];d[b+2]=a}return d},l=function(){function d(b,q,a){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=
1;this.userOptions={};this.y=this.x=0;this.chart=a;this.options=q;this.renderer=a.renderer;this.init(b,q,a)}d.prototype.addEvents=function(){var b=this.options.inverted?[1,0]:[0,1],q=this.scrollbarButtons,a=this.scrollbarGroup.element,k=this.track.element,h=this.mouseDownHandler.bind(this),n=this.mouseMoveHandler.bind(this),d=this.mouseUpHandler.bind(this);b=[[q[b[0]].element,"click",this.buttonToMinClick.bind(this)],[q[b[1]].element,"click",this.buttonToMaxClick.bind(this)],[k,"click",this.trackClick.bind(this)],
[a,"mousedown",h],[a.ownerDocument,"mousemove",n],[a.ownerDocument,"mouseup",d]];z&&b.push([a,"touchstart",h],[a.ownerDocument,"touchmove",n],[a.ownerDocument,"touchend",d]);b.forEach(function(a){A.apply(null,a)});this._events=b};d.prototype.buttonToMaxClick=function(b){var q=(this.to-this.from)*F(this.options.step,.2);this.updatePosition(this.from+q,this.to+q);g(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};d.prototype.buttonToMinClick=function(b){var q=u(this.to-this.from)*
F(this.options.step,.2);this.updatePosition(u(this.from-q),u(this.to-q));g(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};d.prototype.cursorToScrollbarPosition=function(b){var q=this.options;q=q.minWidth>this.calculatedWidth?q.minWidth:0;return{chartX:(b.chartX-this.x-this.xOffset)/(this.barWidth-q),chartY:(b.chartY-this.y-this.yOffset)/(this.barWidth-q)}};d.prototype.destroy=function(){var b=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar",
"scrollbarGroup","group"].forEach(function(b){this[b]&&this[b].destroy&&(this[b]=this[b].destroy())},this);b&&this===b.scrollbar&&(b.scrollbar=null,t(b.scrollbarButtons))};d.prototype.drawScrollbarButton=function(b){var d=this.renderer,a=this.scrollbarButtons,k=this.options,h=this.size;var n=d.g().add(this.group);a.push(n);n=d.rect().addClass("highcharts-scrollbar-button").add(n);this.chart.styledMode||n.attr({stroke:k.buttonBorderColor,"stroke-width":k.buttonBorderWidth,fill:k.buttonBackgroundColor});
n.attr(n.crisp({x:-.5,y:-.5,width:h+1,height:h+1,r:k.buttonBorderRadius},n.strokeWidth()));n=d.path(w(["M",h/2+(b?-1:1),h/2-3,"L",h/2+(b?-1:1),h/2+3,"L",h/2+(b?2:-2),h/2],k.vertical)).addClass("highcharts-scrollbar-arrow").add(a[b]);this.chart.styledMode||n.attr({fill:k.buttonArrowColor})};d.prototype.init=function(b,q,a){this.scrollbarButtons=[];this.renderer=b;this.userOptions=q;this.options=E(d.defaultOptions,q);this.chart=a;this.size=F(this.options.size,this.options.height);q.enabled&&(this.render(),
this.addEvents())};d.prototype.mouseDownHandler=function(b){b=this.chart.pointer.normalize(b);b=this.cursorToScrollbarPosition(b);this.chartX=b.chartX;this.chartY=b.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};d.prototype.mouseMoveHandler=function(b){var d=this.chart.pointer.normalize(b),a=this.options.vertical?"chartY":"chartX",k=this.initPositions||[];!this.grabbedCenter||b.touches&&0===b.touches[0][a]||(d=this.cursorToScrollbarPosition(d)[a],a=this[a],a=d-a,this.hasDragged=
!0,this.updatePosition(k[0]+a,k[1]+a),this.hasDragged&&g(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b}))};d.prototype.mouseUpHandler=function(b){this.hasDragged&&g(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:b.type,DOMEvent:b});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};d.prototype.position=function(b,d,a,k){var h=this.options.vertical,n=0,q=this.rendered?"animate":"attr";this.x=b;this.y=d+this.trackBorderWidth;
this.width=a;this.xOffset=this.height=k;this.yOffset=n;h?(this.width=this.yOffset=a=n=this.size,this.xOffset=d=0,this.barWidth=k-2*a,this.x=b+=this.options.margin):(this.height=this.xOffset=k=d=this.size,this.barWidth=a-2*k,this.y+=this.options.margin);this.group[q]({translateX:b,translateY:this.y});this.track[q]({width:a,height:k});this.scrollbarButtons[1][q]({translateX:h?0:a-d,translateY:h?k-n:0})};d.prototype.removeEvents=function(){this._events.forEach(function(b){B.apply(null,b)});this._events.length=
0};d.prototype.render=function(){var b=this.renderer,d=this.options,a=this.size,k=this.chart.styledMode,h;this.group=h=b.g("scrollbar").attr({zIndex:d.zIndex,translateY:-99999}).add();this.track=b.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:d.trackBorderRadius||0,height:a,width:a}).add(h);k||this.track.attr({fill:d.trackBackgroundColor,stroke:d.trackBorderColor,"stroke-width":d.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%
2/2});this.scrollbarGroup=b.g().add(h);this.scrollbar=b.rect().addClass("highcharts-scrollbar-thumb").attr({height:a,width:a,r:d.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=b.path(w(["M",-3,a/4,"L",-3,2*a/3,"M",0,a/4,"L",0,2*a/3,"M",3,a/4,"L",3,2*a/3],d.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);k||(this.scrollbar.attr({fill:d.barBackgroundColor,stroke:d.barBorderColor,"stroke-width":d.barBorderWidth}),this.scrollbarRifles.attr({stroke:d.rifleColor,
"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};d.prototype.setRange=function(b,d){var a=this.options,k=a.vertical,h=a.minWidth,n=this.barWidth,y,q=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(D(n)){b=Math.max(b,0);var r=Math.ceil(n*b);this.calculatedWidth=y=u(n*
Math.min(d,1)-r);y<h&&(r=(n-h+y)*b,y=h);h=Math.floor(r+this.xOffset+this.yOffset);n=y/2-.5;this.from=b;this.to=d;k?(this.scrollbarGroup[q]({translateY:h}),this.scrollbar[q]({height:y}),this.scrollbarRifles[q]({translateY:n}),this.scrollbarTop=h,this.scrollbarLeft=0):(this.scrollbarGroup[q]({translateX:h}),this.scrollbar[q]({width:y}),this.scrollbarRifles[q]({translateX:n}),this.scrollbarLeft=h,this.scrollbarTop=0);12>=y?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===a.showFull&&(0>=
b&&1<=d?this.group.hide():this.group.show());this.rendered=!0}};d.prototype.trackClick=function(b){var d=this.chart.pointer.normalize(b),a=this.to-this.from,k=this.y+this.scrollbarTop,h=this.x+this.scrollbarLeft;this.options.vertical&&d.chartY>k||!this.options.vertical&&d.chartX>h?this.updatePosition(this.from+a,this.to+a):this.updatePosition(this.from-a,this.to-a);g(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};d.prototype.update=function(b){this.destroy();this.init(this.chart.renderer,
E(!0,this.options,b),this.chart)};d.prototype.updatePosition=function(b,d){1<d&&(b=u(1-u(d-b)),d=1);0>b&&(d=u(d-b),b=0);this.from=b;this.to=d};d.defaultOptions={height:C?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",
trackBorderColor:"#f2f2f2",trackBorderWidth:1};return d}();m.Scrollbar||(e.scrollbar=E(!0,l.defaultOptions,e.scrollbar),m.Scrollbar=l,J.compose(p,l));return m.Scrollbar});G(p,"parts/Navigator.js",[p["parts/Globals.js"],p["parts/Color.js"],p["parts/Scrollbar.js"],p["parts/Utilities.js"]],function(u,m,p,e){m=m.parse;var A=e.addEvent,H=e.clamp,D=e.correctFloat,t=e.defined,g=e.destroyObjectProperties,E=e.erase,F=e.extend,B=e.find,z=e.isArray,C=e.isNumber,w=e.merge,l=e.pick,d=e.removeEvent,b=e.splat,q=
u.Axis;e=u.Chart;var a=u.defaultOptions,k=u.hasTouch,h=u.isTouchDevice,n=u.Series,y=function(c){for(var f=[],v=1;v<arguments.length;v++)f[v-1]=arguments[v];f=[].filter.call(f,C);if(f.length)return Math[c].apply(0,f)};var M="undefined"===typeof u.seriesTypes.areaspline?"line":"areaspline";F(a,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:m("#6685c2").setOpacity(.3).get(),
outlineColor:"#cccccc",outlineWidth:1,series:{type:M,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},
threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});u.Renderer.prototype.symbols["navigator-handle"]=function(c,f,v,a,b){c=b.width/
2;f=Math.round(c/3)+.5;b=b.height;return["M",-c-1,.5,"L",c,.5,"L",c,b+.5,"L",-c-1,b+.5,"L",-c-1,.5,"M",-f,4,"L",-f,b-3,"M",f-1,4,"L",f-1,b-3]};q.prototype.toFixedRange=function(c,f,v,a){var x=this.chart&&this.chart.fixedRange,b=(this.pointRange||0)/2;c=l(v,this.translate(c,!0,!this.horiz));f=l(a,this.translate(f,!0,!this.horiz));var h=x&&(f-c)/x;t(v)||(c=D(c+b));t(a)||(f=D(f-b));.7<h&&1.3>h&&(a?c=f-x:f=c+x);C(c)&&C(f)||(c=f=void 0);return{min:c,max:f}};var r=function(){function c(f){this.zoomedMin=
this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(f)}c.prototype.drawHandle=function(f,v,c,a){var x=this.navigatorOptions.handles.height;this.handles[v][a](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+
parseInt(f,10)+.5-x)}:{translateX:Math.round(this.left+parseInt(f,10)),translateY:Math.round(this.top+this.height/2-x/2-1)})};c.prototype.drawOutline=function(f,v,c,a){var b=this.navigatorOptions.maskInside,x=this.outline.strokeWidth(),h=x/2;x=x%2/2;var d=this.outlineHeight,k=this.scrollbarHeight,r=this.size,I=this.left-k,n=this.top;c?(I-=h,c=n+v+x,v=n+f+x,f=["M",I+d,n-k-x,"L",I+d,c,"L",I,c,"L",I,v,"L",I+d,v,"L",I+d,n+r+k].concat(b?["M",I+d,c-h,"L",I+d,v+h]:[])):(f+=I+k-x,v+=I+k-x,n+=h,f=["M",I,n,
"L",f,n,"L",f,n+d,"L",v,n+d,"L",v,n,"L",I+r+2*k,n].concat(b?["M",f-h,n,"L",v+h,n]:[]));this.outline[a]({d:f})};c.prototype.drawMasks=function(f,v,c,a){var x=this.left,b=this.top,h=this.height;if(c){var d=[x,x,x];var k=[b,b+f,b+v];var I=[h,h,h];var n=[f,v-f,this.size-v]}else d=[x,x+f,x+v],k=[b,b,b],I=[f,v-f,this.size-v],n=[h,h,h];this.shades.forEach(function(f,v){f[a]({x:d[v],y:k[v],width:I[v],height:n[v]})})};c.prototype.renderElements=function(){var f=this,v=f.navigatorOptions,c=v.maskInside,a=f.chart,
b=a.renderer,h,d={cursor:a.inverted?"ns-resize":"ew-resize"};f.navigatorGroup=h=b.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,x){f.shades[x]=b.rect().addClass("highcharts-navigator-mask"+(1===x?"-inside":"-outside")).add(h);a.styledMode||f.shades[x].attr({fill:c?v.maskFill:"rgba(0,0,0,0)"}).css(1===x&&d)});f.outline=b.path().addClass("highcharts-navigator-outline").add(h);a.styledMode||f.outline.attr({"stroke-width":v.outlineWidth,stroke:v.outlineColor});
v.handles.enabled&&[0,1].forEach(function(c){v.handles.inverted=a.inverted;f.handles[c]=b.symbol(v.handles.symbols[c],-v.handles.width/2-1,0,v.handles.width,v.handles.height,v.handles);f.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(h);if(!a.styledMode){var x=v.handles;f.handles[c].attr({fill:x.backgroundColor,stroke:x.borderColor,"stroke-width":x.lineWidth}).css(d)}})};c.prototype.update=function(f){(this.series||[]).forEach(function(f){f.baseSeries&&
delete f.baseSeries.navigatorSeries});this.destroy();w(!0,this.chart.options.navigator,this.options,f);this.init(this.chart)};c.prototype.render=function(f,v,c,a){var b=this.chart,x=this.scrollbarHeight,h,d=this.xAxis,k=d.pointRange||0;var n=d.fake?b.xAxis[0]:d;var r=this.navigatorEnabled,I,y=this.rendered;var q=b.inverted;var z=b.xAxis[0].minRange,g=b.xAxis[0].options.maxRange;if(!this.hasDragged||t(c)){f=D(f-k/2);v=D(v+k/2);if(!C(f)||!C(v))if(y)c=0,a=l(d.width,n.width);else return;this.left=l(d.left,
b.plotLeft+x+(q?b.plotWidth:0));this.size=I=h=l(d.len,(q?b.plotHeight:b.plotWidth)-2*x);b=q?x:h+2*x;c=l(c,d.toPixels(f,!0));a=l(a,d.toPixels(v,!0));C(c)&&Infinity!==Math.abs(c)||(c=0,a=b);f=d.toValue(c,!0);v=d.toValue(a,!0);var e=Math.abs(D(v-f));e<z?this.grabbedLeft?c=d.toPixels(v-z-k,!0):this.grabbedRight&&(a=d.toPixels(f+z+k,!0)):t(g)&&D(e-k)>g&&(this.grabbedLeft?c=d.toPixels(v-g-k,!0):this.grabbedRight&&(a=d.toPixels(f+g+k,!0)));this.zoomedMax=H(Math.max(c,a),0,I);this.zoomedMin=H(this.fixedWidth?
this.zoomedMax-this.fixedWidth:Math.min(c,a),0,I);this.range=this.zoomedMax-this.zoomedMin;I=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);r&&(this.navigatorGroup.attr({visibility:"visible"}),y=y&&!this.hasDragged?"animate":"attr",this.drawMasks(c,I,q,y),this.drawOutline(c,I,q,y),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,q,y),this.drawHandle(I,1,q,y)));this.scrollbar&&(q?(q=this.top-x,n=this.left-x+(r||!n.opposite?0:(n.titleOffset||0)+n.axisTitleMargin),x=h+2*x):(q=this.top+
(r?this.height:-x),n=this.left-x),this.scrollbar.position(n,q,b,x),this.scrollbar.setRange(this.zoomedMin/(h||1),this.zoomedMax/(h||1)));this.rendered=!0}};c.prototype.addMouseEvents=function(){var f=this,v=f.chart,c=v.container,a=[],b,h;f.mouseMoveHandler=b=function(c){f.onMouseMove(c)};f.mouseUpHandler=h=function(c){f.onMouseUp(c)};a=f.getPartsEvents("mousedown");a.push(A(v.renderTo,"mousemove",b),A(c.ownerDocument,"mouseup",h));k&&(a.push(A(v.renderTo,"touchmove",b),A(c.ownerDocument,"touchend",
h)),a.concat(f.getPartsEvents("touchstart")));f.eventsToUnbind=a;f.series&&f.series[0]&&a.push(A(f.series[0].xAxis,"foundExtremes",function(){v.navigator.modifyNavigatorAxisExtremes()}))};c.prototype.getPartsEvents=function(f){var c=this,a=[];["shades","handles"].forEach(function(v){c[v].forEach(function(b,x){a.push(A(b.element,f,function(f){c[v+"Mousedown"](f,x)}))})});return a};c.prototype.shadesMousedown=function(f,c){f=this.chart.pointer.normalize(f);var v=this.chart,a=this.xAxis,b=this.zoomedMin,
h=this.left,d=this.size,k=this.range,n=f.chartX;v.inverted&&(n=f.chartY,h=this.top);if(1===c)this.grabbedCenter=n,this.fixedWidth=k,this.dragOffset=n-b;else{f=n-h-k/2;if(0===c)f=Math.max(0,f);else if(2===c&&f+k>=d)if(f=d-k,this.reversedExtremes){f-=k;var r=this.getUnionExtremes().dataMin}else var y=this.getUnionExtremes().dataMax;f!==b&&(this.fixedWidth=k,c=a.toFixedRange(f,f+k,r,y),t(c.min)&&v.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,null,{trigger:"navigator"}))}};c.prototype.handlesMousedown=
function(f,c){this.chart.pointer.normalize(f);f=this.chart;var v=f.xAxis[0],a=this.reversedExtremes;0===c?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=a?v.min:v.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=a?v.max:v.min);f.fixedRange=null};c.prototype.onMouseMove=function(f){var c=this,a=c.chart,b=c.left,d=c.navigatorSize,k=c.range,n=c.dragOffset,r=a.inverted;f.touches&&0===f.touches[0].pageX||(f=a.pointer.normalize(f),a=f.chartX,r&&
(b=c.top,a=f.chartY),c.grabbedLeft?(c.hasDragged=!0,c.render(0,0,a-b,c.otherHandlePos)):c.grabbedRight?(c.hasDragged=!0,c.render(0,0,c.otherHandlePos,a-b)):c.grabbedCenter&&(c.hasDragged=!0,a<n?a=n:a>d+n-k&&(a=d+n-k),c.render(0,0,a-n,a-n+k)),c.hasDragged&&c.scrollbar&&l(c.scrollbar.options.liveRedraw,u.svg&&!h&&!this.chart.isBoosting)&&(f.DOMType=f.type,setTimeout(function(){c.onMouseUp(f)},0)))};c.prototype.onMouseUp=function(f){var c=this.chart,a=this.xAxis,b=this.scrollbar,h=f.DOMEvent||f,d=c.inverted,
k=this.rendered&&!this.hasDragged?"animate":"attr",n=Math.round(this.zoomedMax),r=Math.round(this.zoomedMin);if(this.hasDragged&&(!b||!b.hasDragged)||"scrollbar"===f.trigger){b=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var y=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var q=this.fixedExtreme;this.zoomedMax===this.size&&(q=this.reversedExtremes?b.dataMin:b.dataMax);0===this.zoomedMin&&(y=this.reversedExtremes?b.dataMax:b.dataMin);a=a.toFixedRange(this.zoomedMin,
this.zoomedMax,y,q);t(a.min)&&c.xAxis[0].setExtremes(Math.min(a.min,a.max),Math.max(a.min,a.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:h})}"mousemove"!==f.DOMType&&"touchmove"!==f.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&this.drawMasks(r,n,d,k),this.outline&&this.drawOutline(r,n,d,k),this.navigatorOptions.handles.enabled&&
Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(r,0,d,k),this.drawHandle(n,1,d,k)))};c.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(f){f()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};c.prototype.removeBaseSeriesEvents=function(){var f=this.baseSeries||[];this.navigatorEnabled&&f[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&f.forEach(function(f){d(f,"updatedData",this.updatedDataHandler)},this),f[0].xAxis&&
d(f[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};c.prototype.init=function(f){var c=f.options,a=c.navigator,b=a.enabled,h=c.scrollbar,d=h.enabled;c=b?a.height:0;var k=d?h.height:0;this.handles=[];this.shades=[];this.chart=f;this.setBaseSeries();this.height=c;this.scrollbarHeight=k;this.scrollbarEnabled=d;this.navigatorEnabled=b;this.navigatorOptions=a;this.scrollbarOptions=h;this.outlineHeight=c+k;this.opposite=l(a.opposite,!(b||!f.inverted));var n=this;b=n.baseSeries;h=f.xAxis.length;
d=f.yAxis.length;var r=b&&b[0]&&b[0].xAxis||f.xAxis[0]||{options:{}};f.isDirtyBox=!0;n.navigatorEnabled?(n.xAxis=new q(f,w({breaks:r.options.breaks,ordinal:r.options.ordinal},a.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:h,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},f.inverted?{offsets:[k,0,-k,0],width:c}:{offsets:[0,-k,0,k],height:c})),n.yAxis=new q(f,w(a.yAxis,{id:"navigator-y-axis",alignTicks:!1,
offset:0,index:d,isInternal:!0,zoomEnabled:!1},f.inverted?{width:c}:{height:c})),b||a.series.data?n.updateNavigatorSeries(!1):0===f.series.length&&(n.unbindRedraw=A(f,"beforeRedraw",function(){0<f.series.length&&!n.series&&(n.setBaseSeries(),n.unbindRedraw())})),n.reversedExtremes=f.inverted&&!n.xAxis.reversed||!f.inverted&&n.xAxis.reversed,n.renderElements(),n.addMouseEvents()):n.xAxis={translate:function(c,a){var b=f.xAxis[0],v=b.getExtremes(),h=b.len-2*k,d=y("min",b.options.min,v.dataMin);b=y("max",
b.options.max,v.dataMax)-d;return a?c*b/h+d:h*(c-d)/b},toPixels:function(f){return this.translate(f)},toValue:function(f){return this.translate(f,!0)},toFixedRange:q.prototype.toFixedRange,fake:!0};f.options.scrollbar.enabled&&(f.scrollbar=n.scrollbar=new p(f.renderer,w(f.options.scrollbar,{margin:n.navigatorEnabled?0:10,vertical:f.inverted}),f),A(n.scrollbar,"changed",function(c){var a=n.size,b=a*this.to;a*=this.from;n.hasDragged=n.scrollbar.hasDragged;n.render(0,0,a,b);(f.options.scrollbar.liveRedraw||
"mousemove"!==c.DOMType&&"touchmove"!==c.DOMType)&&setTimeout(function(){n.onMouseUp(c)})}));n.addBaseSeriesEvents();n.addChartEvents()};c.prototype.getUnionExtremes=function(f){var c=this.chart.xAxis[0],a=this.xAxis,b=a.options,h=c.options,d;f&&null===c.dataMin||(d={dataMin:l(b&&b.min,y("min",h.min,c.dataMin,a.dataMin,a.min)),dataMax:l(b&&b.max,y("max",h.max,c.dataMax,a.dataMax,a.max))});return d};c.prototype.setBaseSeries=function(f,c){var a=this.chart,b=this.baseSeries=[];f=f||a.options&&a.options.navigator.baseSeries||
(a.series.length?B(a.series,function(f){return!f.options.isInternal}).index:0);(a.series||[]).forEach(function(c,a){c.options.isInternal||!c.options.showInNavigator&&(a!==f&&c.options.id!==f||!1===c.options.showInNavigator)||b.push(c)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(!0,c)};c.prototype.updateNavigatorSeries=function(f,c){var v=this,h=v.chart,k=v.baseSeries,n,r,y=v.navigatorOptions.series,q,g={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",
yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,states:{inactive:{opacity:1}}},e=v.series=(v.series||[]).filter(function(f){var c=f.baseSeries;return 0>k.indexOf(c)?(c&&(d(c,"updatedData",v.updatedDataHandler),delete c.navigatorSeries),f.chart&&f.destroy(),!1):!0});k&&k.length&&k.forEach(function(f){var b=f.navigatorSeries,d=F({color:f.color,visible:f.visible},z(y)?a.navigator.series:y);b&&!1===v.navigatorOptions.adaptToUpdatedData||(g.name="Navigator "+k.length,n=f.options||{},
q=n.navigatorOptions||{},r=w(n,g,d,q),r.pointRange=l(d.pointRange,q.pointRange,a.plotOptions[r.type||"line"].pointRange),d=q.data||d.data,v.hasNavigatorData=v.hasNavigatorData||!!d,r.data=d||n.data&&n.data.slice(0),b&&b.options?b.update(r,c):(f.navigatorSeries=h.initSeries(r),f.navigatorSeries.baseSeries=f,e.push(f.navigatorSeries)))});if(y.data&&(!k||!k.length)||z(y))v.hasNavigatorData=!1,y=b(y),y.forEach(function(f,c){g.name="Navigator "+(e.length+1);r=w(a.navigator.series,{color:h.series[c]&&!h.series[c].options.isInternal&&
h.series[c].color||h.options.colors[c]||h.options.colors[0]},g,f);r.data=f.data;r.data&&(v.hasNavigatorData=!0,e.push(h.initSeries(r)))});f&&this.addBaseSeriesEvents()};c.prototype.addBaseSeriesEvents=function(){var f=this,c=f.baseSeries||[];c[0]&&c[0].xAxis&&A(c[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);c.forEach(function(c){A(c,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});A(c,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,
!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&c.xAxis&&A(c,"updatedData",this.updatedDataHandler);A(c,"remove",function(){this.navigatorSeries&&(E(f.series,this.navigatorSeries),t(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};c.prototype.getBaseSeriesMin=function(c){return this.baseSeries.reduce(function(c,f){return Math.min(c,f.xData?f.xData[0]:c)},c)};c.prototype.modifyNavigatorAxisExtremes=function(){var c=this.xAxis,a;"undefined"!==
typeof c.getExtremes&&(!(a=this.getUnionExtremes(!0))||a.dataMin===c.min&&a.dataMax===c.max||(c.min=a.dataMin,c.max=a.dataMax))};c.prototype.modifyBaseAxisExtremes=function(){var c=this.chart.navigator,a=this.getExtremes(),b=a.dataMin,h=a.dataMax;a=a.max-a.min;var d=c.stickToMin,k=c.stickToMax,n=l(this.options.overscroll,0),r=c.series&&c.series[0],y=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(d){var q=b;var g=q+a}k&&(g=h+n,d||(q=Math.max(g-a,c.getBaseSeriesMin(r&&
r.xData?r.xData[0]:-Number.MAX_VALUE))));y&&(d||k)&&C(q)&&(this.min=this.userMin=q,this.max=this.userMax=g)}c.stickToMin=c.stickToMax=null};c.prototype.updatedDataHandler=function(){var c=this.chart.navigator,a=this.navigatorSeries,b=c.getBaseSeriesMin(this.xData[0]);c.stickToMax=c.reversedExtremes?0===Math.round(c.zoomedMin):Math.round(c.zoomedMax)>=Math.round(c.size);c.stickToMin=C(this.xAxis.min)&&this.xAxis.min<=b&&(!this.chart.fixedRange||!c.stickToMax);a&&!c.hasNavigatorData&&(a.options.pointStart=
this.xData[0],a.setData(this.options.data,!1,null,!1))};c.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(A(this.chart,"redraw",function(){var c=this.navigator,a=c&&(c.baseSeries&&c.baseSeries[0]&&c.baseSeries[0].xAxis||this.xAxis[0]);a&&c.render(a.min,a.max)}),A(this.chart,"getMargins",function(){var c=this.navigator,a=c.opposite?"plotTop":"marginBottom";this.inverted&&(a=c.opposite?"marginRight":"plotLeft");this[a]=(this[a]||0)+(c.navigatorEnabled||
!this.inverted?c.outlineHeight:0)+c.navigatorOptions.margin}))};c.prototype.destroy=function(){this.removeEvents();this.xAxis&&(E(this.chart.xAxis,this.xAxis),E(this.chart.axes,this.xAxis));this.yAxis&&(E(this.chart.yAxis,this.yAxis),E(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(c){c.destroy&&c.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(c){this[c]&&this[c].destroy&&
this[c].destroy();this[c]=null},this);[this.handles].forEach(function(c){g(c)},this)};return c}();u.Navigator||(u.Navigator=r,A(q,"zoom",function(c){var f=this.chart.options,a=f.chart.zoomType,b=f.chart.pinchType,d=f.navigator;f=f.rangeSelector;this.isXAxis&&(d&&d.enabled||f&&f.enabled)&&("y"===a?c.zoomed=!1:(!h&&"xy"===a||h&&"xy"===b)&&this.options.range&&(a=this.previousZoom,t(c.newMin)?this.previousZoom=[this.min,this.max]:a&&(c.newMin=a[0],c.newMax=a[1],delete this.previousZoom)));"undefined"!==
typeof c.zoomed&&c.preventDefault()}),A(e,"beforeShowResetZoom",function(){var c=this.options,f=c.navigator,a=c.rangeSelector;if((f&&f.enabled||a&&a.enabled)&&(!h&&"x"===c.chart.zoomType||h&&"x"===c.chart.pinchType))return!1}),A(e,"beforeRender",function(){var c=this.options;if(c.navigator.enabled||c.scrollbar.enabled)this.scroller=this.navigator=new r(this)}),A(e,"afterSetChartSize",function(){var c=this.legend,a=this.navigator;if(a){var b=c&&c.options;var h=a.xAxis;var d=a.yAxis;var k=a.scrollbarHeight;
this.inverted?(a.left=a.opposite?this.chartWidth-k-a.height:this.spacing[3]+k,a.top=this.plotTop+k):(a.left=this.plotLeft+k,a.top=a.navigatorOptions.top||this.chartHeight-a.height-k-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(b&&"bottom"===b.verticalAlign&&b.enabled&&!b.floating?c.legendHeight+l(b.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));h&&d&&(this.inverted?h.options.left=d.options.left=a.left:h.options.top=d.options.top=a.top,h.setAxisSize(),
d.setAxisSize())}}),A(e,"update",function(c){var a=c.options.navigator||{},b=c.options.scrollbar||{};this.navigator||this.scroller||!a.enabled&&!b.enabled||(w(!0,this.options.navigator,a),w(!0,this.options.scrollbar,b),delete c.options.navigator,delete c.options.scrollbar)}),A(e,"afterUpdate",function(c){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new r(this),l(c.redraw,!0)&&this.redraw(c.animation))}),A(e,"afterAddSeries",
function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),A(n,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),e.prototype.callbacks.push(function(c){var a=c.navigator;a&&c.xAxis[0]&&(c=c.xAxis[0].getExtremes(),a.render(c.min,c.max))}));u.Navigator=r;return u.Navigator});G(p,"parts/OrdinalAxis.js",[p["parts/Axis.js"],p["parts/Globals.js"],p["parts/Utilities.js"]],function(u,m,p){var e=p.addEvent,A=p.css,H=p.defined,D=p.pick,
t=p.timeUnits;p=m.Chart;var g=m.Series,E=function(){function g(g){this.index={};this.axis=g}g.prototype.getExtendedPositions=function(){var g=this,e=g.axis,w=e.constructor.prototype,l=e.chart,d=e.series[0].currentDataGrouping,b=g.index,q=d?d.count+d.unitName:"raw",a=e.options.overscroll,k=e.getExtremes(),h;b||(b=g.index={});if(!b[q]){var n={series:[],chart:l,getExtremes:function(){return{min:k.dataMin,max:k.dataMax+a}},options:{ordinal:!0},ordinal:{},ordinal2lin:w.ordinal2lin,val2lin:w.val2lin};n.ordinal.axis=
n;e.series.forEach(function(a){h={xAxis:n,xData:a.xData.slice(),chart:l,destroyGroupedData:m.noop};h.xData=h.xData.concat(g.getOverscrollPositions());h.options={dataGrouping:d?{enabled:!0,forced:!0,approximation:"open",units:[[d.unitName,[d.count]]]}:{enabled:!1}};a.processData.apply(h);n.series.push(h)});e.beforeSetTickPositions.apply(n);b[q]=n.ordinal.positions}return b[q]};g.prototype.getGroupIntervalFactor=function(g,e,m){m=m.processedXData;var l=m.length,d=[];var b=this.groupIntervalFactor;if(!b){for(b=
0;b<l-1;b++)d[b]=m[b+1]-m[b];d.sort(function(b,a){return b-a});d=d[Math.floor(l/2)];g=Math.max(g,m[0]);e=Math.min(e,m[l-1]);this.groupIntervalFactor=b=l*d/(e-g)}return b};g.prototype.getOverscrollPositions=function(){var g=this.axis,e=g.options.overscroll,m=this.overscrollPointsRange,l=[],d=g.dataMax;if(H(m))for(l.push(d);d<=g.dataMax+e;)d+=m,l.push(d);return l};g.prototype.postProcessTickInterval=function(g){var e=this.axis,m=this.slope;return m?e.options.breaks?e.closestPointRange||g:g/(m/e.closestPointRange):
g};return g}(),F=function(){function g(){}g.compose=function(g,m,B){var l=g.prototype;l.beforeSetTickPositions=function(){var d=this.ordinal,b=[],q,a=!1,k=this.getExtremes(),h=k.min,n=k.max,y,g=this.isXAxis&&!!this.options.breaks;k=this.options.ordinal;var r=Number.MAX_VALUE,c=this.chart.options.chart.ignoreHiddenSeries,f;if(k||g){this.series.forEach(function(a,h){q=[];if(!(c&&!1===a.visible||!1===a.takeOrdinalPosition&&!g)&&(b=b.concat(a.processedXData),v=b.length,b.sort(function(c,a){return c-a}),
r=Math.min(r,D(a.closestPointRange,r)),v)){for(h=0;h<v-1;)b[h]!==b[h+1]&&q.push(b[h+1]),h++;q[0]!==b[0]&&q.unshift(b[0]);b=q}a.isSeriesBoosting&&(f=!0)});f&&(b.length=0);var v=b.length;if(2<v){var x=b[1]-b[0];for(y=v-1;y--&&!a;)b[y+1]-b[y]!==x&&(a=!0);!this.options.keepOrdinalPadding&&(b[0]-h>x||n-b[b.length-1]>x)&&(a=!0)}else this.options.overscroll&&(2===v?r=b[1]-b[0]:1===v?(r=this.options.overscroll,b=[b[0],b[0]+r]):r=d.overscrollPointsRange);a?(this.options.overscroll&&(d.overscrollPointsRange=
r,b=b.concat(d.getOverscrollPositions())),d.positions=b,x=this.ordinal2lin(Math.max(h,b[0]),!0),y=Math.max(this.ordinal2lin(Math.min(n,b[b.length-1]),!0),1),d.slope=n=(n-h)/(y-x),d.offset=h-x*n):(d.overscrollPointsRange=D(this.closestPointRange,d.overscrollPointsRange),d.positions=this.ordinal.slope=d.offset=void 0)}this.isOrdinal=k&&a;d.groupIntervalFactor=null};g.prototype.getTimeTicks=function(d,b,g,a,k,h,n){void 0===k&&(k=[]);void 0===h&&(h=0);var y=0,q,r,c={},f=[],v=-Number.MAX_VALUE,x=this.options.tickPixelInterval,
l=this.chart.time,e=[];if(!this.options.ordinal&&!this.options.breaks||!k||3>k.length||"undefined"===typeof b)return l.getTimeTicks.apply(l,arguments);var m=k.length;for(q=0;q<m;q++){var z=q&&k[q-1]>g;k[q]<b&&(y=q);if(q===m-1||k[q+1]-k[q]>5*h||z){if(k[q]>v){for(r=l.getTimeTicks(d,k[y],k[q],a);r.length&&r[0]<=v;)r.shift();r.length&&(v=r[r.length-1]);e.push(f.length);f=f.concat(r)}y=q+1}if(z)break}r=r.info;if(n&&r.unitRange<=t.hour){q=f.length-1;for(y=1;y<q;y++)if(l.dateFormat("%d",f[y])!==l.dateFormat("%d",
f[y-1])){c[f[y]]="day";var B=!0}B&&(c[f[0]]="day");r.higherRanks=c}r.segmentStarts=e;f.info=r;if(n&&H(x)){y=e=f.length;B=[];var w;for(l=[];y--;)q=this.translate(f[y]),w&&(l[y]=w-q),B[y]=w=q;l.sort();l=l[Math.floor(l.length/2)];l<.6*x&&(l=null);y=f[e-1]>g?e-1:e;for(w=void 0;y--;)q=B[y],e=Math.abs(w-q),w&&e<.8*x&&(null===l||e<.8*l)?(c[f[y]]&&!c[f[y+1]]?(e=y+1,w=q):e=y,f.splice(e,1)):w=q}return f};l.lin2val=function(d,b){var q=this.ordinal,a=q.positions;if(a){var k=q.slope,h=q.offset;q=a.length-1;if(b)if(0>
d)d=a[0];else if(d>q)d=a[q];else{q=Math.floor(d);var n=d-q}else for(;q--;)if(b=k*q+h,d>=b){k=k*(q+1)+h;n=(d-b)/(k-b);break}return"undefined"!==typeof n&&"undefined"!==typeof a[q]?a[q]+(n?n*(a[q+1]-a[q]):0):d}return d};l.val2lin=function(d,b){var q=this.ordinal,a=q.positions;if(a){var k=a.length,h;for(h=k;h--;)if(a[h]===d){var n=h;break}for(h=k-1;h--;)if(d>a[h]||0===h){d=(d-a[h])/(a[h+1]-a[h]);n=h+d;break}b=b?n:q.slope*(n||0)+q.offset}else b=d;return b};l.ordinal2lin=l.val2lin;e(g,"afterInit",function(){this.ordinal=
new E(this)});e(g,"foundExtremes",function(){this.isXAxis&&H(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=this.options.overscroll,!this.isInternal&&H(this.userMin)&&(this.min+=this.options.overscroll))});e(g,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&!this.chart.navigator.adaptToUpdatedData)});e(m,"pan",
function(d){var b=this.xAxis[0],q=b.options.overscroll,a=d.originalEvent.chartX,k=this.options.chart&&this.options.chart.panning,h=!1;if(k&&"y"!==k.type&&b.options.ordinal&&b.series.length){var n=this.mouseDownX,g=b.getExtremes(),l=g.dataMax,r=g.min,c=g.max,f=this.hoverPoints,v=b.closestPointRange||b.ordinal&&b.ordinal.overscrollPointsRange;n=(n-a)/(b.translationSlope*(b.ordinal.slope||v));var x={ordinal:{positions:b.ordinal.getExtendedPositions()}};v=b.lin2val;var e=b.val2lin;if(!x.ordinal.positions)h=
!0;else if(1<Math.abs(n)){f&&f.forEach(function(c){c.setState()});if(0>n){f=x;var m=b.ordinal.positions?b:x}else f=b.ordinal.positions?b:x,m=x;x=m.ordinal.positions;l>x[x.length-1]&&x.push(l);this.fixedRange=c-r;n=b.toFixedRange(null,null,v.apply(f,[e.apply(f,[r,!0])+n,!0]),v.apply(m,[e.apply(m,[c,!0])+n,!0]));n.min>=Math.min(g.dataMin,r)&&n.max<=Math.max(l,c)+q&&b.setExtremes(n.min,n.max,!0,!1,{trigger:"pan"});this.mouseDownX=a;A(this.container,{cursor:"move"})}}else h=!0;h||k&&/y/.test(k.type)?
q&&(b.max=b.dataMax+q):d.preventDefault()});e(B,"updatedData",function(){var d=this.xAxis;d&&d.options.ordinal&&delete d.ordinal.index})};return g}();F.compose(u,p,g);return F});G(p,"modules/broken-axis.src.js",[p["parts/Globals.js"],p["parts/Utilities.js"],p["parts/Stacking.js"]],function(p,m,J){var e=m.addEvent,A=m.extend,u=m.find,D=m.fireEvent,t=m.isArray,g=m.pick,E=p.Axis;m=p.Series;var F=function(g,e){return u(e,function(e){return e.from<g&&g<e.to})};A(E.prototype,{isInBreak:function(g,e){var m=
g.repeat||Infinity,t=g.from,l=g.to-g.from;e=e>=t?(e-t)%m:m-(t-e)%m;return g.inclusive?e<=l:e<l&&0!==e},isInAnyBreak:function(e,m){var t=this.options.breaks,w=t&&t.length,l;if(w){for(;w--;)if(this.isInBreak(t[w],e)){var d=!0;l||(l=g(t[w].showPoints,!this.isXAxis))}var b=d&&m?d&&!l:d}return b}});e(E,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});e(E,"afterSetTickPositions",function(){if(this.isBroken){var g=this.tickPositions,e=this.tickPositions.info,
m=[],t;for(t=0;t<g.length;t++)this.isInAnyBreak(g[t])||m.push(g[t]);this.tickPositions=m;this.tickPositions.info=e}});e(E,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});E.prototype.setBreaks=function(e,m){function z(b){var d=b,a;for(a=0;a<l.breakArray.length;a++){var k=l.breakArray[a];if(k.to<=b)d-=k.len;else if(k.from>=b)break;else if(l.isInBreak(k,b)){d-=b-k.from;break}}return d}function p(b){var d;for(d=0;d<l.breakArray.length;d++){var a=l.breakArray[d];if(a.from>=b)break;
else a.to<b?b+=a.len:l.isInBreak(a,b)&&(b+=a.len)}return b}var l=this,d=t(e)&&!!e.length;l.isDirty=l.isBroken!==d;l.isBroken=d;l.options.breaks=l.userOptions.breaks=e;l.forceRedraw=!0;l.series.forEach(function(b){b.isDirty=!0});d||l.val2lin!==z||(delete l.val2lin,delete l.lin2val);d&&(l.userOptions.ordinal=!1,l.val2lin=z,l.lin2val=p,l.setExtremes=function(b,d,a,k,h){if(this.isBroken){for(var n,g=this.options.breaks;n=F(b,g);)b=n.to;for(;n=F(d,g);)d=n.from;d<b&&(d=b)}E.prototype.setExtremes.call(this,
b,d,a,k,h)},l.setAxisTranslation=function(b){E.prototype.setAxisTranslation.call(this,b);this.unitLength=null;if(this.isBroken){b=l.options.breaks;var d=[],a=[],k=0,h,n=l.userMin||l.min,e=l.userMax||l.max,m=g(l.pointRangePadding,0),r;b.forEach(function(c){h=c.repeat||Infinity;l.isInBreak(c,n)&&(n+=c.to%h-n%h);l.isInBreak(c,e)&&(e-=e%h-c.from%h)});b.forEach(function(c){f=c.from;for(h=c.repeat||Infinity;f-h>n;)f-=h;for(;f<n;)f+=h;for(r=f;r<e;r+=h)d.push({value:r,move:"in"}),d.push({value:r+(c.to-c.from),
move:"out",size:c.breakSize})});d.sort(function(c,a){return c.value===a.value?("in"===c.move?0:1)-("in"===a.move?0:1):c.value-a.value});var c=0;var f=n;d.forEach(function(b){c+="in"===b.move?1:-1;1===c&&"in"===b.move&&(f=b.value);0===c&&(a.push({from:f,to:b.value,len:b.value-f-(b.size||0)}),k+=b.value-f-(b.size||0))});l.breakArray=a;l.unitLength=e-n-k+m;D(l,"afterBreaks");l.staticScale?l.transA=l.staticScale:l.unitLength&&(l.transA*=(e-l.min+m)/l.unitLength);m&&(l.minPixelPadding=l.transA*l.minPointOffset);
l.min=n;l.max=e}});g(m,!0)&&this.chart.redraw()};e(m,"afterGeneratePoints",function(){var g=this.options.connectNulls,e=this.points,m=this.xAxis,t=this.yAxis;if(this.isDirty)for(var l=e.length;l--;){var d=e[l],b=!(null===d.y&&!1===g)&&(m&&m.isInAnyBreak(d.x,!0)||t&&t.isInAnyBreak(d.y,!0));d.visible=b?!1:!1!==d.options.visible}});e(m,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,g(this.pointArrayMap,["y"]))});p.Series.prototype.drawBreaks=function(e,m){var t=
this,p=t.points,l,d,b,q;e&&m.forEach(function(a){l=e.breakArray||[];d=e.isXAxis?e.min:g(t.options.threshold,e.min);p.forEach(function(k){q=g(k["stack"+a.toUpperCase()],k[a]);l.forEach(function(a){b=!1;if(d<a.from&&q>a.to||d>a.from&&q<a.from)b="pointBreak";else if(d<a.from&&q>a.from&&q<a.to||d>a.from&&q>a.to&&q<a.from)b="pointInBreak";b&&D(e,b,{point:k,brk:a})})})})};p.Series.prototype.gappedPath=function(){var g=this.currentDataGrouping,e=g&&g.gapSize;g=this.options.gapSize;var m=this.points.slice(),
t=m.length-1,l=this.yAxis,d;if(g&&0<t)for("value"!==this.options.gapUnit&&(g*=this.basePointRange),e&&e>g&&e>=this.basePointRange&&(g=e),d=void 0;t--;)d&&!1!==d.visible||(d=m[t+1]),e=m[t],!1!==d.visible&&!1!==e.visible&&(d.x-e.x>g&&(d=(e.x+d.x)/2,m.splice(t+1,0,{isNull:!0,x:d}),this.options.stacking&&(d=l.stacks[this.stackKey][d]=new J(l,l.options.stackLabels,!1,d,this.stack),d.total=0)),d=e);return this.getGraphPath(m)}});G(p,"masters/modules/broken-axis.src.js",[],function(){});G(p,"parts/DataGrouping.js",
[p["parts/Globals.js"],p["parts/Point.js"],p["parts/Tooltip.js"],p["parts/Utilities.js"]],function(p,m,J,e){"";var A=e.addEvent,u=e.arrayMax,D=e.arrayMin,t=e.correctFloat,g=e.defined,E=e.error,F=e.extend,B=e.format,z=e.isNumber,C=e.merge,w=e.pick,l=p.Axis,d=p.defaultPlotOptions;e=p.Series;var b=p.approximations={sum:function(c){var a=c.length;if(!a&&c.hasNulls)var b=null;else if(a)for(b=0;a--;)b+=c[a];return b},average:function(c){var a=c.length;c=b.sum(c);z(c)&&a&&(c=t(c/a));return c},averages:function(){var c=
[];[].forEach.call(arguments,function(a){c.push(b.average(a))});return"undefined"===typeof c[0]?void 0:c},open:function(c){return c.length?c[0]:c.hasNulls?null:void 0},high:function(c){return c.length?u(c):c.hasNulls?null:void 0},low:function(c){return c.length?D(c):c.hasNulls?null:void 0},close:function(c){return c.length?c[c.length-1]:c.hasNulls?null:void 0},ohlc:function(c,a,d,h){c=b.open(c);a=b.high(a);d=b.low(d);h=b.close(h);if(z(c)||z(a)||z(d)||z(h))return[c,a,d,h]},range:function(c,a){c=b.low(c);
a=b.high(a);if(z(c)||z(a))return[c,a];if(null===c&&null===a)return null}},q=function(c,a,d,h){var f=this,k=f.data,n=f.options&&f.options.data,v=[],r=[],e=[],x=c.length,q=!!a,l=[],y=f.pointArrayMap,m=y&&y.length,t=["x"].concat(y||["y"]),p=0,A=0,w;h="function"===typeof h?h:b[h]?b[h]:b[f.getDGApproximation&&f.getDGApproximation()||"average"];m?y.forEach(function(){l.push([])}):l.push([]);var M=m||1;for(w=0;w<=x&&!(c[w]>=d[0]);w++);for(w;w<=x;w++){for(;"undefined"!==typeof d[p+1]&&c[w]>=d[p+1]||w===x;){var u=
d[p];f.dataGroupInfo={start:f.cropStart+A,length:l[0].length};var B=h.apply(f,l);f.pointClass&&!g(f.dataGroupInfo.options)&&(f.dataGroupInfo.options=C(f.pointClass.prototype.optionsToObject.call({series:f},f.options.data[f.cropStart+A])),t.forEach(function(c){delete f.dataGroupInfo.options[c]}));"undefined"!==typeof B&&(v.push(u),r.push(B),e.push(f.dataGroupInfo));A=w;for(u=0;u<M;u++)l[u].length=0,l[u].hasNulls=!1;p+=1;if(w===x)break}if(w===x)break;if(y)for(u=f.cropStart+w,B=k&&k[u]||f.pointClass.prototype.applyOptions.apply({series:f},
[n[u]]),u=0;u<m;u++){var H=B[y[u]];z(H)?l[u].push(H):null===H&&(l[u].hasNulls=!0)}else u=q?a[w]:null,z(u)?l[0].push(u):null===u&&(l[0].hasNulls=!0)}return{groupedXData:v,groupedYData:r,groupMap:e}},a={approximations:b,groupData:q},k=e.prototype,h=k.processData,n=k.generatePoints,y={groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M",
"-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},M={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},r=p.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,
5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];k.getDGApproximation=function(){return this.is("arearange")?"range":this.is("ohlc")?"ohlc":this.is("column")?"sum":"average"};k.groupData=q;k.processData=function(){var c=this.chart,a=this.options.dataGrouping,b=!1!==this.allowDG&&a&&w(a.enabled,c.options.isStock),d=this.visible||!c.options.chart.ignoreHiddenSeries,n,e=this.currentDataGrouping,l=!1;this.forceCrop=b;this.groupPixelWidth=
null;this.hasProcessed=!0;b&&!this.requireSorting&&(this.requireSorting=l=!0);b=!1===h.apply(this,arguments)||!b;l&&(this.requireSorting=!1);if(!b){this.destroyGroupedData();b=a.groupAll?this.xData:this.processedXData;var q=a.groupAll?this.yData:this.processedYData,y=c.plotSizeX;c=this.xAxis;var m=c.options.ordinal,t=this.groupPixelWidth=c.getGroupPixelWidth&&c.getGroupPixelWidth();if(t){this.isDirty=n=!0;this.points=null;l=c.getExtremes();var p=l.min;l=l.max;m=m&&c.ordinal&&c.ordinal.getGroupIntervalFactor(p,
l,this)||1;t=t*(l-p)/y*m;y=c.getTimeTicks(c.normalizeTimeTickInterval(t,a.units||r),Math.min(p,b[0]),Math.max(l,b[b.length-1]),c.options.startOfWeek,b,this.closestPointRange);q=k.groupData.apply(this,[b,q,y,a.approximation]);b=q.groupedXData;m=q.groupedYData;var A=0;if(a.smoothed&&b.length){var u=b.length-1;for(b[u]=Math.min(b[u],l);u--&&0<u;)b[u]+=t/2;b[0]=Math.max(b[0],p)}for(u=1;u<y.length;u++)y.info.segmentStarts&&-1!==y.info.segmentStarts.indexOf(u)||(A=Math.max(y[u]-y[u-1],A));p=y.info;p.gapSize=
A;this.closestPointRange=y.info.totalRange;this.groupMap=q.groupMap;if(g(b[0])&&b[0]<c.min&&d){if(!g(c.options.min)&&c.min<=c.dataMin||c.min===c.dataMin)c.min=Math.min(b[0],c.min);c.dataMin=Math.min(b[0],c.dataMin)}a.groupAll&&(a=this.cropData(b,m,c.min,c.max,1),b=a.xData,m=a.yData);this.processedXData=b;this.processedYData=m}else this.groupMap=null;this.hasGroupedData=n;this.currentDataGrouping=p;this.preventGraphAnimation=(e&&e.totalRange)!==(p&&p.totalRange)}};k.destroyGroupedData=function(){this.groupedData&&
(this.groupedData.forEach(function(c,a){c&&(this.groupedData[a]=c.destroy?c.destroy():null)},this),this.groupedData.length=0)};k.generatePoints=function(){n.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};A(m,"update",function(){if(this.dataGroup)return E(24,!1,this.series.chart),!1});A(J,"headerFormatter",function(c){var a=this.chart,b=a.time,d=c.labelConfig,h=d.series,k=h.tooltipOptions,n=h.options.dataGrouping,r=k.xDateFormat,e=h.xAxis,g=k[(c.isFooter?
"footer":"header")+"Format"];if(e&&"datetime"===e.options.type&&n&&z(d.key)){var l=h.currentDataGrouping;n=n.dateTimeLabelFormats||y.dateTimeLabelFormats;if(l)if(k=n[l.unitName],1===l.count)r=k[0];else{r=k[1];var q=k[2]}else!r&&n&&(r=this.getXDateFormat(d,k,e));r=b.dateFormat(r,d.key);q&&(r+=b.dateFormat(q,d.key+l.totalRange-1));h.chart.styledMode&&(g=this.styledModeFormat(g));c.text=B(g,{point:F(d.point,{key:r}),series:h},a);c.preventDefault()}});A(e,"destroy",k.destroyGroupedData);A(e,"afterSetOptions",
function(c){c=c.options;var a=this.type,b=this.chart.options.plotOptions,h=d[a].dataGrouping,k=this.useCommonDataGrouping&&y;if(M[a]||k)h||(h=C(y,M[a])),c.dataGrouping=C(k,h,b.series&&b.series.dataGrouping,b[a].dataGrouping,this.userOptions.dataGrouping)});A(l,"afterSetScale",function(){this.series.forEach(function(c){c.hasProcessed=!1})});l.prototype.getGroupPixelWidth=function(){var c=this.series,a=c.length,b,d=0,h=!1,k;for(b=a;b--;)(k=c[b].options.dataGrouping)&&(d=Math.max(d,w(k.groupPixelWidth,
y.groupPixelWidth)));for(b=a;b--;)(k=c[b].options.dataGrouping)&&c[b].hasProcessed&&(a=(c[b].processedXData||c[b].data).length,c[b].groupPixelWidth||a>this.chart.plotSizeX/d||a&&k.forced)&&(h=!0);return h?d:0};l.prototype.setDataGrouping=function(c,a){var b;a=w(a,!0);c||(c={forced:!1,units:null});if(this instanceof l)for(b=this.series.length;b--;)this.series[b].update({dataGrouping:c},!1);else this.chart.options.series.forEach(function(a){a.dataGrouping=c},!1);this.ordinal&&(this.ordinal.slope=void 0);
a&&this.chart.redraw()};p.dataGrouping=a;"";return a});G(p,"parts/OHLCSeries.js",[p["parts/Globals.js"],p["parts/Point.js"],p["parts/Utilities.js"]],function(p,m,J){J=J.seriesType;var e=p.seriesTypes;J("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,
pointArrayMap:["open","high","low","close"],toYData:function(e){return[e.open,e.high,e.low,e.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},init:function(){e.column.prototype.init.apply(this,arguments);this.options.stacking=!1},pointAttribs:function(m,p){p=e.column.prototype.pointAttribs.call(this,m,p);var u=this.options;delete p.fill;!m.options.color&&u.upColor&&m.open<m.close&&(p.stroke=u.upColor);return p},translate:function(){var m=this,p=m.yAxis,u=
!!m.modifyValue,t=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];e.column.prototype.translate.apply(m);m.points.forEach(function(e){[e.open,e.high,e.low,e.close,e.low].forEach(function(g,A){null!==g&&(u&&(g=m.modifyValue(g)),e[t[A]]=p.toPixels(g,!0))});e.tooltipPos[1]=e.plotHigh+p.pos-m.chart.plotTop})},drawPoints:function(){var e=this,m=e.chart,p=function(e,g,m){e[2]=Math.max(m+g,e[2]);e[5]=Math.min(m-g,e[5])};e.points.forEach(function(t){var g=t.graphic,u=!g;if("undefined"!==typeof t.plotY){g||
(t.graphic=g=m.renderer.path().add(e.group));m.styledMode||g.attr(e.pointAttribs(t,t.selected&&"select"));var A=g.strokeWidth();var B=A%2/2;var z=Math.round(t.plotX)-B;var C=Math.round(t.shapeArgs.width/2);var w=["M",z,Math.round(t.yBottom),"L",z,Math.round(t.plotHigh)];if(null!==t.open){var l=Math.round(t.plotOpen)+B;w.push("M",z,l,"L",z-C,l);p(w,A/2,l)}null!==t.close&&(l=Math.round(t.plotClose)+B,w.push("M",z,l,"L",z+C,l),p(w,A/2,l));g[u?"attr":"animate"]({d:w}).addClass(t.getClassName(),!0)}})},
animate:null},{getClassName:function(){return m.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}});""});G(p,"parts/CandlestickSeries.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(p,m){var u=m.merge;m=m.seriesType;var e=p.defaultPlotOptions,A=p.seriesTypes;m("candlestick","ohlc",u(e.column,{states:{hover:{lineWidth:2}},tooltip:e.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(e,
m){var p=A.column.prototype.pointAttribs.call(this,e,m),g=this.options,u=e.open<e.close,D=g.lineColor||this.color;p["stroke-width"]=g.lineWidth;p.fill=e.options.color||(u?g.upColor||this.color:this.color);p.stroke=e.options.lineColor||(u?g.upLineColor||D:D);m&&(e=g.states[m],p.fill=e.color||p.fill,p.stroke=e.lineColor||p.stroke,p["stroke-width"]=e.lineWidth||p["stroke-width"]);return p},drawPoints:function(){var e=this,m=e.chart,p=e.yAxis.reversed;e.points.forEach(function(g){var t=g.graphic,u=!t;
if("undefined"!==typeof g.plotY){t||(g.graphic=t=m.renderer.path().add(e.group));e.chart.styledMode||t.attr(e.pointAttribs(g,g.selected&&"select")).shadow(e.options.shadow);var A=t.strokeWidth()%2/2;var z=Math.round(g.plotX)-A;var C=g.plotOpen;var w=g.plotClose;var l=Math.min(C,w);C=Math.max(C,w);var d=Math.round(g.shapeArgs.width/2);w=p?C!==g.yBottom:Math.round(l)!==Math.round(g.plotHigh);var b=p?Math.round(l)!==Math.round(g.plotHigh):C!==g.yBottom;l=Math.round(l)+A;C=Math.round(C)+A;A=[];A.push("M",
z-d,C,"L",z-d,l,"L",z+d,l,"L",z+d,C,"Z","M",z,l,"L",z,w?Math.round(p?g.yBottom:g.plotHigh):l,"M",z,C,"L",z,b?Math.round(p?g.plotHigh:g.yBottom):C);t[u?"attr":"animate"]({d:A}).addClass(g.getClassName(),!0)}})}});""});G(p,"mixins/on-series.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(p,m){var u=m.defined,e=m.stableSort,A=p.seriesTypes;return{getPlotBox:function(){return p.Series.prototype.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){A.column.prototype.translate.apply(this);
var m=this,p=m.options,t=m.chart,g=m.points,E=g.length-1,F,B=p.onSeries;B=B&&t.get(B);p=p.onKey||"y";var z=B&&B.options.step,C=B&&B.points,w=C&&C.length,l=t.inverted,d=m.xAxis,b=m.yAxis,q=0,a;if(B&&B.visible&&w){q=(B.pointXOffset||0)+(B.barW||0)/2;t=B.currentDataGrouping;var k=C[w-1].x+(t?t.totalRange:0);e(g,function(a,b){return a.x-b.x});for(p="plot"+p[0].toUpperCase()+p.substr(1);w--&&g[E];){var h=C[w];t=g[E];t.y=h.y;if(h.x<=t.x&&"undefined"!==typeof h[p]){if(t.x<=k&&(t.plotY=h[p],h.x<t.x&&!z&&
(a=C[w+1])&&"undefined"!==typeof a[p])){var n=(t.x-h.x)/(a.x-h.x);t.plotY+=n*(a[p]-h[p]);t.y+=n*(a.y-h.y)}E--;w++;if(0>E)break}}}g.forEach(function(a,h){a.plotX+=q;if("undefined"===typeof a.plotY||l)0<=a.plotX&&a.plotX<=d.len?l?(a.plotY=d.translate(a.x,0,1,0,1),a.plotX=u(a.y)?b.translate(a.y,0,0,0,1):0):a.plotY=(d.opposite?0:m.yAxis.len)+d.offset:a.shapeArgs={};if((F=g[h-1])&&F.plotX===a.plotX){"undefined"===typeof F.stackIndex&&(F.stackIndex=0);var k=F.stackIndex+1}a.stackIndex=k});this.onSeries=
B}}});G(p,"parts/FlagsSeries.js",[p["parts/Globals.js"],p["parts/Utilities.js"],p["mixins/on-series.js"]],function(p,m,J){function e(d){l[d+"pin"]=function(b,e,a,k,h){var n=h&&h.anchorX;h=h&&h.anchorY;"circle"===d&&k>a&&(b-=Math.round((k-a)/2),a=k);var g=l[d](b,e,a,k);n&&h&&(g.push("M","circle"===d?b+a/2:g[1]+g[4]/2,e>h?e:e+k,"L",n,h),g=g.concat(l.circle(n-1,h-1,2,2)));return g}}var u=m.addEvent,H=m.defined,D=m.isNumber,t=m.merge,g=m.objectEach,E=m.seriesType,F=m.wrap;m=p.noop;var B=p.Renderer,z=
p.Series,C=p.TrackerMixin,w=p.VMLRenderer,l=p.SVGRenderer.prototype.symbols;E("flags","column",{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30,fillColor:"#ffffff",lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:z.prototype.init,pointAttribs:function(d,
b){var e=this.options,a=d&&d.color||this.color,k=e.lineColor,h=d&&d.lineWidth;d=d&&d.fillColor||e.fillColor;b&&(d=e.states[b].fillColor,k=e.states[b].lineColor,h=e.states[b].lineWidth);return{fill:d||a,stroke:k||a,"stroke-width":h||e.lineWidth||0}},translate:J.translate,getPlotBox:J.getPlotBox,drawPoints:function(){var d=this.points,b=this.chart,e=b.renderer,a=b.inverted,k=this.options,h=k.y,n,m=this.yAxis,l={},r=[];for(n=d.length;n--;){var c=d[n];var f=(a?c.plotY:c.plotX)>this.xAxis.len;var v=c.plotX;
var x=c.stackIndex;var u=c.options.shape||k.shape;var w=c.plotY;"undefined"!==typeof w&&(w=c.plotY+h-("undefined"!==typeof x&&x*k.stackDistance));c.anchorX=x?void 0:c.plotX;var A=x?void 0:c.plotY;var z="flag"!==u;x=c.graphic;"undefined"!==typeof w&&0<=v&&!f?(x||(x=c.graphic=e.label("",null,null,u,null,null,k.useHTML),b.styledMode||x.attr(this.pointAttribs(c)).css(t(k.style,c.style)),x.attr({align:z?"center":"left",width:k.width,height:k.height,"text-align":k.textAlign}).addClass("highcharts-point").add(this.markerGroup),
c.graphic.div&&(c.graphic.div.point=c),b.styledMode||x.shadow(k.shadow),x.isNew=!0),0<v&&(v-=x.strokeWidth()%2),u={y:w,anchorY:A},k.allowOverlapX&&(u.x=v,u.anchorX=c.anchorX),x.attr({text:c.options.title||k.title||"A"})[x.isNew?"attr":"animate"](u),k.allowOverlapX||(l[c.plotX]?l[c.plotX].size=Math.max(l[c.plotX].size,x.width):l[c.plotX]={align:z?.5:0,size:x.width,target:v,anchorX:v}),c.tooltipPos=[v,w+m.pos-b.plotTop]):x&&(c.graphic=x.destroy())}k.allowOverlapX||(g(l,function(a){a.plotX=a.anchorX;
r.push(a)}),p.distribute(r,a?m.len:this.xAxis.len,100),d.forEach(function(a){var c=a.graphic&&l[a.plotX];c&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:c.pos+c.align*c.size,anchorX:a.anchorX}),H(c.pos)?a.graphic.isNew=!1:(a.graphic.attr({x:-9999,anchorX:-9999}),a.graphic.isNew=!0))}));k.useHTML&&F(this.markerGroup,"on",function(a){return p.SVGElement.prototype.on.apply(a.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var d=this.points;C.drawTrackerPoint.apply(this);
d.forEach(function(b){var e=b.graphic;e&&u(e.element,"mouseover",function(){0<b.stackIndex&&!b.raised&&(b._y=e.y,e.attr({y:b._y-8}),b.raised=!0);d.forEach(function(a){a!==b&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})},animate:function(d){d&&this.setClip()},setClip:function(){z.prototype.setClip.apply(this,arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])},buildKDTree:m,invertGroups:m},{isValid:function(){return D(this.y)||
"undefined"===typeof this.y}});l.flag=function(d,b,e,a,k){var h=k&&k.anchorX||d;k=k&&k.anchorY||b;return l.circle(h-1,k-1,2,2).concat(["M",h,k,"L",d,b+a,d,b,d+e,b,d+e,b+a,d,b+a,"Z"])};e("circle");e("square");B===w&&["circlepin","flag","squarepin"].forEach(function(d){w.prototype.symbols[d]=l[d]});""});G(p,"parts/RangeSelector.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(p,m){function u(a){this.init(a)}var e=m.addEvent,A=m.createElement,H=m.css,D=m.defined,t=m.destroyObjectProperties,
g=m.discardElement,E=m.extend,F=m.fireEvent,B=m.isNumber,z=m.merge,C=m.objectEach,w=m.pick,l=m.pInt,d=m.splat,b=p.Axis;m=p.Chart;var q=p.defaultOptions;E(q,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});q.lang=z(q.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});u.prototype={clickButton:function(a,
k){var h=this.chart,n=this.buttonOptions[a],g=h.xAxis[0],l=h.scroller&&h.scroller.getUnionExtremes()||g||{},r=l.dataMin,c=l.dataMax,f=g&&Math.round(Math.min(g.max,w(c,g.max))),m=n.type;l=n._range;var p,q=n.dataGrouping;if(null!==r&&null!==c){h.fixedRange=l;q&&(this.forcedDataGrouping=!0,b.prototype.setDataGrouping.call(g||{chart:this.chart},q,!1),this.frozenStates=n.preserveDataGrouping);if("month"===m||"year"===m)if(g){m={range:n,max:f,chart:h,dataMin:r,dataMax:c};var t=g.minFromRange.call(m);B(m.newMax)&&
(f=m.newMax)}else l=n;else if(l)t=Math.max(f-l,r),f=Math.min(t+l,c);else if("ytd"===m)if(g)"undefined"===typeof c&&(r=Number.MAX_VALUE,c=Number.MIN_VALUE,h.series.forEach(function(a){a=a.xData;r=Math.min(a[0],r);c=Math.max(a[a.length-1],c)}),k=!1),f=this.getYTDExtremes(c,r,h.time.useUTC),t=p=f.min,f=f.max;else{this.deferredYTDClick=a;return}else"all"===m&&g&&(t=r,f=c);t+=n._offsetMin;f+=n._offsetMax;this.setSelected(a);if(g)g.setExtremes(t,f,w(k,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:n});
else{var u=d(h.options.xAxis)[0];var A=u.range;u.range=l;var z=u.min;u.min=p;e(h,"load",function(){u.range=A;u.min=z})}}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var b=this,d=a.options.rangeSelector,n=d.buttons||[].concat(b.defaultButtons),g=d.selected,l=function(){var a=
b.minInput,c=b.maxInput;a&&a.blur&&F(a,"blur");c&&c.blur&&F(c,"blur")};b.chart=a;b.options=d;b.buttons=[];b.buttonOptions=n;this.unMouseDown=e(a.container,"mousedown",l);this.unResize=e(a,"resize",l);n.forEach(b.computeButtonRange);"undefined"!==typeof g&&n[g]&&this.clickButton(g,!1);e(a,"load",function(){a.xAxis&&a.xAxis[0]&&e(a.xAxis[0],"setExtremes",function(d){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==d.trigger&&"updatedData"!==d.trigger&&b.forcedDataGrouping&&!b.frozenStates&&
this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this,b=this.chart,d=b.xAxis[0],e=Math.round(d.max-d.min),g=!d.hasVisibleSeries,l=b.scroller&&b.scroller.getUnionExtremes()||d,r=l.dataMin,c=l.dataMax;b=a.getYTDExtremes(c,r,b.time.useUTC);var f=b.min,m=b.max,p=a.selected,q=B(p),t=a.options.allButtonsEnabled,u=a.buttons;a.buttonOptions.forEach(function(b,h){var k=b._range,n=b.type,l=b.count||1,v=u[h],x=0,y=b._offsetMax-b._offsetMin;b=h===p;var w=k>c-r,A=k<d.minRange,z=!1,B=!1;k=k===
e;("month"===n||"year"===n)&&e+36E5>=864E5*{month:28,year:365}[n]*l-y&&e-36E5<=864E5*{month:31,year:366}[n]*l+y?k=!0:"ytd"===n?(k=m-f+y===e,z=!b):"all"===n&&(k=d.max-d.min>=c-r,B=!b&&q&&k);n=!t&&(w||A||B||g);l=b&&k||k&&!q&&!z||b&&a.frozenStates;n?x=3:l&&(q=!0,x=2);v.state!==x&&(v.setState(x),0===x&&p===h&&a.setSelected(null))})},computeButtonRange:function(a){var b=a.type,d=a.count||1,e={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(e[b])a._range=e[b]*d;else if("month"===
b||"year"===b)a._range=864E5*{month:30,year:365}[b]*d;a._offsetMin=w(a.offsetMin,0);a._offsetMax=w(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,b){var d=this.chart.options.rangeSelector,e=this.chart.time,k=this[a+"Input"];D(b)&&(k.previousValue=k.HCTime,k.HCTime=b);k.value=e.dateFormat(d.inputEditDateFormat||"%Y-%m-%d",k.HCTime);this[a+"DateBox"].attr({text:e.dateFormat(d.inputDateFormat||"%b %e, %Y",k.HCTime)})},showInput:function(a){var b=this.inputGroup,d=this[a+
"DateBox"];H(this[a+"Input"],{left:b.translateX+d.x+"px",top:b.translateY+"px",width:d.width-2+"px",height:d.height-2+"px",border:"2px solid silver"})},hideInput:function(a){H(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function b(){var a=v.value,c=(r.inputDateParser||Date.parse)(a),b=e.xAxis[0],h=e.scroller&&e.scroller.xAxis?e.scroller.xAxis:b,k=h.dataMin;h=h.dataMax;c!==v.previousValue&&(v.previousValue=c,B(c)||(c=a.split("-"),c=Date.UTC(l(c[0]),
l(c[1])-1,l(c[2]))),B(c)&&(e.time.useUTC||(c+=6E4*(new Date).getTimezoneOffset()),f?c>d.maxInput.HCTime?c=void 0:c<k&&(c=k):c<d.minInput.HCTime?c=void 0:c>h&&(c=h),"undefined"!==typeof c&&b.setExtremes(f?c:b.min,f?b.max:c,void 0,void 0,{trigger:"rangeSelectorInput"})))}var d=this,e=d.chart,g=e.renderer.style||{},m=e.renderer,r=e.options.rangeSelector,c=d.div,f="min"===a,v,x,t=this.inputGroup;this[a+"Label"]=x=m.label(q.lang[f?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(t);
t.offset+=x.width+5;this[a+"DateBox"]=m=m.label("",t.offset).addClass("highcharts-range-input").attr({padding:2,width:r.inputBoxWidth||90,height:r.inputBoxHeight||17,"text-align":"center"}).on("click",function(){d.showInput(a);d[a+"Input"].focus()});e.styledMode||m.attr({stroke:r.inputBoxBorderColor||"#cccccc","stroke-width":1});m.add(t);t.offset+=m.width+(f?10:0);this[a+"Input"]=v=A("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:e.plotTop+"px"},c);e.styledMode||(x.css(z(g,
r.labelStyle)),m.css(z({color:"#333333"},g,r.inputStyle)),H(v,E({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:g.fontSize,fontFamily:g.fontFamily,top:"-9999em"},r.inputStyle)));v.onfocus=function(){d.showInput(a)};v.onblur=function(){v===p.doc.activeElement&&b();d.hideInput(a);v.blur()};v.onchange=b;v.onkeypress=function(a){13===a.keyCode&&b()}},getPosition:function(){var a=this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:
0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}},getYTDExtremes:function(a,b,d){var e=this.chart.time,h=new e.Date(a),k=e.get("FullYear",h);d=d?e.Date.UTC(k,0,1):+new e.Date(k,0,1);b=Math.max(b||0,d);h=h.getTime();return{max:Math.min(a||h,h),min:b}},render:function(a,b){var d=this,e=d.chart,k=e.renderer,g=e.container,r=e.options,c=r.exporting&&!1!==r.exporting.enabled&&r.navigation&&r.navigation.buttonOptions,f=q.lang,l=d.div,m=r.rangeSelector,p=w(r.chart.style&&r.chart.style.zIndex,
0)+1;r=m.floating;var t=d.buttons;l=d.inputGroup;var u=m.buttonTheme,z=m.buttonPosition,B=m.inputPosition,C=m.inputEnabled,E=u&&u.states,D=e.plotLeft,F=d.buttonGroup,H,G=d.options.verticalAlign,J=e.legend,O=J&&J.options,P=z.y,N=B.y,Q=e.hasLoaded,R=Q?"animate":"attr",L=0,K=0;if(!1!==m.enabled){d.rendered||(d.group=H=k.g("range-selector-group").attr({zIndex:7}).add(),d.buttonGroup=F=k.g("range-selector-buttons").add(H),d.zoomText=k.text(f.rangeSelectorZoom,0,15).add(F),e.styledMode||(d.zoomText.css(m.labelStyle),
u["stroke-width"]=w(u["stroke-width"],0)),d.buttonOptions.forEach(function(a,c){t[c]=k.button(a.text,0,0,function(b){var f=a.events&&a.events.click,e;f&&(e=f.call(a,b));!1!==e&&d.clickButton(c);d.isActive=!0},u,E&&E.hover,E&&E.select,E&&E.disabled).attr({"text-align":"center"}).add(F)}),!1!==C&&(d.div=l=A("div",null,{position:"relative",height:0,zIndex:p}),g.parentNode.insertBefore(l,g),d.inputGroup=l=k.g("input-group").add(H),l.offset=0,d.drawInput("min"),d.drawInput("max")));d.zoomText[R]({x:w(D+
z.x,D)});var S=w(D+z.x,D)+d.zoomText.getBBox().width+5;d.buttonOptions.forEach(function(a,c){t[c][R]({x:S});S+=t[c].width+w(m.buttonSpacing,5)});D=e.plotLeft-e.spacing[3];d.updateButtonStates();c&&this.titleCollision(e)&&"top"===G&&"right"===z.align&&z.y+F.getBBox().height-12<(c.y||0)+c.height&&(L=-40);g=z.x-e.spacing[3];"right"===z.align?g+=L-D:"center"===z.align&&(g-=D/2);F.align({y:z.y,width:F.getBBox().width,align:z.align,x:g},!0,e.spacingBox);d.group.placed=Q;d.buttonGroup.placed=Q;!1!==C&&(L=
c&&this.titleCollision(e)&&"top"===G&&"right"===B.align&&B.y-l.getBBox().height-12<(c.y||0)+c.height+e.spacing[0]?-40:0,"left"===B.align?g=D:"right"===B.align&&(g=-Math.max(e.axisOffset[1],-L)),l.align({y:B.y,width:l.getBBox().width,align:B.align,x:B.x+g-2},!0,e.spacingBox),c=l.alignAttr.translateX+l.alignOptions.x-L+l.getBBox().x+2,g=l.alignOptions.width,f=F.alignAttr.translateX+F.getBBox().x,D=F.getBBox().width+20,(B.align===z.align||f+D>c&&c+g>f&&P<N+l.getBBox().height)&&l.attr({translateX:l.alignAttr.translateX+
(e.axisOffset[1]>=-L?0:-L),translateY:l.alignAttr.translateY+F.getBBox().height+10}),d.setInputValue("min",a),d.setInputValue("max",b),d.inputGroup.placed=Q);d.group.align({verticalAlign:G},!0,e.spacingBox);a=d.group.getBBox().height+20;b=d.group.alignAttr.translateY;"bottom"===G&&(J=O&&"bottom"===O.verticalAlign&&O.enabled&&!O.floating?J.legendHeight+w(O.margin,10):0,a=a+J-20,K=b-a-(r?0:m.y)-(e.titleOffset?e.titleOffset[2]:0)-10);if("top"===G)r&&(K=0),e.titleOffset&&e.titleOffset[0]&&(K=e.titleOffset[0]),
K+=e.margin[0]-e.spacing[0]||0;else if("middle"===G)if(N===P)K=0>N?b+void 0:b;else if(N||P)K=0>N||0>P?K-Math.min(N,P):b-a+NaN;d.group.translate(m.x,m.y+Math.floor(K));!1!==C&&(d.minInput.style.marginTop=d.group.translateY+"px",d.maxInput.style.marginTop=d.group.translateY+"px");d.rendered=!0}},getHeight:function(){var a=this.options,b=this.group,d=a.y,e=a.buttonPosition.y,g=a.inputPosition.y;if(a.height)return a.height;a=b?b.getBBox(!0).height+13+d:0;b=Math.min(g,e);if(0>g&&0>e||0<g&&0<e)a+=Math.abs(b);
return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var b=this.chart;z(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()},destroy:function(){var a=this,b=a.minInput,d=a.maxInput;a.unMouseDown();a.unResize();t(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);d&&(d.onfocus=d.onblur=d.onchange=null);C(a,function(b,d){b&&"chart"!==d&&(b.destroy?b.destroy():b.nodeType&&g(this[d]));b!==u.prototype[d]&&(a[d]=null)},
this)}};b.prototype.minFromRange=function(){var a=this.range,b=a.type,d=this.max,e=this.chart.time,g=function(a,c){var d="year"===b?"FullYear":"Month",f=new e.Date(a),k=e.get(d,f);e.set(d,f,k+c);k===e.get(d,f)&&e.set("Date",f,0);return f.getTime()-a};if(B(a)){var l=d-a;var m=a}else l=d+g(d,-a.count),this.chart&&(this.chart.fixedRange=d-l);var c=w(this.dataMin,Number.MIN_VALUE);B(l)||(l=c);l<=c&&(l=c,"undefined"===typeof m&&(m=g(l,a.count)),this.newMax=Math.min(l+m,this.dataMax));B(d)||(l=void 0);
return l};p.RangeSelector||(e(m,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new u(this))}),e(m,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(B(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),
e(m,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var d=this.extraBottomMargin,e=this.extraTopMargin;b&&b.enabled&&!D(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new u(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==d||this.extraTopMargin!==e)&&(this.isDirtyBox=
!0)}),e(m,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),e(m,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),m.prototype.callbacks.push(function(a){function b(){d=a.xAxis[0].getExtremes();B(d.min)&&g.render(d.min,d.max)}var d,g=a.rangeSelector;if(g){var l=
e(a.xAxis[0],"afterSetExtremes",function(a){g.render(a.min,a.max)});var m=e(a,"redraw",b);b()}e(a,"destroy",function(){g&&(m(),l())})}),p.RangeSelector=u)});G(p,"parts/StockChart.js",[p["parts/Axis.js"],p["parts/Globals.js"],p["parts/Point.js"],p["parts/Utilities.js"]],function(p,m,G,e){var u=e.addEvent,H=e.arrayMax,D=e.arrayMin,t=e.clamp,g=e.defined,E=e.extend,F=e.find,B=e.format,z=e.isNumber,C=e.isString,w=e.merge,l=e.pick,d=e.splat,b=m.Chart;e=m.Renderer;var q=m.Series,a=m.SVGRenderer,k=m.VMLRenderer,
h=q.prototype,n=h.init,y=h.processData,J=G.prototype.tooltipFormatter;m.StockChart=m.stockChart=function(a,c,f){var e=C(a)||a.nodeName,g=arguments[e?1:0],h=g,k=g.series,r=m.getOptions(),n,p=g.chart&&g.chart.panning,q=l(g.navigator&&g.navigator.enabled,r.navigator.enabled,!0),t=p&&/y/.test(p.type),u={startOnTick:!1,endOnTick:!1};g.xAxis=d(g.xAxis||{}).map(function(a,c){return w({minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},r.xAxis,
r.xAxis&&r.xAxis[c],a,{type:"datetime",categories:null},q?u:null)});g.yAxis=d(g.yAxis||{}).map(function(a,c){n=l(a.opposite,!0);return w({labels:{y:-2},opposite:n,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},r.yAxis,r.yAxis&&r.yAxis[c],a,t?u:null)});g.series=null;g=w({chart:{panning:{enabled:!0,type:"x"},pinchType:"x"},navigator:{enabled:q},scrollbar:{enabled:l(r.scrollbar.enabled,!0)},rangeSelector:{enabled:l(r.rangeSelector.enabled,!0)},title:{text:null},tooltip:{split:l(r.tooltip.split,
!0),crosshairs:!0},legend:{enabled:!1}},g,{isStock:!0});g.series=h.series=k;return e?new b(a,g,f):new b(g,c)};u(q,"setOptions",function(a){var c;this.chart.options.isStock&&(this.is("column")||this.is("columnrange")?c={borderWidth:0,shadow:!1}:this.is("scatter")||this.is("sma")||(c={marker:{enabled:!1,radius:2}}),c&&(a.plotOptions[this.type]=w(a.plotOptions[this.type],c)))});u(p,"autoLabelAlign",function(a){var c=this.chart,b=this.options;c=c._labelPanes=c._labelPanes||{};var d=this.options.labels;
this.chart.options.isStock&&"yAxis"===this.coll&&(b=b.top+","+b.height,!c[b]&&d.enabled&&(15===d.x&&(d.x=0),"undefined"===typeof d.align&&(d.align="right"),c[b]=this,a.align="right",a.preventDefault()))});u(p,"destroy",function(){var a=this.chart,c=this.options&&this.options.top+","+this.options.height;c&&a._labelPanes&&a._labelPanes[c]===this&&delete a._labelPanes[c]});u(p,"getPlotLinePath",function(a){function c(a){var c="xAxis"===a?"yAxis":"xAxis";a=b.options[c];return z(a)?[e[c][a]]:C(a)?[e.get(a)]:
d.map(function(a){return a[c]})}var b=this,d=this.isLinked&&!this.series?this.linkedParent.series:this.series,e=b.chart,h=e.renderer,k=b.left,m=b.top,r,n,p,q,u=[],w=[],y=a.translatedValue,A=a.value,B=a.force;if(e.options.isStock&&!1!==a.acrossPanes&&"xAxis"===b.coll||"yAxis"===b.coll){a.preventDefault();w=c(b.coll);var E=b.isXAxis?e.yAxis:e.xAxis;E.forEach(function(a){if(g(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var c=a.isXAxis?"yAxis":"xAxis";c=g(a.options[c])?e[c][a.options[c]]:
e[c][0];b===c&&w.push(a)}});var D=w.length?[]:[b.isXAxis?e.yAxis[0]:e.xAxis[0]];w.forEach(function(a){-1!==D.indexOf(a)||F(D,function(c){return c.pos===a.pos&&c.len===a.len})||D.push(a)});var G=l(y,b.translate(A,null,null,a.old));z(G)&&(b.horiz?D.forEach(function(a){var c;n=a.pos;q=n+a.len;r=p=Math.round(G+b.transB);"pass"!==B&&(r<k||r>k+b.width)&&(B?r=p=t(r,k,k+b.width):c=!0);c||u.push("M",r,n,"L",p,q)}):D.forEach(function(a){var c;r=a.pos;p=r+a.len;n=q=Math.round(m+b.height-G);"pass"!==B&&(n<m||
n>m+b.height)&&(B?n=q=t(n,m,m+b.height):c=!0);c||u.push("M",r,n,"L",p,q)}));a.path=0<u.length?h.crispPolyLine(u,a.lineWidth||1):null}});a.prototype.crispPolyLine=function(a,c){var b;for(b=0;b<a.length;b+=6)a[b+1]===a[b+4]&&(a[b+1]=a[b+4]=Math.round(a[b+1])-c%2/2),a[b+2]===a[b+5]&&(a[b+2]=a[b+5]=Math.round(a[b+2])+c%2/2);return a};e===k&&(k.prototype.crispPolyLine=a.prototype.crispPolyLine);u(p,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});u(p,"afterDrawCrosshair",
function(a){var c,b;if(g(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var d=this.chart,e=this.options.crosshair.label,h=this.horiz,k=this.opposite,m=this.left,n=this.top,p=this.crossLabel,r=e.format,q="",t="inside"===this.options.tickPosition,u=!1!==this.crosshair.snap,w=0,y=a.e||this.cross&&this.cross.e,z=a.point;var A=this.lin2log;if(this.isLog){a=A(this.min);var C=A(this.max)}else a=this.min,C=this.max;A=h?"center":k?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?
"left":"center";p||(p=this.crossLabel=d.renderer.label(null,null,null,e.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:e.align||A,padding:l(e.padding,8),r:l(e.borderRadius,3),zIndex:2}).add(this.labelGroup),d.styledMode||p.attr({fill:e.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:e.borderColor||"","stroke-width":e.borderWidth||0}).css(E({color:"#ffffff",fontWeight:"normal",fontSize:"11px",
textAlign:"center"},e.style)));h?(A=u?z.plotX+m:y.chartX,n+=k?0:this.height):(A=k?this.width+m:0,n=u?z.plotY+n:y.chartY);r||e.formatter||(this.isDatetimeAxis&&(q="%b %d, %Y"),r="{value"+(q?":"+q:"")+"}");q=u?z[this.isXAxis?"x":"y"]:this.toValue(h?y.chartX:y.chartY);p.attr({text:r?B(r,{value:q},d):e.formatter.call(this,q),x:A,y:n,visibility:q<a||q>C?"hidden":"visible"});e=p.getBBox();if(h){if(t&&!k||!t&&k)n=p.y-e.height}else n=p.y-e.height/2;h?(c=m-e.x,b=m+this.width-e.x):(c="left"===this.labelAlign?
m:0,b="right"===this.labelAlign?m+this.width:d.chartWidth);p.translateX<c&&(w=c-p.translateX);p.translateX+e.width>=b&&(w=-(p.translateX+e.width-b));p.attr({x:A+w,y:n,anchorX:h?A:this.opposite?0:d.chartWidth,anchorY:h?this.opposite?d.chartHeight:0:n+e.height/2})}});h.init=function(){n.apply(this,arguments);this.setCompare(this.options.compare)};h.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(c,b){var d=this.compareValue;return"undefined"!==typeof c&&"undefined"!==typeof d?
(c="value"===a?c-d:c/d*100-(100===this.options.compareBase?0:100),b&&(b.change=c),c):0}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=!0)};h.processData=function(a){var b,d=-1,e=!0===this.options.compareStart?0:1;y.apply(this,arguments);if(this.xAxis&&this.processedYData){var g=this.processedXData;var h=this.processedYData;var k=h.length;this.pointArrayMap&&(d=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(b=0;b<k-e;b++){var l=h[b]&&-1<d?h[b][d]:
h[b];if(z(l)&&g[b+e]>=this.xAxis.min&&0!==l){this.compareValue=l;break}}}};u(q,"afterGetExtremes",function(a){a=a.dataExtremes;if(this.modifyValue&&a){var b=[this.modifyValue(a.dataMin),this.modifyValue(a.dataMax)];a.dataMin=D(b);a.dataMax=H(b)}});p.prototype.setCompare=function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),l(b,!0)&&this.chart.redraw())};G.prototype.tooltipFormatter=function(a){var b=this.series.chart.numberFormatter;a=a.replace("{point.change}",(0<this.change?
"+":"")+b(this.change,l(this.series.tooltipOptions.changeDecimals,2)));return J.apply(this,[a])};u(q,"render",function(){var a=this.chart;if(!(a.is3d&&a.is3d()||a.polar)&&this.xAxis&&!this.xAxis.isRadial){var b=this.yAxis.len;if(this.xAxis.axisLine){var d=a.plotTop+a.plotHeight-this.yAxis.pos-this.yAxis.len,e=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=d&&(b-=Math.max(e-d,0))}!this.clipBox&&this.animate?(this.clipBox=w(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=b):a[this.sharedClipKey]&&
(a[this.sharedClipKey].animate({width:this.xAxis.len,height:b}),a[this.sharedClipKey+"m"]&&a[this.sharedClipKey+"m"].animate({width:this.xAxis.len}))}});u(b,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(w(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)});u(p,"afterSetScale",function(){var a=this,b=a.chart.options.chart&&a.chart.options.chart.panning;if(b&&("y"===b.type||"xy"===b.type)&&!a.isXAxis&&!g(a.panningState)){var d=Number.MAX_VALUE,
e=Number.MIN_VALUE;a.series.forEach(function(b){d=Math.min(D(b.yData),d)-(a.min&&a.dataMin?a.dataMin-a.min:0);e=Math.max(H(b.yData),e)+(a.max&&a.dataMax?a.max-a.dataMax:0)});a.panningState={startMin:d,startMax:e}}})});G(p,"masters/modules/stock.src.js",[],function(){})});
//# sourceMappingURL=stock.js.map