/*
 Highcharts JS v8.0.4 (2020-03-26)

 (c) 2009-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(e){"object"===typeof module&&module.exports?(e["default"]=e,module.exports=e):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(B){e(B);e.Highcharts=B;return e}):e("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(e){function B(l,b,d,a){l.hasOwnProperty(b)||(l[b]=a.apply(null,d))}e=e?e._modules:{};B(e,"parts-more/Pane.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(l,b){function d(h,a,b){return Math.sqrt(Math.pow(h-
b[0],2)+Math.pow(a-b[1],2))<b[2]/2}var a=b.addEvent,m=b.extend,u=b.merge,w=b.pick,e=b.splat,x=l.CenteredSeriesMixin;l.Chart.prototype.collectionsWithUpdate.push("pane");b=function(){function h(h,a){this.options=this.chart=this.center=this.background=void 0;this.coll="pane";this.defaultOptions={center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0};this.defaultBackgroundOptions={shape:"circle",borderWidth:1,borderColor:"#cccccc",backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,
"#ffffff"],[1,"#e6e6e6"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,outerRadius:"105%"};this.init(h,a)}h.prototype.init=function(h,a){this.chart=a;this.background=[];a.pane.push(this);this.setOptions(h)};h.prototype.setOptions=function(h){this.options=u(this.defaultOptions,this.chart.angular?{background:{}}:void 0,h)};h.prototype.render=function(){var h=this.options,a=this.options.background,b=this.chart.renderer;this.group||(this.group=b.g("pane-group").attr({zIndex:h.zIndex||0}).add());
this.updateCenter();if(a)for(a=e(a),h=Math.max(a.length,this.background.length||0),b=0;b<h;b++)a[b]&&this.axis?this.renderBackground(u(this.defaultBackgroundOptions,a[b]),b):this.background[b]&&(this.background[b]=this.background[b].destroy(),this.background.splice(b,1))};h.prototype.renderBackground=function(h,a){var b="animate",k={"class":"highcharts-pane "+(h.className||"")};this.chart.styledMode||m(k,{fill:h.backgroundColor,stroke:h.borderColor,"stroke-width":h.borderWidth});this.background[a]||
(this.background[a]=this.chart.renderer.path().add(this.group),b="attr");this.background[a][b]({d:this.axis.getPlotBandPath(h.from,h.to,h)}).attr(k)};h.prototype.updateCenter=function(h){this.center=(h||this.axis||{}).center=x.getCenter.call(this)};h.prototype.update=function(h,a){u(!0,this.options,h);u(!0,this.chart.options.pane,h);this.setOptions(this.options);this.render();this.chart.axes.forEach(function(h){h.pane===this&&(h.pane=null,h.update({},a))},this)};return h}();l.Chart.prototype.getHoverPane=
function(h){var a=this,b;h&&a.pane.forEach(function(q){var k=h.chartX-a.plotLeft,t=h.chartY-a.plotTop;d(a.inverted?t:k,a.inverted?k:t,q.center)&&(b=q)});return b};a(l.Chart,"afterIsInsidePlot",function(h){this.polar&&(h.isInsidePlot=this.pane.some(function(a){return d(h.x,h.y,a.center)}))});a(l.Pointer,"beforeGetHoverData",function(h){var a=this.chart;a.polar&&(a.hoverPane=a.getHoverPane(h),h.filter=function(b){return b.visible&&!(!h.shared&&b.directTouch)&&w(b.options.enableMouseTracking,!0)&&(!a.hoverPane||
b.xAxis.pane===a.hoverPane)})});a(l.Pointer,"afterGetHoverData",function(h){var a=this.chart;h.hoverPoint&&h.hoverPoint.plotX&&h.hoverPoint.plotY&&a.hoverPane&&!d(h.hoverPoint.plotX,h.hoverPoint.plotY,a.hoverPane.center)&&(h.hoverPoint=void 0)});l.Pane=b;return l.Pane});B(e,"parts-more/HiddenAxis.js",[],function(){return function(){function l(){}l.init=function(b){b.getOffset=function(){};b.redraw=function(){this.isDirty=!1};b.render=function(){this.isDirty=!1};b.createLabelCollector=function(){return function(){}};
b.setScale=function(){};b.setCategories=function(){};b.setTitle=function(){};b.isHidden=!0};return l}()});B(e,"parts-more/RadialAxis.js",[e["parts/Axis.js"],e["parts/Tick.js"],e["parts-more/HiddenAxis.js"],e["parts/Utilities.js"]],function(l,b,d,a){var m=a.addEvent,u=a.correctFloat,w=a.defined,e=a.extend,x=a.fireEvent,h=a.merge,t=a.pick,q=a.pInt,z=a.relativeLength,k=a.wrap;a=function(){function a(){}a.init=function(a){var b=l.prototype;a.setOptions=function(c){c=this.options=h(a.constructor.defaultOptions,
this.defaultPolarOptions,c);c.plotBands||(c.plotBands=[]);x(this,"afterSetOptions")};a.getOffset=function(){b.getOffset.call(this);this.chart.axisOffset[this.side]=0};a.getLinePath=function(c,g,f){c=this.pane.center;var p=this.chart,v=t(g,c[2]/2-this.offset);"undefined"===typeof f&&(f=this.horiz?0:this.center&&-this.center[3]/2);f&&(v+=f);this.isCircular||"undefined"!==typeof g?(g=this.chart.renderer.symbols.arc(this.left+c[0],this.top+c[1],v,v,{start:this.startAngleRad,end:this.endAngleRad,open:!0,
innerR:0}),g.xBounds=[this.left+c[0]],g.yBounds=[this.top+c[1]-v]):(g=this.postTranslate(this.angleRad,v),g=["M",this.center[0]+p.plotLeft,this.center[1]+p.plotTop,"L",g.x,g.y]);return g};a.setAxisTranslation=function(){b.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):(this.center[2]-this.center[3])/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)};a.beforeSetTickPositions=
function(){this.autoConnect=this.isCircular&&"undefined"===typeof t(this.userMax,this.options.max)&&u(this.endAngleRad-this.startAngleRad)===u(2*Math.PI);!this.isCircular&&this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)};a.setAxisSize=function(){b.setAxisSize.call(this);if(this.isRadial){this.pane.updateCenter(this);var c=this.center=e([],this.pane.center);if(this.isCircular)this.sector=this.endAngleRad-this.startAngleRad;
else{var g=this.postTranslate(this.angleRad,c[3]/2);c[0]=g.x-this.chart.plotLeft;c[1]=g.y-this.chart.plotTop}this.len=this.width=this.height=(c[2]-c[3])*t(this.sector,1)/2}};a.getPosition=function(c,g){c=this.translate(c);return this.postTranslate(this.isCircular?c:this.angleRad,t(this.isCircular?g:0>c?0:c,this.center[2]/2)-this.offset)};a.postTranslate=function(c,g){var f=this.chart,p=this.center;c=this.startAngleRad+c;return{x:f.plotLeft+p[0]+Math.cos(c)*g,y:f.plotTop+p[1]+Math.sin(c)*g}};a.getPlotBandPath=
function(c,g,f){var p=this.center,v=this.startAngleRad,h=p[2]/2,n=[t(f.outerRadius,"100%"),f.innerRadius,t(f.thickness,10)],a=Math.min(this.offset,0),b=/%$/;var k=this.isCircular;if("polygon"===this.options.gridLineInterpolation)n=this.getPlotLinePath({value:c}).concat(this.getPlotLinePath({value:g,reverse:!0}));else{c=Math.max(c,this.min);g=Math.min(g,this.max);k||(n[0]=this.translate(c),n[1]=this.translate(g));n=n.map(function(f){b.test(f)&&(f=q(f,10)*h/100);return f});if("circle"!==f.shape&&k)c=
v+this.translate(c),g=v+this.translate(g);else{c=-Math.PI/2;g=1.5*Math.PI;var r=!0}n[0]-=a;n[2]-=a;n=this.chart.renderer.symbols.arc(this.left+p[0],this.top+p[1],n[0],n[0],{start:Math.min(c,g),end:Math.max(c,g),innerR:t(n[1],n[0]-n[2]),open:r});k&&(k=(g+c)/2,a=this.left+p[0]+p[2]/2*Math.cos(k),n.xBounds=k>-Math.PI/2&&k<Math.PI/2?[a,this.chart.plotWidth]:[0,a],n.yBounds=[this.top+p[1]+p[2]/2*Math.sin(k)],n.yBounds[0]+=k>-Math.PI&&0>k||k>Math.PI?-10:10)}return n};a.getCrosshairPosition=function(c,g,
f){var p=c.value,v=this.pane.center;if(this.isCircular){if(w(p))c.point&&(a=c.point.shapeArgs||{},a.start&&(p=this.chart.inverted?this.translate(c.point.rectPlotY,!0):c.point.x));else{var a=c.chartX||0;var n=c.chartY||0;p=this.translate(Math.atan2(n-f,a-g)-this.startAngleRad,!0)}c=this.getPosition(p);a=c.x;n=c.y}else w(p)||(a=c.chartX,n=c.chartY),w(a)&&w(n)&&(f=v[1]+this.chart.plotTop,p=this.translate(Math.min(Math.sqrt(Math.pow(a-g,2)+Math.pow(n-f,2)),v[2]/2)-v[3]/2,!0));return[p,a||0,n||0]};a.getPlotLinePath=
function(c){var g=this,f=g.pane.center,p=g.chart,v=p.inverted,a=c.value,n=c.reverse,h=g.getPosition(a),b=g.pane.options.background?g.pane.options.background[0]||g.pane.options.background:{},k=b.innerRadius||"0%",r=b.outerRadius||"100%";b=f[0]+p.plotLeft;var q=f[1]+p.plotTop,d=h.x,t=h.y,A=g.height;h=f[3]/2;var m,u;c.isCrosshair&&(t=this.getCrosshairPosition(c,b,q),a=t[0],d=t[1],t=t[2]);if(g.isCircular){n=Math.sqrt(Math.pow(d-b,2)+Math.pow(t-q,2));k="string"===typeof k?z(k,1):k/n;r="string"===typeof r?
z(r,1):r/n;f&&h&&(f=h/n,k<f&&(k=f),r<f&&(r=f));var l=["M",b+k*(d-b),q-k*(q-t),"L",d-(1-r)*(d-b),t+(1-r)*(q-t)]}else(a=g.translate(a))&&(0>a||a>A)&&(a=0),"circle"===g.options.gridLineInterpolation?l=g.getLinePath(0,a,h):(p[v?"yAxis":"xAxis"].forEach(function(f){f.pane===g.pane&&(m=f)}),l=[],f=m.tickPositions,m.autoConnect&&(f=f.concat([f[0]])),n&&(f=[].concat(f).reverse()),a&&(a+=h),f.forEach(function(f,g){u=m.getPosition(f,a);l.push(g?"L":"M",u.x,u.y)}));return l};a.getTitlePosition=function(){var c=
this.center,g=this.chart,f=this.options.title;return{x:g.plotLeft+c[0]+(f.x||0),y:g.plotTop+c[1]-{high:.5,middle:.25,low:0}[f.align]*c[2]+(f.y||0)}};a.createLabelCollector=function(){var c=this;return function(){if(c.isRadial&&c.tickPositions&&!0!==c.options.labels.allowOverlap)return c.tickPositions.map(function(g){return c.ticks[g]&&c.ticks[g].label}).filter(function(g){return!!g})}}};a.compose=function(b,r){m(b,"init",function(c){var g=this.chart,f=g.inverted,p=g.angular,v=g.polar,C=this.isXAxis,
n=this.coll,H=p&&C,k,r=g.options;c=c.userOptions.pane||0;c=this.pane=g.pane&&g.pane[c];if("colorAxis"===n)this.isRadial=!1;else{if(p){if(H?d.init(this):a.init(this),k=!C)this.defaultPolarOptions=a.defaultRadialGaugeOptions}else v&&(a.init(this),this.defaultPolarOptions=(k=this.horiz)?a.defaultCircularOptions:h("xAxis"===n?b.defaultOptions:b.defaultYAxisOptions,a.defaultRadialOptions),f&&"yAxis"===n&&(this.defaultPolarOptions.stackLabels=b.defaultYAxisOptions.stackLabels));p||v?(this.isRadial=!0,r.chart.zoomType=
null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&g.labelCollectors.push(this.labelCollector)):this.isRadial=!1;c&&k&&(c.axis=this);this.isCircular=k}});m(b,"afterInit",function(){var c=this.chart,g=this.options,f=this.pane,p=f&&f.options;c.angular&&this.isXAxis||!f||!c.angular&&!c.polar||(this.angleRad=(g.angle||0)*Math.PI/180,this.startAngleRad=(p.startAngle-90)*Math.PI/180,this.endAngleRad=(t(p.endAngle,p.startAngle+360)-90)*Math.PI/180,this.offset=
g.offset||0)});m(b,"autoLabelAlign",function(c){this.isRadial&&(c.align=void 0,c.preventDefault())});m(b,"destroy",function(){if(this.chart&&this.chart.labelCollectors){var c=this.labelCollector?this.chart.labelCollectors.indexOf(this.labelCollector):-1;0<=c&&this.chart.labelCollectors.splice(c,1)}});m(r,"afterGetPosition",function(c){this.axis.getPosition&&e(c.pos,this.axis.getPosition(this.pos))});m(r,"afterGetLabelPosition",function(c){var g=this.axis,f=this.label;if(f){var p=f.getBBox(),a=g.options.labels,
h=a.y,n=20,b=a.align,k=(g.translate(this.pos)+g.startAngleRad+Math.PI/2)/Math.PI*180%360,r=Math.round(k),q="end",d=0>r?r+360:r,m=d,A=0,u=0,l=null===a.y?.3*-p.height:0;if(g.isRadial){var w=g.getPosition(this.pos,g.center[2]/2+z(t(a.distance,-25),g.center[2]/2,-g.center[2]/2));"auto"===a.rotation?f.attr({rotation:k}):null===h&&(h=g.chart.renderer.fontMetrics(f.styles&&f.styles.fontSize).b-p.height/2);null===b&&(g.isCircular?(p.width>g.len*g.tickInterval/(g.max-g.min)&&(n=0),b=k>n&&k<180-n?"left":k>
180+n&&k<360-n?"right":"center"):b="center",f.attr({align:b}));if("auto"===b&&2===g.tickPositions.length&&g.isCircular){90<d&&180>d?d=180-d:270<d&&360>=d&&(d=540-d);180<m&&360>=m&&(m=360-m);if(g.pane.options.startAngle===r||g.pane.options.startAngle===r+360||g.pane.options.startAngle===r-360)q="start";b=-90<=r&&90>=r||-360<=r&&-270>=r||270<=r&&360>=r?"start"===q?"right":"left":"start"===q?"left":"right";70<m&&110>m&&(b="center");15>d||180<=d&&195>d?A=.3*p.height:15<=d&&35>=d?A="start"===q?0:.75*p.height:
195<=d&&215>=d?A="start"===q?.75*p.height:0:35<d&&90>=d?A="start"===q?.25*-p.height:p.height:215<d&&270>=d&&(A="start"===q?p.height:.25*-p.height);15>m?u="start"===q?.15*-p.height:.15*p.height:165<m&&180>=m&&(u="start"===q?.15*p.height:.15*-p.height);f.attr({align:b});f.translate(u,A+l)}c.pos.x=w.x+a.x;c.pos.y=w.y+h}}});k(r.prototype,"getMarkPath",function(c,g,f,p,a,h,n){var v=this.axis;v.isRadial?(c=v.getPosition(this.pos,v.center[2]/2+p),g=["M",g,f,"L",c.x,c.y]):g=c.call(this,g,f,p,a,h,n);return g})};
a.defaultCircularOptions={gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0};a.defaultRadialGaugeOptions={labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2};a.defaultRadialOptions={gridLineInterpolation:"circle",gridLineWidth:1,labels:{align:"right",
x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}};return a}();a.compose(l,b);return a});B(e,"parts-more/AreaRangeSeries.js",[e["parts/Globals.js"],e["parts/Point.js"],e["parts/Utilities.js"]],function(l,b,d){var a=d.defined,m=d.extend,u=d.isArray,w=d.isNumber,e=d.pick;d=d.seriesType;var x=l.seriesTypes,h=l.Series.prototype,t=b.prototype;d("arearange","area",{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},
trackByArea:!0,dataLabels:{align:null,verticalAlign:null,xLow:0,xHigh:0,yLow:0,yHigh:0}},{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,toYData:function(a){return[a.low,a.high]},highToXY:function(a){var h=this.chart,b=this.xAxis.postTranslate(a.rectPlotX,this.yAxis.len-a.plotHigh);a.plotHighX=b.x-h.plotLeft;a.plotHigh=b.y-h.plotTop;a.plotLowX=a.plotX},translate:function(){var a=this,h=a.yAxis,b=!!a.modifyValue;x.area.prototype.translate.apply(a);a.points.forEach(function(k){var d=
k.high,r=k.plotY;k.isNull?k.plotY=null:(k.plotLow=r,k.plotHigh=h.translate(b?a.modifyValue(d,k):d,0,1,0,1),b&&(k.yBottom=k.plotHigh))});this.chart.polar&&this.points.forEach(function(h){a.highToXY(h);h.tooltipPos=[(h.plotHighX+h.plotLowX)/2,(h.plotHigh+h.plotLow)/2]})},getGraphPath:function(a){var h=[],b=[],d,t=x.area.prototype.getGraphPath;var r=this.options;var c=this.chart.polar&&!1!==r.connectEnds,g=r.connectNulls,f=r.step;a=a||this.points;for(d=a.length;d--;){var p=a[d];p.isNull||c||g||a[d+1]&&
!a[d+1].isNull||b.push({plotX:p.plotX,plotY:p.plotY,doCurve:!1});var v={polarPlotY:p.polarPlotY,rectPlotX:p.rectPlotX,yBottom:p.yBottom,plotX:e(p.plotHighX,p.plotX),plotY:p.plotHigh,isNull:p.isNull};b.push(v);h.push(v);p.isNull||c||g||a[d-1]&&!a[d-1].isNull||b.push({plotX:p.plotX,plotY:p.plotY,doCurve:!1})}a=t.call(this,a);f&&(!0===f&&(f="left"),r.step={left:"right",center:"center",right:"left"}[f]);h=t.call(this,h);b=t.call(this,b);r.step=f;r=[].concat(a,h);this.chart.polar||"M"!==b[0]||(b[0]="L");
this.graphPath=r;this.areaPath=a.concat(b);r.isArea=!0;r.xMap=a.xMap;this.areaPath.xMap=a.xMap;return r},drawDataLabels:function(){var a=this.points,b=a.length,k,d=[],t=this.options.dataLabels,r,c=this.chart.inverted;if(u(t))if(1<t.length){var g=t[0];var f=t[1]}else g=t[0],f={enabled:!1};else g=m({},t),g.x=t.xHigh,g.y=t.yHigh,f=m({},t),f.x=t.xLow,f.y=t.yLow;if(g.enabled||this._hasPointLabels){for(k=b;k--;)if(r=a[k]){var p=g.inside?r.plotHigh<r.plotLow:r.plotHigh>r.plotLow;r.y=r.high;r._plotY=r.plotY;
r.plotY=r.plotHigh;d[k]=r.dataLabel;r.dataLabel=r.dataLabelUpper;r.below=p;c?g.align||(g.align=p?"right":"left"):g.verticalAlign||(g.verticalAlign=p?"top":"bottom")}this.options.dataLabels=g;h.drawDataLabels&&h.drawDataLabels.apply(this,arguments);for(k=b;k--;)if(r=a[k])r.dataLabelUpper=r.dataLabel,r.dataLabel=d[k],delete r.dataLabels,r.y=r.low,r.plotY=r._plotY}if(f.enabled||this._hasPointLabels){for(k=b;k--;)if(r=a[k])p=f.inside?r.plotHigh<r.plotLow:r.plotHigh>r.plotLow,r.below=!p,c?f.align||(f.align=
p?"left":"right"):f.verticalAlign||(f.verticalAlign=p?"bottom":"top");this.options.dataLabels=f;h.drawDataLabels&&h.drawDataLabels.apply(this,arguments)}if(g.enabled)for(k=b;k--;)if(r=a[k])r.dataLabels=[r.dataLabelUpper,r.dataLabel].filter(function(f){return!!f});this.options.dataLabels=t},alignDataLabel:function(){x.column.prototype.alignDataLabel.apply(this,arguments)},drawPoints:function(){var b=this.points.length,d;h.drawPoints.apply(this,arguments);for(d=0;d<b;){var k=this.points[d];k.origProps=
{plotY:k.plotY,plotX:k.plotX,isInside:k.isInside,negative:k.negative,zone:k.zone,y:k.y};k.lowerGraphic=k.graphic;k.graphic=k.upperGraphic;k.plotY=k.plotHigh;a(k.plotHighX)&&(k.plotX=k.plotHighX);k.y=k.high;k.negative=k.high<(this.options.threshold||0);k.zone=this.zones.length&&k.getZone();this.chart.polar||(k.isInside=k.isTopInside="undefined"!==typeof k.plotY&&0<=k.plotY&&k.plotY<=this.yAxis.len&&0<=k.plotX&&k.plotX<=this.xAxis.len);d++}h.drawPoints.apply(this,arguments);for(d=0;d<b;)k=this.points[d],
k.upperGraphic=k.graphic,k.graphic=k.lowerGraphic,m(k,k.origProps),delete k.origProps,d++},setStackedPoints:l.noop},{setState:function(){var h=this.state,b=this.series,d=b.chart.polar;a(this.plotHigh)||(this.plotHigh=b.yAxis.toPixels(this.high,!0));a(this.plotLow)||(this.plotLow=this.plotY=b.yAxis.toPixels(this.low,!0));b.stateMarkerGraphic&&(b.lowerStateMarkerGraphic=b.stateMarkerGraphic,b.stateMarkerGraphic=b.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;d&&(this.plotX=
this.plotHighX);t.setState.apply(this,arguments);this.state=h;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;d&&(this.plotX=this.plotLowX);b.stateMarkerGraphic&&(b.upperStateMarkerGraphic=b.stateMarkerGraphic,b.stateMarkerGraphic=b.lowerStateMarkerGraphic,b.lowerStateMarkerGraphic=void 0);t.setState.apply(this,arguments)},haloPath:function(){var a=this.series.chart.polar,h=[];this.plotY=this.plotLow;a&&(this.plotX=this.plotLowX);this.isInside&&(h=t.haloPath.apply(this,arguments));this.plotY=
this.plotHigh;a&&(this.plotX=this.plotHighX);this.isTopInside&&(h=h.concat(t.haloPath.apply(this,arguments)));return h},destroyElements:function(){["lowerGraphic","upperGraphic"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this);this.graphic=null;return t.destroyElements.apply(this,arguments)},isValid:function(){return w(this.low)&&w(this.high)}});""});B(e,"parts-more/AreaSplineRangeSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(l,b){b=b.seriesType;b("areasplinerange",
"arearange",null,{getPointSpline:l.seriesTypes.spline.prototype.getPointSpline});""});B(e,"parts-more/ColumnRangeSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(l,b){var d=b.clamp,a=b.merge,m=b.pick;b=b.seriesType;var u=l.defaultPlotOptions,w=l.noop,e=l.seriesTypes.column.prototype;b("columnrange","arearange",a(u.column,u.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{translate:function(){var a=this,h=a.yAxis,b=a.xAxis,u=b.startAngleRad,l,k=a.chart,w=a.xAxis.isRadial,
A=Math.max(k.chartWidth,k.chartHeight)+999,r;e.translate.apply(a);a.points.forEach(function(c){var g=c.shapeArgs,f=a.options.minPointLength;c.plotHigh=r=d(h.translate(c.high,0,1,0,1),-A,A);c.plotLow=d(c.plotY,-A,A);var p=r;var v=m(c.rectPlotY,c.plotY)-r;Math.abs(v)<f?(f-=v,v+=f,p-=f/2):0>v&&(v*=-1,p-=v);w?(l=c.barX+u,c.shapeType="arc",c.shapeArgs=a.polarArc(p+v,p,l,l+c.pointWidth)):(g.height=v,g.y=p,c.tooltipPos=k.inverted?[h.len+h.pos-k.plotLeft-p-v/2,b.len+b.pos-k.plotTop-g.x-g.width/2,v]:[b.left-
k.plotLeft+g.x+g.width/2,h.pos-k.plotTop+p+v/2,v])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],drawGraph:w,getSymbol:w,crispCol:function(){return e.crispCol.apply(this,arguments)},drawPoints:function(){return e.drawPoints.apply(this,arguments)},drawTracker:function(){return e.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return e.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return e.pointAttribs.apply(this,arguments)},animate:function(){return e.animate.apply(this,
arguments)},polarArc:function(){return e.polarArc.apply(this,arguments)},translate3dPoints:function(){return e.translate3dPoints.apply(this,arguments)},translate3dShapes:function(){return e.translate3dShapes.apply(this,arguments)}},{setState:e.pointClass.prototype.setState});""});B(e,"parts-more/ColumnPyramidSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(l,b){var d=b.clamp,a=b.pick;b=b.seriesType;var m=l.seriesTypes.column.prototype;b("columnpyramid","column",{},{translate:function(){var b=
this,l=b.chart,e=b.options,x=b.dense=2>b.closestPointRange*b.xAxis.transA;x=b.borderWidth=a(e.borderWidth,x?0:1);var h=b.yAxis,t=e.threshold,q=b.translatedThreshold=h.getThreshold(t),z=a(e.minPointLength,5),k=b.getColumnMetrics(),y=k.width,A=b.barW=Math.max(y,1+2*x),r=b.pointXOffset=k.offset;l.inverted&&(q-=.5);e.pointPadding&&(A=Math.ceil(A));m.translate.apply(b);b.points.forEach(function(c){var g=a(c.yBottom,q),f=999+Math.abs(g),p=d(c.plotY,-f,h.len+f);f=c.plotX+r;var v=A/2,C=Math.min(p,g);g=Math.max(p,
g)-C;var n;c.barX=f;c.pointWidth=y;c.tooltipPos=l.inverted?[h.len+h.pos-l.plotLeft-p,b.xAxis.len-f-v,g]:[f+v,p+h.pos-l.plotTop,g];p=t+(c.total||c.y);"percent"===e.stacking&&(p=t+(0>c.y)?-100:100);p=h.toPixels(p,!0);var k=(n=l.plotHeight-p-(l.plotHeight-q))?v*(C-p)/n:0;var m=n?v*(C+g-p)/n:0;n=f-k+v;k=f+k+v;var I=f+m+v;m=f-m+v;var u=C-z;var G=C+g;0>c.y&&(u=C,G=C+g+z);l.inverted&&(I=l.plotWidth-C,n=p-(l.plotWidth-q),k=v*(p-I)/n,m=v*(p-(I-g))/n,n=f+v+k,k=n-2*k,I=f-m+v,m=f+m+v,u=C,G=C+g-z,0>c.y&&(G=C+
g+z));c.shapeType="path";c.shapeArgs={x:n,y:u,width:k-n,height:g,d:["M",n,u,"L",k,u,I,G,m,G,"Z"]}})}});""});B(e,"parts-more/GaugeSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(l,b){var d=b.clamp,a=b.isNumber,m=b.merge,u=b.pick,e=b.pInt;b=b.seriesType;var D=l.Series,x=l.TrackerMixin;b("gauge","line",{dataLabels:{borderColor:"#cccccc",borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},
{angular:!0,directTouch:!0,drawGraph:l.noop,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var b=this.yAxis,t=this.options,l=b.center;this.generatePoints();this.points.forEach(function(h){var k=m(t.dial,h.dial),q=e(u(k.radius,"80%"))*l[2]/200,A=e(u(k.baseLength,"70%"))*q/100,r=e(u(k.rearLength,"10%"))*q/100,c=k.baseWidth||3,g=k.topWidth||1,f=t.overshoot,p=b.startAngleRad+b.translate(h.y,null,null,null,!0);if(a(f)||!1===t.wrap)f=a(f)?f/180*
Math.PI:0,p=d(p,b.startAngleRad-f,b.endAngleRad+f);p=180*p/Math.PI;h.shapeType="path";h.shapeArgs={d:k.path||["M",-r,-c/2,"L",A,-c/2,q,-g/2,q,g/2,A,c/2,-r,c/2,"z"],translateX:l[0],translateY:l[1],rotation:p};h.plotX=l[0];h.plotY=l[1]})},drawPoints:function(){var a=this,b=a.chart,d=a.yAxis.center,l=a.pivot,k=a.options,e=k.pivot,A=b.renderer;a.points.forEach(function(h){var c=h.graphic,g=h.shapeArgs,f=g.d,p=m(k.dial,h.dial);c?(c.animate(g),g.d=f):h.graphic=A[h.shapeType](g).attr({rotation:g.rotation,
zIndex:1}).addClass("highcharts-dial").add(a.group);if(!b.styledMode)h.graphic[c?"animate":"attr"]({stroke:p.borderColor||"none","stroke-width":p.borderWidth||0,fill:p.backgroundColor||"#000000"})});l?l.animate({translateX:d[0],translateY:d[1]}):(a.pivot=A.circle(0,0,u(e.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(d[0],d[1]).add(a.group),b.styledMode||a.pivot.attr({"stroke-width":e.borderWidth||0,stroke:e.borderColor||"#cccccc",fill:e.backgroundColor||"#000000"}))},animate:function(a){var b=
this;a||b.points.forEach(function(a){var h=a.graphic;h&&(h.attr({rotation:180*b.yAxis.startAngleRad/Math.PI}),h.animate({rotation:a.shapeArgs.rotation},b.options.animation))})},render:function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);D.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(a,b){D.prototype.setData.call(this,a,!1);this.processData();this.generatePoints();u(b,!0)&&this.chart.redraw()},
hasData:function(){return!!this.points.length},drawTracker:x&&x.drawTrackerPoint},{setState:function(a){this.state=a}});""});B(e,"parts-more/BoxPlotSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(l,b){var d=b.pick;b=b.seriesType;var a=l.noop,m=l.seriesTypes;b("boxplot","column",{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},
whiskerLength:"50%",fillColor:"#ffffff",lineWidth:1,medianWidth:2,whiskerWidth:2},{pointArrayMap:["low","q1","median","q3","high"],toYData:function(a){return[a.low,a.q1,a.median,a.q3,a.high]},pointValKey:"high",pointAttribs:function(){return{}},drawDataLabels:a,translate:function(){var a=this.yAxis,b=this.pointArrayMap;m.column.prototype.translate.apply(this);this.points.forEach(function(d){b.forEach(function(b){null!==d[b]&&(d[b+"Plot"]=a.translate(d[b],0,1,0,1))});d.plotHigh=d.highPlot})},drawPoints:function(){var a=
this,b=a.options,m=a.chart,l=m.renderer,h,t,e,z,k,y,A=0,r,c,g,f,p=!1!==a.doQuartiles,v,C=a.options.whiskerLength;a.points.forEach(function(n){var H=n.graphic,K=H?"animate":"attr",I=n.shapeArgs,q={},G={},u={},E={},J=n.color||a.color;"undefined"!==typeof n.plotY&&(r=I.width,c=Math.floor(I.x),g=c+r,f=Math.round(r/2),h=Math.floor(p?n.q1Plot:n.lowPlot),t=Math.floor(p?n.q3Plot:n.lowPlot),e=Math.floor(n.highPlot),z=Math.floor(n.lowPlot),H||(n.graphic=H=l.g("point").add(a.group),n.stem=l.path().addClass("highcharts-boxplot-stem").add(H),
C&&(n.whiskers=l.path().addClass("highcharts-boxplot-whisker").add(H)),p&&(n.box=l.path(void 0).addClass("highcharts-boxplot-box").add(H)),n.medianShape=l.path(void 0).addClass("highcharts-boxplot-median").add(H)),m.styledMode||(G.stroke=n.stemColor||b.stemColor||J,G["stroke-width"]=d(n.stemWidth,b.stemWidth,b.lineWidth),G.dashstyle=n.stemDashStyle||b.stemDashStyle,n.stem.attr(G),C&&(u.stroke=n.whiskerColor||b.whiskerColor||J,u["stroke-width"]=d(n.whiskerWidth,b.whiskerWidth,b.lineWidth),n.whiskers.attr(u)),
p&&(q.fill=n.fillColor||b.fillColor||J,q.stroke=b.lineColor||J,q["stroke-width"]=b.lineWidth||0,n.box.attr(q)),E.stroke=n.medianColor||b.medianColor||J,E["stroke-width"]=d(n.medianWidth,b.medianWidth,b.lineWidth),n.medianShape.attr(E)),y=n.stem.strokeWidth()%2/2,A=c+f+y,n.stem[K]({d:["M",A,t,"L",A,e,"M",A,h,"L",A,z]}),p&&(y=n.box.strokeWidth()%2/2,h=Math.floor(h)+y,t=Math.floor(t)+y,c+=y,g+=y,n.box[K]({d:["M",c,t,"L",c,h,"L",g,h,"L",g,t,"L",c,t,"z"]})),C&&(y=n.whiskers.strokeWidth()%2/2,e+=y,z+=y,
v=/%$/.test(C)?f*parseFloat(C)/100:C/2,n.whiskers[K]({d:["M",A-v,e,"L",A+v,e,"M",A-v,z,"L",A+v,z]})),k=Math.round(n.medianPlot),y=n.medianShape.strokeWidth()%2/2,k+=y,n.medianShape[K]({d:["M",c,k,"L",g,k]}))})},setStackedPoints:a});""});B(e,"parts-more/ErrorBarSeries.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(l,b){b=b.seriesType;var d=l.noop,a=l.seriesTypes;b("errorbar","boxplot",{color:"#000000",grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},
whiskerWidth:null},{type:"errorbar",pointArrayMap:["low","high"],toYData:function(a){return[a.low,a.high]},pointValKey:"high",doQuartiles:!1,drawDataLabels:a.arearange?function(){var b=this.pointValKey;a.arearange.prototype.drawDataLabels.call(this);this.data.forEach(function(a){a.y=a[b]})}:d,getColumnMetrics:function(){return this.linkedParent&&this.linkedParent.columnMetrics||a.column.prototype.getColumnMetrics.call(this)}});""});B(e,"parts-more/WaterfallSeries.js",[e["parts/Globals.js"],e["parts/Point.js"],
e["parts/Utilities.js"],e["parts/Stacking.js"]],function(l,b,d,a){var m=d.addEvent,e=d.arrayMax,w=d.arrayMin,D=d.correctFloat,x=d.isNumber,h=d.objectEach,t=d.pick;d=d.seriesType;var q=l.Axis,z=l.Chart,k=l.Series,y=l.seriesTypes;m(q,"afterInit",function(){this.isXAxis||(this.waterfallStacks={changed:!1})});m(q,"afterBuildStacks",function(){this.waterfallStacks.changed=!1;delete this.waterfallStacks.alreadyChanged});m(z,"beforeRedraw",function(){for(var a=this.axes,b=this.series,c=b.length;c--;)b[c].options.stacking&&
(a.forEach(function(g){g.isXAxis||(g.waterfallStacks.changed=!0)}),c=0)});m(q,"afterRender",function(){var a=this.options.stackLabels;a&&a.enabled&&this.waterfallStacks&&this.renderWaterfallStackTotals()});q.prototype.renderWaterfallStackTotals=function(){var b=this.waterfallStacks,d=this.stackTotalGroup,c=new a(this,this.options.stackLabels,!1,0,void 0);this.dummyStackItem=c;h(b,function(g){h(g,function(f){c.total=f.stackTotal;f.label&&(c.label=f.label);a.prototype.render.call(c,d);f.label=c.label;
delete c.label})});c.total=null};d("waterfall","column",{dataLabels:{inside:!0},lineWidth:1,lineColor:"#333333",dashStyle:"Dot",borderColor:"#333333",states:{hover:{lineWidthPlus:0}}},{pointValKey:"y",showLine:!0,generatePoints:function(){var a;y.column.prototype.generatePoints.apply(this);var b=0;for(a=this.points.length;b<a;b++){var c=this.points[b];var g=this.processedYData[b];if(c.isIntermediateSum||c.isSum)c.y=D(g)}},translate:function(){var a=this.options,b=this.yAxis,c,g=t(a.minPointLength,
5),f=g/2,p=a.threshold,h=a.stacking,C=b.waterfallStacks[this.stackKey];y.column.prototype.translate.apply(this);var n=c=p;var d=this.points;var k=0;for(a=d.length;k<a;k++){var m=d[k];var l=this.processedYData[k];var e=m.shapeArgs;var q=[0,l];var E=m.y;if(h){if(C){q=C[k];if("overlap"===h){var u=q.stackState[q.stateIndex--];u=0<=E?u:u-E;Object.hasOwnProperty.call(q,"absolutePos")&&delete q.absolutePos;Object.hasOwnProperty.call(q,"absoluteNeg")&&delete q.absoluteNeg}else 0<=E?(u=q.threshold+q.posTotal,
q.posTotal-=E):(u=q.threshold+q.negTotal,q.negTotal-=E,u-=E),!q.posTotal&&Object.hasOwnProperty.call(q,"absolutePos")&&(q.posTotal=q.absolutePos,delete q.absolutePos),!q.negTotal&&Object.hasOwnProperty.call(q,"absoluteNeg")&&(q.negTotal=q.absoluteNeg,delete q.absoluteNeg);m.isSum||(q.connectorThreshold=q.threshold+q.stackTotal);b.reversed?(l=0<=E?u-E:u+E,E=u):(l=u,E=u-E);m.below=l<=t(p,0);e.y=b.translate(l,0,1,0,1);e.height=Math.abs(e.y-b.translate(E,0,1,0,1))}if(E=b.dummyStackItem)E.x=k,E.label=
C[k].label,E.setOffset(this.pointXOffset||0,this.barW||0,this.stackedYNeg[k],this.stackedYPos[k])}else u=Math.max(n,n+E)+q[0],e.y=b.translate(u,0,1,0,1),m.isSum?(e.y=b.translate(q[1],0,1,0,1),e.height=Math.min(b.translate(q[0],0,1,0,1),b.len)-e.y):m.isIntermediateSum?(0<=E?(l=q[1]+c,E=c):(l=c,E=q[1]+c),b.reversed&&(l^=E,E^=l,l^=E),e.y=b.translate(l,0,1,0,1),e.height=Math.abs(e.y-Math.min(b.translate(E,0,1,0,1),b.len)),c+=q[1]):(e.height=0<l?b.translate(n,0,1,0,1)-e.y:b.translate(n,0,1,0,1)-b.translate(n-
l,0,1,0,1),n+=l,m.below=n<t(p,0)),0>e.height&&(e.y+=e.height,e.height*=-1);m.plotY=e.y=Math.round(e.y)-this.borderWidth%2/2;e.height=Math.max(Math.round(e.height),.001);m.yBottom=e.y+e.height;e.height<=g&&!m.isNull?(e.height=g,e.y-=f,m.plotY=e.y,m.minPointLengthOffset=0>m.y?-f:f):(m.isNull&&(e.width=0),m.minPointLengthOffset=0);e=m.plotY+(m.negative?e.height:0);this.chart.inverted?m.tooltipPos[0]=b.len-e:m.tooltipPos[1]=e}},processData:function(a){var b=this.options,c=this.yData,g=b.data,f=c.length,
p=b.threshold||0,h,C,n,d,m;for(m=C=h=n=d=0;m<f;m++){var e=c[m];var l=g&&g[m]?g[m]:{};"sum"===e||l.isSum?c[m]=D(C):"intermediateSum"===e||l.isIntermediateSum?(c[m]=D(h),h=0):(C+=e,h+=e);n=Math.min(C,n);d=Math.max(C,d)}k.prototype.processData.call(this,a);b.stacking||(this.dataMin=n+p,this.dataMax=d)},toYData:function(a){return a.isSum?"sum":a.isIntermediateSum?"intermediateSum":a.y},updateParallelArrays:function(a,b){k.prototype.updateParallelArrays.call(this,a,b);if("sum"===this.yData[0]||"intermediateSum"===
this.yData[0])this.yData[0]=null},pointAttribs:function(a,b){var c=this.options.upColor;c&&!a.options.color&&(a.color=0<a.y?c:null);a=y.column.prototype.pointAttribs.call(this,a,b);delete a.dashstyle;return a},getGraphPath:function(){return["M",0,0]},getCrispPath:function(){var a=this.data,b=this.yAxis,c=a.length,g=Math.round(this.graph.strokeWidth())%2/2,f=Math.round(this.borderWidth)%2/2,p=this.xAxis.reversed,h=this.yAxis.reversed,C=this.options.stacking,n=[],d;for(d=1;d<c;d++){var k=a[d].shapeArgs;
var m=a[d-1];var e=a[d-1].shapeArgs;var l=b.waterfallStacks[this.stackKey];var t=0<m.y?-e.height:0;if(l){l=l[d-1];C?(l=l.connectorThreshold,t=Math.round(b.translate(l,0,1,0,1)+(h?t:0))-g):t=e.y+m.minPointLengthOffset+f-g;var q=["M",e.x+(p?0:e.width),t,"L",k.x+(p?k.width:0),t]}if(!C&&q&&0>m.y&&!h||0<m.y&&h)q[2]+=e.height,q[5]+=e.height;n=n.concat(q)}return n},drawGraph:function(){k.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})},setStackedPoints:function(){function a(f,a,g,
c){if(x)for(g;g<x;g++)u.stackState[g]+=c;else u.stackState[0]=f,x=u.stackState.length;u.stackState.push(u.stackState[x-1]+a)}var b=this.options,c=this.yAxis.waterfallStacks,g=b.threshold,f=g||0,p=f,h=this.stackKey,C=this.xData,n=C.length,d,k,m;this.yAxis.usePercentage=!1;var e=k=m=f;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var l=c.changed;(d=c.alreadyChanged)&&0>d.indexOf(h)&&(l=!0);c[h]||(c[h]={});d=c[h];for(var t=0;t<n;t++){var q=C[t];if(!d[q]||l)d[q]={negTotal:0,posTotal:0,
stackTotal:0,threshold:0,stateIndex:0,stackState:[],label:l&&d[q]?d[q].label:void 0};var u=d[q];var z=this.yData[t];0<=z?u.posTotal+=z:u.negTotal+=z;var w=b.data[t];q=u.absolutePos=u.posTotal;var y=u.absoluteNeg=u.negTotal;u.stackTotal=q+y;var x=u.stackState.length;w&&w.isIntermediateSum?(a(m,k,0,m),m=k,k=g,f^=p,p^=f,f^=p):w&&w.isSum?(a(g,e,x),f=g):(a(f,z,0,e),w&&(e+=z,k+=z));u.stateIndex++;u.threshold=f;f+=u.stackTotal}c.changed=!1;c.alreadyChanged||(c.alreadyChanged=[]);c.alreadyChanged.push(h)}},
getExtremes:function(){var a=this.options.stacking;if(a){var b=this.yAxis;b=b.waterfallStacks;var c=this.stackedYNeg=[];var g=this.stackedYPos=[];"overlap"===a?h(b[this.stackKey],function(f){c.push(w(f.stackState));g.push(e(f.stackState))}):h(b[this.stackKey],function(f){c.push(f.negTotal+f.threshold);g.push(f.posTotal+f.threshold)});return{dataMin:w(c),dataMax:e(g)}}return{dataMin:this.dataMin,dataMax:this.dataMax}}},{getClassName:function(){var a=b.prototype.getClassName.call(this);this.isSum?a+=
" highcharts-sum":this.isIntermediateSum&&(a+=" highcharts-intermediate-sum");return a},isValid:function(){return x(this.y)||this.isSum||!!this.isIntermediateSum}});""});B(e,"parts-more/PolygonSeries.js",[e["parts/Globals.js"],e["mixins/legend-symbol.js"],e["parts/Utilities.js"]],function(e,b,d){d=d.seriesType;var a=e.Series,m=e.seriesTypes;d("polygon","scatter",{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0},{type:"polygon",
getGraphPath:function(){for(var b=a.prototype.getGraphPath.call(this),d=b.length+1;d--;)(d===b.length||"M"===b[d])&&0<d&&b.splice(d,0,"z");return this.areaPath=b},drawGraph:function(){this.options.fillColor=this.color;m.area.prototype.drawGraph.call(this)},drawLegendSymbol:b.drawRectangle,drawTracker:a.prototype.drawTracker,setStackedPoints:e.noop});""});B(e,"parts-more/BubbleLegend.js",[e["parts/Globals.js"],e["parts/Color.js"],e["parts/Legend.js"],e["parts/Utilities.js"]],function(e,b,d,a){"";var m=
b.parse;b=a.addEvent;var l=a.arrayMax,w=a.arrayMin,D=a.isNumber,x=a.merge,h=a.objectEach,t=a.pick,q=a.stableSort,z=a.wrap,k=e.Series,y=e.Chart,A=e.noop,r=e.setOptions;r({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,
ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});r=function(){function b(a,f){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=A;this.init(a,f)}b.prototype.init=function(a,f){this.options=a;this.visible=!0;this.chart=f.chart;
this.legend=f};b.prototype.addToLegend=function(a){a.splice(this.options.legendIndex,0,this)};b.prototype.drawLegendSymbol=function(a){var f=this.chart,b=this.options,g=t(a.options.itemDistance,20),c=b.ranges;var h=b.connectorDistance;this.fontMetrics=f.renderer.fontMetrics(b.labels.style.fontSize.toString()+"px");c&&c.length&&D(c[0].value)?(q(c,function(f,a){return a.value-f.value}),this.ranges=c,this.setOptions(),this.render(),f=this.getMaxLabelSize(),c=this.ranges[0].radius,a=2*c,h=h-c+f.width,
h=0<h?h:0,this.maxLabel=f,this.movementX="left"===b.labels.align?h:0,this.legendItemWidth=a+h+g,this.legendItemHeight=a+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0};b.prototype.setOptions=function(){var a=this.ranges,f=this.options,b=this.chart.series[f.seriesIndex],c=this.legend.baseline,h={"z-index":f.zIndex,"stroke-width":f.borderWidth},n={"z-index":f.zIndex,"stroke-width":f.connectorWidth},d=this.getLabelStyles(),k=b.options.marker.fillOpacity,e=this.chart.styledMode;a.forEach(function(g,
p){e||(h.stroke=t(g.borderColor,f.borderColor,b.color),h.fill=t(g.color,f.color,1!==k?m(b.color).setOpacity(k).get("rgba"):b.color),n.stroke=t(g.connectorColor,f.connectorColor,b.color));a[p].radius=this.getRangeRadius(g.value);a[p]=x(a[p],{center:a[0].radius-a[p].radius+c});e||x(!0,a[p],{bubbleStyle:x(!1,h),connectorStyle:x(!1,n),labelStyle:d})},this)};b.prototype.getLabelStyles=function(){var a=this.options,f={},b="left"===a.labels.align,c=this.legend.options.rtl;h(a.labels.style,function(a,b){"color"!==
b&&"fontSize"!==b&&"z-index"!==b&&(f[b]=a)});return x(!1,f,{"font-size":a.labels.style.fontSize,fill:t(a.labels.style.color,"#000000"),"z-index":a.zIndex,align:c||b?"right":"left"})};b.prototype.getRangeRadius=function(a){var f=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,f.ranges[f.ranges.length-1].value,f.ranges[0].value,f.minSize,f.maxSize,a)};b.prototype.render=function(){var a=this.chart.renderer,f=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],
bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(a){a.value>=f&&this.renderRange(a)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};b.prototype.renderRange=function(a){var f=this.options,b=f.labels,c=this.chart.renderer,g=this.symbols,h=g.labels,d=a.center,k=Math.abs(a.radius),m=f.connectorDistance,
e=b.align,t=b.style.fontSize;m=this.legend.options.rtl||"left"===e?-m:m;b=f.connectorWidth;var l=this.ranges[0].radius,q=d-k-f.borderWidth/2+b/2;t=t/2-(this.fontMetrics.h-t)/2;var r=c.styledMode;"center"===e&&(m=0,f.connectorDistance=0,a.labelStyle.align="center");e=q+f.labels.y;var u=l+m+f.labels.x;g.bubbleItems.push(c.circle(l,d+((q%1?1:.5)-(b%2?0:.5)),k).attr(r?{}:a.bubbleStyle).addClass((r?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(f.className||"")).add(this.legendSymbol));
g.connectors.push(c.path(c.crispLine(["M",l,q,"L",l+m,q],f.connectorWidth)).attr(r?{}:a.connectorStyle).addClass((r?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(f.connectorClassName||"")).add(this.legendSymbol));a=c.text(this.formatLabel(a),u,e+t).attr(r?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+(f.labels.className||"")).add(this.legendSymbol);h.push(a);a.placed=!0;a.alignAttr={x:u,y:e+t}};b.prototype.getMaxLabelSize=function(){var a,
f;this.symbols.labels.forEach(function(b){f=b.getBBox(!0);a=a?f.width>a.width?f:a:f});return a||{}};b.prototype.formatLabel=function(b){var f=this.options,c=f.labels.formatter;f=f.labels.format;var g=this.chart.numberFormatter;return f?a.format(f,b):c?c.call(b):g(b.value,1)};b.prototype.hideOverlappingLabels=function(){var a=this.chart,f=this.symbols;!this.options.labels.allowOverlap&&f&&(a.hideOverlappingLabels(f.labels),f.labels.forEach(function(a,b){a.newOpacity?a.newOpacity!==a.oldOpacity&&f.connectors[b].show():
f.connectors[b].hide()}))};b.prototype.getRanges=function(){var a=this.legend.bubbleLegend,f=a.options.ranges,b,c=Number.MAX_VALUE,h=-Number.MAX_VALUE;a.chart.series.forEach(function(f){f.isBubble&&!f.ignoreSeries&&(b=f.zData.filter(D),b.length&&(c=t(f.options.zMin,Math.min(c,Math.max(w(b),!1===f.options.displayNegative?f.options.zThreshold:-Number.MAX_VALUE))),h=t(f.options.zMax,Math.max(h,l(b)))))});var n=c===h?[{value:h}]:[{value:c},{value:(c+h)/2},{value:h,autoRanges:!0}];f.length&&f[0].radius&&
n.reverse();n.forEach(function(a,b){f&&f[b]&&(n[b]=x(!1,f[b],a))});return n};b.prototype.predictBubbleSizes=function(){var a=this.chart,f=this.fontMetrics,b=a.legend.options,c="horizontal"===b.layout,h=c?a.legend.lastLineHeight:0,n=a.plotSizeX,d=a.plotSizeY,k=a.series[this.options.seriesIndex];a=Math.ceil(k.minPxSize);var m=Math.ceil(k.maxPxSize);k=k.options.maxSize;var e=Math.min(d,n);if(b.floating||!/%$/.test(k))f=m;else if(k=parseFloat(k),f=(e+h-f.h/2)*k/100/(k/100+1),c&&d-f>=n||!c&&n-f>=d)f=m;
return[a,Math.ceil(f)]};b.prototype.updateRanges=function(a,f){var b=this.legend.options.bubbleLegend;b.minSize=a;b.maxSize=f;b.ranges=this.getRanges()};b.prototype.correctSizes=function(){var a=this.legend,f=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(f.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,f.maxPxSize),a.render())};return b}();b(d,"afterGetAllItems",function(a){var b=this.bubbleLegend,f=this.options,c=f.bubbleLegend,h=this.chart.getVisibleBubbleSeriesIndex();
b&&b.ranges&&b.ranges.length&&(c.ranges.length&&(c.autoRanges=!!c.ranges[0].autoRanges),this.destroyItem(b));0<=h&&f.enabled&&c.enabled&&(c.seriesIndex=h,this.bubbleLegend=new e.BubbleLegend(c,this),this.bubbleLegend.addToLegend(a.allItems))});y.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=this.series,b=0;b<a.length;){if(a[b]&&a[b].isBubble&&a[b].visible&&a[b].zData.length)return b;b++}return-1};d.prototype.getLinesHeights=function(){var a=this.allItems,b=[],f=a.length,h,d=0;for(h=0;h<
f;h++)if(a[h].legendItemHeight&&(a[h].itemHeight=a[h].legendItemHeight),a[h]===a[f-1]||a[h+1]&&a[h]._legendItemPos[1]!==a[h+1]._legendItemPos[1]){b.push({height:0});var k=b[b.length-1];for(d;d<=h;d++)a[d].itemHeight>k.height&&(k.height=a[d].itemHeight);k.step=h}return b};d.prototype.retranslateItems=function(a){var b,f,c,h=this.options.rtl,d=0;this.allItems.forEach(function(g,p){b=g.legendGroup.translateX;f=g._legendItemPos[1];if((c=g.movementX)||h&&g.ranges)c=h?b-g.options.maxSize/2:b+c,g.legendGroup.attr({translateX:c});
p>a[d].step&&d++;g.legendGroup.attr({translateY:Math.round(f+a[d].height/2)});g._legendItemPos[1]=f+a[d].height/2})};b(k,"legendItemClick",function(){var a=this.chart,b=this.visible,f=this.chart.legend;f&&f.bubbleLegend&&(this.visible=!b,this.ignoreSeries=b,a=0<=a.getVisibleBubbleSeriesIndex(),f.bubbleLegend.visible!==a&&(f.update({bubbleLegend:{enabled:a}}),f.bubbleLegend.visible=a),this.visible=b)});z(y.prototype,"drawChartBox",function(a,b,f){var c=this.legend,g=0<=this.getVisibleBubbleSeriesIndex();
if(c&&c.options.enabled&&c.bubbleLegend&&c.options.bubbleLegend.autoRanges&&g){var d=c.bubbleLegend.options;g=c.bubbleLegend.predictBubbleSizes();c.bubbleLegend.updateRanges(g[0],g[1]);d.placed||(c.group.placed=!1,c.allItems.forEach(function(a){a.legendGroup.translateY=null}));c.render();this.getMargins();this.axes.forEach(function(a){a.visible&&a.render();d.placed||(a.setScale(),a.updateNames(),h(a.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))});d.placed=!0;this.getMargins();a.call(this,b,f);c.bubbleLegend.correctSizes();
c.retranslateItems(c.getLinesHeights())}else a.call(this,b,f),c&&c.options.enabled&&c.bubbleLegend&&(c.render(),c.retranslateItems(c.getLinesHeights()))});e.BubbleLegend=r;return e.BubbleLegend});B(e,"parts-more/BubbleSeries.js",[e["parts/Globals.js"],e["parts/Color.js"],e["parts/Point.js"],e["parts/Utilities.js"]],function(e,b,d,a){var m=b.parse,l=a.arrayMax,w=a.arrayMin,D=a.clamp,x=a.extend,h=a.isNumber,t=a.pick,q=a.pInt;b=a.seriesType;a=e.Axis;var z=e.noop,k=e.Series,y=e.seriesTypes;b("bubble",
"scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],
specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(a,b){var c=this.options.marker.fillOpacity;a=k.prototype.pointAttribs.call(this,a,b);1!==c&&(a.fill=m(a.fill).setOpacity(c).get("rgba"));return a},getRadii:function(a,b,c){var h=this.zData,f=this.yData,p=c.minPxSize,d=c.maxPxSize,k=[];var n=0;for(c=h.length;n<c;n++){var e=h[n];k.push(this.getRadius(a,b,p,d,e,f[n]))}this.radii=k},getRadius:function(a,b,c,g,f,p){var d=this.options,k="width"!==d.sizeBy,
n=d.zThreshold,e=b-a,m=.5;if(null===p||null===f)return null;if(h(f)){d.sizeByAbsoluteValue&&(f=Math.abs(f-n),e=Math.max(b-n,Math.abs(a-n)),a=0);if(f<a)return c/2-1;0<e&&(m=(f-a)/e)}k&&0<=m&&(m=Math.sqrt(m));return Math.ceil(c+m*(g-c))/2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&this.points.forEach(function(a){var b=a.graphic;if(b&&b.width){var h={x:b.x,y:b.y,width:b.width,height:b.height};b.attr({x:a.plotX,y:a.plotY,width:1,height:1});b.animate(h,this.options.animation)}},
this)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,b=this.data,c=this.radii;y.scatter.prototype.translate.call(this);for(a=b.length;a--;){var g=b[a];var f=c?c[a]:0;h(f)&&f>=this.minPxSize/2?(g.marker=x(g.marker,{radius:f,width:2*f,height:2*f}),g.dlBox={x:g.plotX-f,y:g.plotY-f,width:2*f,height:2*f}):g.shapeArgs=g.plotY=g.dlBox=void 0}},alignDataLabel:y.column.prototype.alignDataLabel,buildKDTree:z,applyZones:z},{haloPath:function(a){return d.prototype.haloPath.call(this,
0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});a.prototype.beforePadding=function(){var a=this,b=this.len,c=this.chart,g=0,f=b,p=this.isXAxis,d=p?"xData":"yData",k=this.min,n={},e=Math.min(c.plotWidth,c.plotHeight),m=Number.MAX_VALUE,u=-Number.MAX_VALUE,z=this.max-k,x=b/z,y=[];this.series.forEach(function(f){var b=f.options;!f.bubblePadding||!f.visible&&c.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,y.push(f),p&&(["minSize","maxSize"].forEach(function(a){var f=b[a],c=/%$/.test(f);
f=q(f);n[a]=c?e*f/100:f}),f.minPxSize=n.minSize,f.maxPxSize=Math.max(n.maxSize,n.minSize),f=f.zData.filter(h),f.length&&(m=t(b.zMin,D(w(f),!1===b.displayNegative?b.zThreshold:-Number.MAX_VALUE,m)),u=t(b.zMax,Math.max(u,l(f))))))});y.forEach(function(b){var c=b[d],n=c.length;p&&b.getRadii(m,u,b);if(0<z)for(;n--;)if(h(c[n])&&a.dataMin<=c[n]&&c[n]<=a.max){var e=b.radii?b.radii[n]:0;g=Math.min((c[n]-k)*x-e,g);f=Math.max((c[n]-k)*x+e,f)}});y.length&&0<z&&!this.isLog&&(f-=b,x*=(b+Math.max(0,g)-Math.min(f,
b))/b,[["min","userMin",g],["max","userMax",f]].forEach(function(f){"undefined"===typeof t(a.options[f[0]],a[f[1]])&&(a[f[0]]+=f[2]/x)}))};""});B(e,"modules/networkgraph/integrations.js",[e["parts/Globals.js"]],function(e){e.networkgraphIntegrations={verlet:{attractiveForceFunction:function(b,d){return(d-b)/b},repulsiveForceFunction:function(b,d){return(d-b)/b*(d>b?1:0)},barycenter:function(){var b=this.options.gravitationalConstant,d=this.barycenter.xFactor,a=this.barycenter.yFactor;d=(d-(this.box.left+
this.box.width)/2)*b;a=(a-(this.box.top+this.box.height)/2)*b;this.nodes.forEach(function(b){b.fixedPosition||(b.plotX-=d/b.mass/b.degree,b.plotY-=a/b.mass/b.degree)})},repulsive:function(b,d,a){d=d*this.diffTemperature/b.mass/b.degree;b.fixedPosition||(b.plotX+=a.x*d,b.plotY+=a.y*d)},attractive:function(b,d,a){var e=b.getMass(),l=-a.x*d*this.diffTemperature;d=-a.y*d*this.diffTemperature;b.fromNode.fixedPosition||(b.fromNode.plotX-=l*e.fromNode/b.fromNode.degree,b.fromNode.plotY-=d*e.fromNode/b.fromNode.degree);
b.toNode.fixedPosition||(b.toNode.plotX+=l*e.toNode/b.toNode.degree,b.toNode.plotY+=d*e.toNode/b.toNode.degree)},integrate:function(b,d){var a=-b.options.friction,e=b.options.maxSpeed,l=(d.plotX+d.dispX-d.prevX)*a;a*=d.plotY+d.dispY-d.prevY;var w=Math.abs,D=w(l)/(l||1);w=w(a)/(a||1);l=D*Math.min(e,Math.abs(l));a=w*Math.min(e,Math.abs(a));d.prevX=d.plotX+d.dispX;d.prevY=d.plotY+d.dispY;d.plotX+=l;d.plotY+=a;d.temperature=b.vectorLength({x:l,y:a})},getK:function(b){return Math.pow(b.box.width*b.box.height/
b.nodes.length,.5)}},euler:{attractiveForceFunction:function(b,d){return b*b/d},repulsiveForceFunction:function(b,d){return d*d/b},barycenter:function(){var b=this.options.gravitationalConstant,d=this.barycenter.xFactor,a=this.barycenter.yFactor;this.nodes.forEach(function(e){if(!e.fixedPosition){var m=e.getDegree();m*=1+m/2;e.dispX+=(d-e.plotX)*b*m/e.degree;e.dispY+=(a-e.plotY)*b*m/e.degree}})},repulsive:function(b,d,a,e){b.dispX+=a.x/e*d/b.degree;b.dispY+=a.y/e*d/b.degree},attractive:function(b,
d,a,e){var m=b.getMass(),l=a.x/e*d;d*=a.y/e;b.fromNode.fixedPosition||(b.fromNode.dispX-=l*m.fromNode/b.fromNode.degree,b.fromNode.dispY-=d*m.fromNode/b.fromNode.degree);b.toNode.fixedPosition||(b.toNode.dispX+=l*m.toNode/b.toNode.degree,b.toNode.dispY+=d*m.toNode/b.toNode.degree)},integrate:function(b,d){d.dispX+=d.dispX*b.options.friction;d.dispY+=d.dispY*b.options.friction;var a=d.temperature=b.vectorLength({x:d.dispX,y:d.dispY});0!==a&&(d.plotX+=d.dispX/a*Math.min(Math.abs(d.dispX),b.temperature),
d.plotY+=d.dispY/a*Math.min(Math.abs(d.dispY),b.temperature))},getK:function(b){return Math.pow(b.box.width*b.box.height/b.nodes.length,.3)}}}});B(e,"modules/networkgraph/QuadTree.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(e,b){b=b.extend;var d=e.QuadTreeNode=function(a){this.box=a;this.boxSize=Math.min(a.width,a.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};b(d.prototype,{insert:function(a,b){this.isInternal?this.nodes[this.getBoxPosition(a)].insert(a,b-1):
(this.isEmpty=!1,this.body?b?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,b-1),this.body=!0),this.nodes[this.getBoxPosition(a)].insert(a,b-1)):(b=new d({top:a.plotX,left:a.plotY,width:.1,height:.1}),b.body=a,b.isInternal=!1,this.nodes.push(b)):(this.isInternal=!1,this.body=a))},updateMassAndCenter:function(){var a=0,b=0,d=0;this.isInternal?(this.nodes.forEach(function(e){e.isEmpty||(a+=e.mass,b+=e.plotX*e.mass,d+=e.plotY*e.mass)}),
b/=a,d/=a):this.body&&(a=this.body.mass,b=this.body.plotX,d=this.body.plotY);this.mass=a;this.plotX=b;this.plotY=d},divideBox:function(){var a=this.box.width/2,b=this.box.height/2;this.nodes[0]=new d({left:this.box.left,top:this.box.top,width:a,height:b});this.nodes[1]=new d({left:this.box.left+a,top:this.box.top,width:a,height:b});this.nodes[2]=new d({left:this.box.left+a,top:this.box.top+b,width:a,height:b});this.nodes[3]=new d({left:this.box.left,top:this.box.top+b,width:a,height:b})},getBoxPosition:function(a){var b=
a.plotY<this.box.top+this.box.height/2;return a.plotX<this.box.left+this.box.width/2?b?0:3:b?1:2}});e=e.QuadTree=function(a,b,e,l){this.box={left:a,top:b,width:e,height:l};this.maxDepth=25;this.root=new d(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};b(e.prototype,{insertNodes:function(a){a.forEach(function(a){this.root.insert(a,this.maxDepth)},this)},visitNodeRecursive:function(a,b,d){var e;a||(a=this.root);a===this.root&&b&&(e=b(a));!1!==e&&(a.nodes.forEach(function(a){if(a.isInternal){b&&
(e=b(a));if(!1===e)return;this.visitNodeRecursive(a,b,d)}else a.body&&b&&b(a.body);d&&d(a)},this),a===this.root&&d&&d(a))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(a){a.updateMassAndCenter()})}})});B(e,"modules/networkgraph/layouts.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(e,b){var d=b.addEvent,a=b.clamp,l=b.defined,u=b.extend,w=b.isFunction,D=b.pick,x=b.setAnimation;b=e.Chart;e.layouts={"reingold-fruchterman":function(){}};u(e.layouts["reingold-fruchterman"].prototype,
{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=e.networkgraphIntegrations[a.integration];this.enableSimulation=a.enableSimulation;this.attractiveForce=D(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=D(a.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=a.approximation},updateSimulation:function(a){this.enableSimulation=D(a,this.options.enableSimulation)},
start:function(){var a=this.series,b=this.options;this.currentStep=0;this.forces=a[0]&&a[0].forces||[];this.chart=a[0]&&a[0].chart;this.initialRendering&&(this.initPositions(),a.forEach(function(a){a.render()}));this.setK();this.resetSimulation(b);this.enableSimulation&&this.step()},step:function(){var a=this,b=this.series;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),a.quadTree.calculateMassAndCenter());a.forces.forEach(function(b){a[b+"Forces"](a.temperature)});a.applyLimits(a.temperature);
a.temperature=a.coolDown(a.startTemperature,a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;a.systemTemperature=a.getSystemTemperature();a.enableSimulation&&(b.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()?(a.simulation&&e.win.cancelAnimationFrame(a.simulation),a.simulation=e.win.requestAnimationFrame(function(){a.step()})):a.simulation=!1)},stop:function(){this.simulation&&e.win.cancelAnimationFrame(this.simulation)},
setArea:function(a,b,d,e){this.box={left:a,top:b,width:d,height:e}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(a,b){a.forEach(function(a){-1===b.indexOf(a)&&b.push(a)})},removeElementFromCollection:function(a,b){a=b.indexOf(a);-1!==a&&b.splice(a,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();
this.setTemperature();this.setDiffTemperature()},setMaxIterations:function(a){this.maxIterations=D(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)},setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=new e.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);
this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=this.options.initialPositions;w(a)?(a.call(this),this.nodes.forEach(function(a){l(a.prevX)||(a.prevX=a.plotX);l(a.prevY)||(a.prevY=a.plotY);a.dispX=0;a.dispY=0})):"circle"===a?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function a(b){b.linksFrom.forEach(function(b){m[b.toNode.id]||(m[b.toNode.id]=!0,l.push(b.toNode),a(b.toNode))})}var b=this.box,d=this.nodes,e=2*Math.PI/(d.length+1),k=
d.filter(function(a){return 0===a.linksTo.length}),l=[],m={},r=this.options.initialPositionRadius;k.forEach(function(b){l.push(b);a(b)});l.length?d.forEach(function(a){-1===l.indexOf(a)&&l.push(a)}):l=d;l.forEach(function(a,g){a.plotX=a.prevX=D(a.plotX,b.width/2+r*Math.cos(g*e));a.plotY=a.prevY=D(a.plotY,b.height/2+r*Math.sin(g*e));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=a*a/Math.PI;return a-=Math.floor(a)}var b=this.box,d=this.nodes,e=d.length+1;d.forEach(function(h,
d){h.plotX=h.prevX=D(h.plotX,b.width*a(d));h.plotY=h.prevY=D(h.plotY,b.height*a(e+d));h.dispX=0;h.dispY=0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();this.force("barycenter")},getBarycenter:function(){var a=0,b=0,d=0;this.nodes.forEach(function(h){b+=h.plotX*h.mass;d+=h.plotY*h.mass;a+=h.mass});return this.barycenter={x:b,y:d,xFactor:b/a,yFactor:d/a}},barnesHutApproximation:function(a,b){var d=this.getDistXY(a,
b),h=this.vectorLength(d);if(a!==b&&0!==h)if(b.isInternal)if(b.boxSize/h<this.options.theta&&0!==h){var e=this.repulsiveForce(h,this.k);this.force("repulsive",a,e*b.mass,d,h);var l=!1}else l=!0;else e=this.repulsiveForce(h,this.k),this.force("repulsive",a,e*b.mass,d,h);return l},repulsiveForces:function(){var a=this;"barnes-hut"===a.approximation?a.nodes.forEach(function(b){a.quadTree.visitNodeRecursive(null,function(d){return a.barnesHutApproximation(b,d)})}):a.nodes.forEach(function(b){a.nodes.forEach(function(d){if(b!==
d&&!b.fixedPosition){var h=a.getDistXY(b,d);var e=a.vectorLength(h);if(0!==e){var l=a.repulsiveForce(e,a.k);a.force("repulsive",b,l*d.mass,h,e)}}})})},attractiveForces:function(){var a=this,b,d,e;a.links.forEach(function(h){h.fromNode&&h.toNode&&(b=a.getDistXY(h.fromNode,h.toNode),d=a.vectorLength(b),0!==d&&(e=a.attractiveForce(d,a.k),a.force("attractive",h,e,b,d)))})},applyLimits:function(){var a=this;a.nodes.forEach(function(b){b.fixedPosition||(a.integration.integrate(a,b),a.applyLimitBox(b,a.box),
b.dispX=0,b.dispY=0)})},applyLimitBox:function(b,d){var e=b.radius;b.plotX=a(b.plotX,d.left+e,d.width-e);b.plotY=a(b.plotY,d.top+e,d.height-e)},coolDown:function(a,b,d){return a-b*d},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,b){return a+b.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,b){a=this.getDistXY(a,b);
return this.vectorLength(a)},getDistXY:function(a,b){var d=a.plotX-b.plotX;a=a.plotY-b.plotY;return{x:d,y:a,absX:Math.abs(d),absY:Math.abs(a)}}});d(b,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});d(b,"render",function(){function a(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),d=!1,b=!0)}var b=!1;if(this.graphLayoutsLookup){x(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!d;){var d=
!0;this.graphLayoutsLookup.forEach(a)}b&&this.series.forEach(function(a){a&&a.layout&&a.render()})}});d(b,"beforePrint",function(){this.graphLayoutsLookup.forEach(function(a){a.updateSimulation(!1)});this.redraw()});d(b,"afterPrint",function(){this.graphLayoutsLookup.forEach(function(a){a.updateSimulation()});this.redraw()})});B(e,"modules/networkgraph/draggable-nodes.js",[e["parts/Globals.js"],e["parts/Utilities.js"]],function(e,b){var d=b.addEvent;b=e.Chart;e.dragNodesMixin={onMouseDown:function(a,
b){b=this.chart.pointer.normalize(b);a.fixedPosition={chartX:b.chartX,chartY:b.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,b){if(a.fixedPosition&&a.inDragMode){var d=this.chart,e=d.pointer.normalize(b);b=a.fixedPosition.chartX-e.chartX;e=a.fixedPosition.chartY-e.chartY;if(5<Math.abs(b)||5<Math.abs(e))b=a.fixedPosition.plotX-b,e=a.fixedPosition.plotY-e,d.isInsidePlot(b,e)&&(a.plotX=b,a.plotY=e,a.hasDragged=!0,this.redrawHalo(a),this.layout.simulation?this.layout.resetSimulation():
(this.layout.setInitialRendering(!1),this.layout.enableSimulation?this.layout.start():this.layout.setMaxIterations(1),this.chart.redraw(),this.layout.setInitialRendering(!0)))}},onMouseUp:function(a,b){a.fixedPosition&&a.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw(),a.inDragMode=a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};d(b,"load",
function(){var a=this,b,e,l;a.container&&(b=d(a.container,"mousedown",function(b){var m=a.hoverPoint;m&&m.series&&m.series.hasDraggableNodes&&m.series.options.draggable&&(m.series.onMouseDown(m,b),e=d(a.container,"mousemove",function(a){return m&&m.series&&m.series.onMouseMove(m,a)}),l=d(a.container.ownerDocument,"mouseup",function(a){e();l();return m&&m.series&&m.series.onMouseUp(m,a)}))}));d(a,"destroy",function(){b()})})});B(e,"parts-more/PackedBubbleSeries.js",[e["parts/Globals.js"],e["parts/Color.js"],
e["parts/Point.js"],e["parts/Utilities.js"]],function(e,b,d,a){var l=b.parse,u=a.addEvent,w=a.clamp,D=a.defined,x=a.extend;b=a.extendClass;var h=a.fireEvent,t=a.isArray,q=a.isNumber,z=a.merge,k=a.pick;a=a.seriesType;var y=e.Series,A=e.Chart,r=e.layouts["reingold-fruchterman"],c=e.seriesTypes.bubble.prototype.pointClass,g=e.dragNodesMixin;e.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,b,c,g){return Math.min(a,(c.marker.radius+g.marker.radius)/2)},barycenter:function(){var a=
this,b=a.options.gravitationalConstant,c=a.box,g=a.nodes,d,e;g.forEach(function(f){a.options.splitSeries&&!f.isParentNode?(d=f.series.parentNode.plotX,e=f.series.parentNode.plotY):(d=c.width/2,e=c.height/2);f.fixedPosition||(f.plotX-=(f.plotX-d)*b/(f.mass*Math.sqrt(g.length)),f.plotY-=(f.plotY-e)*b/(f.mass*Math.sqrt(g.length)))})},repulsive:function(a,b,c,g){var f=b*this.diffTemperature/a.mass/a.degree;b=c.x*f;c=c.y*f;a.fixedPosition||(a.plotX+=b,a.plotY+=c);g.fixedPosition||(g.plotX-=b,g.plotY-=
c)},integrate:e.networkgraphIntegrations.verlet.integrate,getK:e.noop};e.layouts.packedbubble=b(r,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},setCircularPositions:function(){var a=this,b=a.box,c=a.nodes,g=2*Math.PI/(c.length+1),d,e,h=a.options.initialPositionRadius;c.forEach(function(f,c){a.options.splitSeries&&!f.isParentNode?(d=f.series.parentNode.plotX,e=f.series.parentNode.plotY):(d=b.width/2,e=b.height/2);f.plotX=f.prevX=k(f.plotX,
d+h*Math.cos(f.index||c*g));f.plotY=f.prevY=k(f.plotY,e+h*Math.sin(f.index||c*g));f.dispX=0;f.dispY=0})},repulsiveForces:function(){var a=this,b,c,g,d=a.options.bubblePadding;a.nodes.forEach(function(f){f.degree=f.mass;f.neighbours=0;a.nodes.forEach(function(e){b=0;f===e||f.fixedPosition||!a.options.seriesInteraction&&f.series!==e.series||(g=a.getDistXY(f,e),c=a.vectorLength(g)-(f.marker.radius+e.marker.radius+d),0>c&&(f.degree+=.01,f.neighbours++,b=a.repulsiveForce(-c/Math.sqrt(f.neighbours),a.k,
f,e)),a.force("repulsive",f,b*e.mass,g,e,c))})})},applyLimitBox:function(a){if(this.options.splitSeries&&!a.isParentNode&&this.options.parentNodeLimit){var b=this.getDistXY(a,a.series.parentNode);var f=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(b);0>f&&f>-2*a.marker.radius&&(a.plotX-=.01*b.x,a.plotY-=.01*b.y)}r.prototype.applyLimitBox.apply(this,arguments)}});a("packedbubble","bubble",{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",tooltip:{pointFormat:"Value: {point.value}"},
draggable:!0,useSimulation:!0,dataLabels:{formatter:function(){return this.point.value},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0},layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:1,lineColor:null,
symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}},{hasDraggableNodes:!0,forces:["barycenter","repulsive"],pointArrayMap:["value"],pointValKey:"value",isCartesian:!1,requireSorting:!1,directTouch:!0,axisTypes:[],noSharedTooltip:!0,searchPoint:e.noop,accumulateAllPoints:function(a){var b=a.chart,f=[],c,g;for(c=0;c<b.series.length;c++)if(a=b.series[c],a.visible||!b.options.chart.ignoreHiddenSeries)for(g=
0;g<a.yData.length;g++)f.push([null,null,a.yData[g],a.index,g,{id:g,marker:{radius:0}}]);return f},init:function(){y.prototype.init.apply(this,arguments);u(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)});return this},render:function(){var a=[];y.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(b){t(b.dataLabels)&&b.dataLabels.forEach(function(b){a.push(b)})}),this.options.useSimulation&&
this.chart.hideOverlappingLabels(a))},setVisible:function(){var a=this;y.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,a.parentNodeLayout.nodes),a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(b){a.layout.removeElementFromCollection(b,
a.layout.nodes)}))},drawDataLabels:function(){var a=this.options.dataLabels.textPath,b=this.points;y.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,y.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)},seriesBox:function(){var a=this.chart,b=Math.max,c=Math.min,g,d=[a.plotLeft,a.plotLeft+
a.plotWidth,a.plotTop,a.plotTop+a.plotHeight];this.data.forEach(function(a){D(a.plotX)&&D(a.plotY)&&a.marker.radius&&(g=a.marker.radius,d[0]=c(d[0],a.plotX-g),d[1]=b(d[1],a.plotX+g),d[2]=c(d[2],a.plotY-g),d[3]=b(d[3],a.plotY+g))});return q(d.width/d.height)?d:null},calculateParentRadius:function(){var a=this.seriesBox();this.parentNodeRadius=w(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+
20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)},drawGraph:function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart,b=this.layout.options.parentNodeOptions.marker;b={fill:b.fillColor||l(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||this.color,"stroke-width":b.lineWidth};var c=this.visible?"inherit":"hidden";this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",c,
.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();c=z({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},b);this.parentNode.graphic||(this.graph=this.parentNode.graphic=a.renderer.symbol(b.symbol).add(this.parentNodesGroup));this.parentNode.graphic.attr(c)}},createParentNodes:function(){var a=this,b=a.chart,g=a.parentNodeLayout,d,e=a.parentNode;a.parentNodeMass=0;a.points.forEach(function(b){a.parentNodeMass+=
Math.PI*Math.pow(b.marker.radius,2)});a.calculateParentRadius();g.nodes.forEach(function(b){b.seriesIndex===a.index&&(d=!0)});g.setArea(0,0,b.plotWidth,b.plotHeight);d||(e||(e=(new c).init(this,{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(e.plotX=a.parentNode.plotX,e.plotY=a.parentNode.plotY),a.parentNode=e,g.addElementsToCollection([a],g.series),g.addElementsToCollection([e],
g.nodes))},addSeriesLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=this.chart.graphLayoutsLookup,g=z(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});var d=b[a.type+"-series"];d||(b[a.type+"-series"]=d=new e.layouts[a.type],d.init(g),c.splice(d.index,0,d));this.parentNodeLayout=d;this.createParentNodes()},addLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,c=this.chart.graphLayoutsLookup,g=
this.chart.options.chart;b||(this.chart.graphLayoutsStorage=b={},this.chart.graphLayoutsLookup=c=[]);var d=b[a.type];d||(a.enableSimulation=D(g.forExport)?!g.forExport:a.enableSimulation,b[a.type]=d=new e.layouts[a.type],d.init(a),c.splice(d.index,0,d));this.layout=d;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=1});d.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);d.addElementsToCollection([this],d.series);d.addElementsToCollection(this.points,d.nodes)},deferLayout:function(){var a=
this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())},translate:function(){var a=this.chart,b=this.data,c=this.index,g,d=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();D(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());if(d)var e=a.allDataPoints;else e=this.placeBubbles(a.allDataPoints),this.options.draggable=!1;for(g=0;g<e.length;g++)if(e[g][3]===c){var k=b[e[g][4]];var l=e[g][2];
d||(k.plotX=e[g][0]-a.plotLeft+a.diffX,k.plotY=e[g][1]-a.plotTop+a.diffY);k.marker=x(k.marker,{radius:l,width:2*l,height:2*l});k.radius=l}d&&this.deferLayout();h(this,"afterTranslate")},checkOverlap:function(a,b){var f=a[0]-b[0],c=a[1]-b[1];return-.001>Math.sqrt(f*f+c*c)-Math.abs(a[2]+b[2])},positionBubble:function(a,b,c){var f=Math.sqrt,g=Math.asin,d=Math.acos,e=Math.pow,h=Math.abs;f=f(e(a[0]-b[0],2)+e(a[1]-b[1],2));d=d((e(f,2)+e(c[2]+b[2],2)-e(c[2]+a[2],2))/(2*(c[2]+b[2])*f));g=g(h(a[0]-b[0])/f);
a=(0>a[1]-b[1]?0:Math.PI)+d+g*(0>(a[0]-b[0])*(a[1]-b[1])?1:-1);return[b[0]+(b[2]+c[2])*Math.sin(a),b[1]-(b[2]+c[2])*Math.cos(a),c[2],c[3],c[4]]},placeBubbles:function(a){var b=this.checkOverlap,f=this.positionBubble,c=[],g=1,d=0,e=0;var h=[];var k;a=a.sort(function(a,b){return b[2]-a[2]});if(a.length){c.push([[0,0,a[0][2],a[0][3],a[0][4]]]);if(1<a.length)for(c.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),k=2;k<a.length;k++)a[k][2]=a[k][2]||1,h=f(c[g][d],c[g-1][e],a[k]),b(h,c[g][0])?(c.push([]),
e=0,c[g+1].push(f(c[g][d],c[g][0],a[k])),g++,d=0):1<g&&c[g-1][e+1]&&b(h,c[g-1][e+1])?(e++,c[g].push(f(c[g][d],c[g-1][e],a[k])),d++):(d++,c[g].push(h));this.chart.stages=c;this.chart.rawPositions=[].concat.apply([],c);this.resizeRadius();h=this.chart.rawPositions}return h},resizeRadius:function(){var a=this.chart,b=a.rawPositions,c=Math.min,g=Math.max,d=a.plotLeft,e=a.plotTop,h=a.plotHeight,k=a.plotWidth,l,m,q;var r=l=Number.POSITIVE_INFINITY;var t=m=Number.NEGATIVE_INFINITY;for(q=0;q<b.length;q++){var u=
b[q][2];r=c(r,b[q][0]-u);t=g(t,b[q][0]+u);l=c(l,b[q][1]-u);m=g(m,b[q][1]+u)}q=[t-r,m-l];c=c.apply([],[(k-d)/q[0],(h-e)/q[1]]);if(1e-10<Math.abs(c-1)){for(q=0;q<b.length;q++)b[q][2]*=c;this.placeBubbles(b)}else a.diffY=h/2+e-l-(m-l)/2,a.diffX=k/2+d-r-(t-r)/2},calculateZExtremes:function(){var a=this.options.zMin,b=this.options.zMax,c=Infinity,g=-Infinity;if(a&&b)return[a,b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){D(a)&&(a>g&&(g=a),a<c&&(c=a))})});a=k(a,c);b=k(b,g);return[a,
b]},getPointRadius:function(){var a=this,b=a.chart,c=a.options,g=c.useSimulation,d=Math.min(b.plotWidth,b.plotHeight),e={},h=[],k=b.allDataPoints,l,m,q,r;["minSize","maxSize"].forEach(function(a){var b=parseInt(c[a],10),f=/%$/.test(c[a]);e[a]=f?d*b/100:b*Math.sqrt(k.length)});b.minRadius=l=e.minSize/Math.sqrt(k.length);b.maxRadius=m=e.maxSize/Math.sqrt(k.length);var t=g?a.calculateZExtremes():[l,m];(k||[]).forEach(function(b,c){q=g?w(b[2],t[0],t[1]):b[2];r=a.getRadius(t[0],t[1],l,m,q);0===r&&(r=null);
k[c][2]=r;h.push(r)});a.radii=h},redrawHalo:g.redrawHalo,onMouseDown:g.onMouseDown,onMouseMove:g.onMouseMove,onMouseUp:function(a){if(a.fixedPosition&&!a.removed){var b,c,f=this.layout,d=this.parentNodeLayout;d&&f.options.dragBetweenSeries&&d.nodes.forEach(function(g){a&&a.marker&&g!==a.series.parentNode&&(b=f.getDistXY(a,g),c=f.vectorLength(b)-g.marker.radius-a.marker.radius,0>c&&(g.series.addPoint(z(a.options,{plotX:a.plotX,plotY:a.plotY}),!1),f.removeElementFromCollection(a,f.nodes),a.remove()))});
g.onMouseUp.apply(this,arguments)}},destroy:function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,a.series)},this);this.parentNode&&(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));e.Series.prototype.destroy.apply(this,arguments)},alignDataLabel:e.Series.prototype.alignDataLabel},{destroy:function(){this.series.layout&&
this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return d.prototype.destroy.apply(this,arguments)}});u(A,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints});""});B(e,"parts-more/Polar.js",[e["parts/Globals.js"],e["parts/Utilities.js"],e["parts-more/Pane.js"]],function(e,b,d){var a=b.addEvent,l=b.animObject,u=b.defined,w=b.find,D=b.isNumber,x=b.pick,h=b.splat,t=b.uniqueKey,q=b.wrap,z=e.Series,k=e.seriesTypes,y=z.prototype,A=e.Pointer.prototype;y.searchPointByAngle=
function(a){var b=this.chart,c=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-c[0]-b.plotLeft,a.chartY-c[1]-b.plotTop)})};y.getConnectors=function(a,b,f,d){var c=d?1:0;var g=0<=b&&b<=a.length-1?b:0>b?a.length-1+b:0;b=0>g-1?a.length-(1+c):g-1;c=g+1>a.length-1?c:g+1;var e=a[b];c=a[c];var h=e.plotX;e=e.plotY;var k=c.plotX;var p=c.plotY;c=a[g].plotX;g=a[g].plotY;h=(1.5*c+h)/2.5;e=(1.5*g+e)/2.5;k=(1.5*c+k)/2.5;var l=(1.5*g+p)/2.5;p=Math.sqrt(Math.pow(h-c,
2)+Math.pow(e-g,2));var m=Math.sqrt(Math.pow(k-c,2)+Math.pow(l-g,2));h=Math.atan2(e-g,h-c);l=Math.PI/2+(h+Math.atan2(l-g,k-c))/2;Math.abs(h-l)>Math.PI/2&&(l-=Math.PI);h=c+Math.cos(l)*p;e=g+Math.sin(l)*p;k=c+Math.cos(Math.PI+l)*m;l=g+Math.sin(Math.PI+l)*m;c={rightContX:k,rightContY:l,leftContX:h,leftContY:e,plotX:c,plotY:g};f&&(c.prevPointCont=this.getConnectors(a,b,!1,d));return c};y.toXY=function(a){var b=this.chart,c=this.xAxis;var d=this.yAxis;var e=a.plotX,h=a.plotY,k=a.series,l=b.inverted,m=
a.y,q=l?e:d.len-h;l&&k&&!k.isRadialBar&&(a.plotY=h="number"===typeof m?d.translate(m)||0:0);a.rectPlotX=e;a.rectPlotY=h;d.center&&(q+=d.center[3]/2);d=l?d.postTranslate(h,q):c.postTranslate(e,q);a.plotX=a.polarPlotX=d.x-b.plotLeft;a.plotY=a.polarPlotY=d.y-b.plotTop;this.kdByAngle?(b=(e/Math.PI*180+c.pane.options.startAngle)%360,0>b&&(b+=360),a.clientX=b):a.clientX=a.plotX};k.spline&&(q(k.spline.prototype,"getPointSpline",function(a,b,f,d){this.chart.polar?d?(a=this.getConnectors(b,d,!0,this.connectEnds),
a=["C",a.prevPointCont.rightContX,a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",f.plotX,f.plotY]:a=a.call(this,b,f,d);return a}),k.areasplinerange&&(k.areasplinerange.prototype.getPointSpline=k.spline.prototype.getPointSpline));a(z,"afterTranslate",function(){var b=this.chart;if(b.polar&&this.xAxis){(this.kdByAngle=b.tooltip&&b.tooltip.shared)?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(var g=this.points,
f=g.length;f--;)this.toXY(g[f]),!b.hasParallelCoordinates&&!this.yAxis.reversed&&g[f].y<this.yAxis.min&&(g[f].isNull=!0);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!this.eventsToUnbind.push(a(this,"afterRender",function(){if(b.polar){var a=this.yAxis.pane.center;this.clipCircle?this.clipCircle.animate({x:a[0],y:a[1],r:a[2]/2,innerR:a[3]/2}):this.clipCircle=b.renderer.clipCircle(a[0],a[1],a[2]/2,a[3]/2);this.group.clip(this.clipCircle);this.setClip=e.noop}})))}},{order:2});q(y,"getGraphPath",
function(a,b){var c=this,d;if(this.chart.polar){b=b||this.points;for(d=0;d<b.length;d++)if(!b[d].isNull){var g=d;break}if(!1!==this.options.connectEnds&&"undefined"!==typeof g){this.connectEnds=!0;b.splice(b.length,0,b[g]);var e=!0}b.forEach(function(a){"undefined"===typeof a.polarPlotY&&c.toXY(a)})}d=a.apply(this,[].slice.call(arguments,1));e&&b.pop();return d});var r=function(a,b){var c=this,d=this.chart,g=this.options.animation,h=this.group,k=this.markerGroup,m=this.xAxis.center,q=d.plotLeft,r=
d.plotTop,t,u,y,w;if(d.polar)if(c.isRadialBar)b||(c.startAngleRad=x(c.translatedThreshold,c.xAxis.startAngleRad),e.seriesTypes.pie.prototype.animate.call(c,b));else{if(d.renderer.isSVG)if(g=l(g),c.is("column")){if(!b){var z=m[3]/2;c.points.forEach(function(a){t=a.graphic;y=(u=a.shapeArgs)&&u.r;w=u&&u.innerR;t&&u&&(t.attr({r:z,innerR:z}),t.animate({r:y,innerR:w},c.options.animation))})}}else b?(a={translateX:m[0]+q,translateY:m[1]+r,scaleX:.001,scaleY:.001},h.attr(a),k&&k.attr(a)):(a={translateX:q,
translateY:r,scaleX:1,scaleY:1},h.animate(a,g),k&&k.animate(a,g))}else a.call(this,b)};q(y,"animate",r);k.column&&(z=k.arearange.prototype,k=k.column.prototype,k.polarArc=function(a,b,d,e){var c=this.xAxis.center,g=this.yAxis.len,f=c[3]/2;b=g-b+f;a=g-x(a,g)+f;this.yAxis.reversed&&(0>b&&(b=f),0>a&&(a=f));return{x:c[0],y:c[1],r:b,innerR:a,start:d,end:e}},q(k,"animate",r),q(k,"translate",function(a){var c=this.options,d=c.stacking,e=this.chart,h=this.xAxis,k=this.yAxis,l=k.reversed,m=k.center,q=h.startAngleRad,
r=h.endAngleRad-q;this.preventPostTranslate=!0;a.call(this);if(h.isRadial){a=this.points;h=a.length;var t=k.translate(k.min);var y=k.translate(k.max);c=c.threshold||0;if(e.inverted&&D(c)){var x=k.translate(c);u(x)&&(0>x?x=0:x>r&&(x=r),this.translatedThreshold=x+q)}for(;h--;){c=a[h];var w=c.barX;var z=c.x;var A=c.y;c.shapeType="arc";if(e.inverted){c.plotY=k.translate(A);if(d){if(A=k.stacks[(0>A?"-":"")+this.stackKey],this.visible&&A&&A[z]&&!c.isNull){var B=A[z].points[this.getStackIndicator(void 0,
z,this.index).key];var F=k.translate(B[0]);B=k.translate(B[1]);u(F)&&(F=b.clamp(F,0,r))}}else F=x,B=c.plotY;F>B&&(B=[F,F=B][0]);if(!l)if(F<t)F=t;else if(B>y)B=y;else{if(B<t||F>y)F=B=0}else if(B>t)B=t;else if(F<y)F=y;else if(F>t||B<y)F=B=r;k.min>k.max&&(F=B=l?r:0);F+=q;B+=q;m&&(c.barX=w+=m[3]/2);z=Math.max(w,0);A=Math.max(w+c.pointWidth,0);c.shapeArgs={x:m&&m[0],y:m&&m[1],r:A,innerR:z,start:F,end:B};c.opacity=F===B?0:void 0;c.plotY=(u(this.translatedThreshold)&&(F<this.translatedThreshold?F:B))-q}else F=
w+q,c.shapeArgs=this.polarArc(c.yBottom,c.plotY,F,F+c.pointWidth);this.toXY(c);e.inverted?(w=k.postTranslate(c.rectPlotY,w+c.pointWidth/2),c.tooltipPos=[w.x-e.plotLeft,w.y-e.plotTop]):c.tooltipPos=[c.plotX,c.plotY];m&&(c.ttBelow=c.plotY>m[1])}}}),k.findAlignments=function(a,b){null===b.align&&(b.align=20<a&&160>a?"left":200<a&&340>a?"right":"center");null===b.verticalAlign&&(b.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle");return b},z&&(z.findAlignments=k.findAlignments),q(k,"alignDataLabel",
function(a,b,d,e,h,k){var c=this.chart,f=x(e.inside,!!this.options.stacking);c.polar?(a=b.rectPlotX/Math.PI*180,c.inverted?(this.forceDL=c.isInsidePlot(b.plotX,Math.round(b.plotY),!1),f&&b.shapeArgs?(h=b.shapeArgs,h=this.yAxis.postTranslate((h.start+h.end)/2-this.xAxis.startAngleRad,b.barX+b.pointWidth/2),h={x:h.x-c.plotLeft,y:h.y-c.plotTop}):b.tooltipPos&&(h={x:b.tooltipPos[0],y:b.tooltipPos[1]}),e.align=x(e.align,"center"),e.verticalAlign=x(e.verticalAlign,"middle")):this.findAlignments&&(e=this.findAlignments(a,
e)),y.alignDataLabel.call(this,b,d,e,h,k),this.isRadialBar&&b.shapeArgs&&b.shapeArgs.start===b.shapeArgs.end&&d.hide(!0)):a.call(this,b,d,e,h,k)}));q(A,"getCoordinates",function(a,b){var c=this.chart,d={xAxis:[],yAxis:[]};c.polar?c.axes.forEach(function(a){var e=a.isXAxis,f=a.center;if("colorAxis"!==a.coll){var g=b.chartX-f[0]-c.plotLeft;f=b.chartY-f[1]-c.plotTop;d[e?"xAxis":"yAxis"].push({axis:a,value:a.translate(e?Math.PI-Math.atan2(g,f):Math.sqrt(Math.pow(g,2)+Math.pow(f,2)),!0)})}}):d=a.call(this,
b);return d});e.SVGRenderer.prototype.clipCircle=function(a,b,d,e){var c=t(),f=this.createElement("clipPath").attr({id:c}).add(this.defs);a=e?this.arc(a,b,d,e,0,2*Math.PI).add(f):this.circle(a,b,d).add(f);a.id=c;a.clipPath=f;return a};a(e.Chart,"getAxes",function(){this.pane||(this.pane=[]);h(this.options.pane).forEach(function(a){new d(a,this)},this)});a(e.Chart,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});a(e.Series,"afterInit",function(){var a=this.chart;a.inverted&&
a.polar&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0))});q(e.Chart.prototype,"get",function(a,b){return w(this.pane,function(a){return a.options.id===b})||a.call(this,b)})});B(e,"masters/highcharts-more.src.js",[],function(){})});
//# sourceMappingURL=highcharts-more.js.map